### ISSUE TITLE
Move or label the follow button

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#103]
The button is taking up a bunch of vertical real estate on the screen and it's not labeled at all.  Can it be next to the site name instead of in its own row?  And can it say something like "Follow" instead of just a "+"?

**Comment by Maurier** [comment]
I can make these adjustments.

**Comment by Maurier** [comment]
This change has been deployed at http://envirodiysandbox.usu.edu/sites/NHMU9S/

**Comment by horsburgh** [comment]
Mauriel - this is what I see on the sandbox:

![image](https://user-images.githubusercontent.com/3485902/33919359-8ce229ce-df75-11e7-9f5b-c5f661867674.png)

I don't think this is an improvement. The vertical elipsis is not aligned correctly, and I don't like that the options to edit, delete, and view code snippet are hidden behind the elipsis, which doesn't really even look like a button. I prefer the separate buttons.

**Comment by Maurier** [comment]
This is what I see:
![image](https://user-images.githubusercontent.com/2448568/33920257-2ed58c40-df7a-11e7-9d7d-2df0de78f35b.png)

Can you check if clearing the browser's cache fixes it?

**Comment by horsburgh** [comment]
Nope - didn't fix it. I'm testing in Chrome on my Macbook Pro. Same result in Safari and Firefox. Could it be because my account is a superuser account?

**Comment by Maurier** [comment]
Yes, that could be it. I'll have to test and fix it with a superuser account.

**Comment by Maurier** [comment]
Options to edit, delete, and view code snippet have been reverted to the previous layout and will be reflected on the next sandbox update.

**Comment by SRGDamia1** [comment]
This looks good to me.
