### ISSUE TITLE
Question:  What happens if multiple points are input with the same date/time

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#112]
What happens if a new post request is sent with identical information to a previous request?  What happens if data is sent with the same data/time/GUID's but different values?

**Comment by fryarludwig** [comment]
In the event of a duplicate timestamp, the request fails and is never processed. The user will see a response like below:

`{
    "detail": "EnviroDIY_Mayfly_FreeSRAM value not saved duplicate key value violates unique constraint \"timeseriesresultvalues_resultid_datavalue_valuedatetime_val_key\"\nDETAIL:  Key (resultid, datavalue, valuedatetime, valuedatetimeutcoffset, censorcodecv, qualitycodecv, timeaggregationinterval, timeaggregationintervalunitsid)already exists.\n"
}`

**Comment by SRGDamia1** [comment]
Okay.  Good.  What happens if a single request has some new data and some repeated data (ie, has new humidity data but repeat temp data)?

**Comment by fryarludwig** [comment]
The data we receive is processed individually, so all non-repeated data that's processed before the repeated data will be kept. After repeated data is discovered no more data values from that request are processed.

**Comment by SRGDamia1** [comment]
Can that be changed so the processing does not stop at the first repeat but continues to the end of the request?

**Comment by fryarludwig** [comment]
Yeah, that can be changed.

**Comment by jcaraballo17** [comment]
This sounds like something I can do.

**Comment by horsburgh** [comment]
@fryarludwig - to be clear on this one, if two different data values are submitted for the same variable recorded at the same site at the same date/time, will both data values be written to the database? 

Or, have you implemented logic to ensure that a timestamp can only occur once, so only the first submitted value would be added to the database?

**Comment by fryarludwig** [comment]
The database cannot store two identical timestamps for the same sensor, and any checks for duplicate timestamps are done at the database level. It's a first-come-first-served situation, whichever datavalue gets recorded for a given timestamp first is the "one true datavalue" for said timestamp. If we receive a request with six different values with identical timestamps for one sensor, whichever one of those is first in the list is the one that gets recorded.
