### ISSUE TITLE
Make spark-line headers collapsable

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#113]
The header for the sparkline is as tall as the sparkline itself.  Can the multiple lines of variable/medium/sensor (and added GUID) be compressed to a single line with an optional expander to see everything?

![capture](https://user-images.githubusercontent.com/5374350/34171733-757dc1ba-e4bd-11e7-8a1e-c9c1dc960f1a.JPG)

Don't worry about the lack of data in the capture.  It's from a site I just created, so the data really isn't there.

**Comment by fryarludwig** [comment]
Referencing issue #92 for overlap in site page changes

**Comment by horsburgh** [comment]
@SRGDamia1 - if we combine the envirodiy and leaf pack network websites into one, we are going to have to consider the styling of the page. We will address this issue when we are clear on what we are doing there.

If we were to compress to one line, what information would be on the one line versus what would be collapsed?

**Comment by SRGDamia1** [comment]
I think I would just leave the variable name in the collapsed version.

**Comment by jcaraballo17** [comment]
Not needed anymore. Closing.
