### ISSUE TITLE
Edit SiteType list and add Explanations

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#119]
This follows on the additional changes & features discussed in #28, namely:
* Add explanation tooltips to existing terms from Definition field at http://vocabulary.odm2.org/sitetype/
* Add these terms (from [SamplingFeatureTypeCV](http://vocabulary.odm2.org/samplingfeaturetype/), using those definitions) to the Site Type list currently on EnviroDIY.
    * borehole
    * observationWell
    * streamGage
    * waterQualityStation
    * weatherStation
* Remove this SiteType from our list:
    * aggregateGroundwaterUse (and anything with this would become "observationWell")

**Comment by horsburgh** [comment]
@jcaraballo17 - is this one complete and ready for testing?

**Comment by aufdenkampe** [comment]
Yes, let me know when and where it might be ready for testing!
@jcaraballo17, Thanks for getting on this!

**Comment by aufdenkampe** [comment]
This looks good on Sandbox! Thanks.
