### ISSUE TITLE
Changes to tiles in My sites page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#128]
Rename the tile as the sampling feature code.  The code is generally shorter, so the tiles don't get as big.  And it's redundant to have the tile named as the sampling feature name and then to immediately list the same information below.
![capture](https://user-images.githubusercontent.com/5374350/35237287-3d8c578c-ff78-11e7-8cd5-5b5700d3e957.JPG)

**Comment by aufdenkampe** [comment]
This is a good idea, especially if it is relatively trivial to implement.

**Comment by horsburgh** [comment]
This appears to be complete on the sandbox server. Marking as tested.
