### ISSUE TITLE
Time of most recent point appended is incorrect

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#132]
This is the page immediately after a hard-refresh:

![capture3](https://user-images.githubusercontent.com/5374350/35243486-0fac8996-ff8b-11e7-9737-2de57b251b55.JPG)

**Comment by aufdenkampe** [comment]
I think this has been an error for some time, and I had hoped that it was corrected with #46, but hadn't gone back to test it.

Although it isn't an absolutely critical bug fix, I'm including it in the bug fix milestone in case it is connected to some of the other issues.

**Comment by horsburgh** [comment]
@jcaraballo17 - can you verify where this information is being loaded from? Is it coming from the underlying ODM2 database or is it coming from the InfluxDB cache? Also - which time zone are you reporting those times in?

**Comment by jcaraballo17** [comment]
This problem came up while working on #77 and as of right now it's already fixed on the development branch, so it will be deployed with release 0.5.
It was a problem with the UTC offset, but it's not related to issue #46. 
The latest measurement datetime is displayed in local time. I'll add the UTC offset information so there's less ambiguity.

**Comment by aufdenkampe** [comment]
@jcaraballo17, sounds like a great solution. Thanks!

**Comment by horsburgh** [comment]
@jcaraballo17 and @aufdenkampe - given that this is fixed and will be deployed as part of the 0.5.0 release, I suggest we move this issue to that release rather than trying to do some kind of partial deployment just for this.

**Comment by aufdenkampe** [comment]
Agreed! I tagged it with the 0.4.5 release just in case it was connected to some of the other bugs.

**Comment by aufdenkampe** [comment]
I'm not really sure how to test this on Sandbox, given that no sensors are loading data there.
However, I registered a new site and the Registration date is showing up with the proper time in my Time Zone. I'll consider this fixed.

**Comment by horsburgh** [comment]
@aufdenkampe and @SRGDamia1 - we completely separated the sandbox and production environments, so to adequately test this kind of issue, somebody needs to set up a site to load data to the sandbox.

**Comment by aufdenkampe** [comment]
Right! I realized that after posting.
@SRGDamia1, are you set up to test this issue, and also #131?
If not, I can try to get set up this afternoon.

**Comment by aufdenkampe** [comment]
@SRGDamia1, have ou been able to test this?

**Comment by SRGDamia1** [comment]
My brief tests look good.
