### ISSUE TITLE
Add ability to include free-form comments about sites or sensors

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#134]
This could include information such as the serial number (#32) or other notes.

**Comment by horsburgh** [comment]
@darksinge - is this something you could take on? We could discuss how to implement.

**Comment by horsburgh** [comment]
@jcaraballo17 - given that we have very little time before the end of June, I'm giving this one to you to work on.

**Comment by horsburgh** [comment]
OK, testing on the sandbox - I see where I can add notes when in edit mode, and when I type them in and save my edits they persist. However, they aren't displayed anywhere on the page. Once notes have been added they need to be displayed. @jcaraballo17 - need to add the notes to the views.

**Comment by horsburgh** [comment]
@jcaraballo17 - just tested again on the sandbox, and I don't see this information displayed.

**Comment by horsburgh** [comment]
Thanks @jcaraballo17 - I see my comments displayed on the page now. Adding the "tested" label.

**Comment by aufdenkampe** [comment]
This is working nicely!

**Comment by horsburgh** [comment]
Live on production. Closing.
