### ISSUE TITLE
Separate instrument make and model in drop-downs for adding/editing sensors

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#137]
Creating two separate drop-downs (ie, select "Decagon," then select "CTD") will help keep the list size more manageable as it grows.

**Comment by horsburgh** [comment]
This appears to be functioning correctly on the sanbox. Adding the Tested label.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
