### ISSUE TITLE
Sensibly order items in drop-downs

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#138]
Right now the order of the items in drop down menus (like selecting a sensor) seem to be ordered based on their record number in the database (or something like that).  It would be much better to have them consistently sorted alphabetically or in some other more obvious order.

**Comment by horsburgh** [comment]
This looks good on the sandbox. Marking as tested.

**Comment by SRGDamia1** [comment]
Thanks!
