### ISSUE TITLE
Remove "code snippet"

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#139]
I don't think we want to take the time to keep the snippet up-to-date with the modularSensors library, and as it is, there's not any obvious link to what the snippet is for anyway.

Without the code snippet, issues like #89 and #90 are unimportant and do not need to be dealt with.  It does, however, make it much, much more important to make the GUID for the variables easily view-able (#92) and also to make the token and sampling feature GUID's easily view-able.

**Comment by aufdenkampe** [comment]
@horsburgh, @Maurier & @jcaraballo17,
As I just described in #89, I feel that it is important to keep our "code snippet", even though we can no longer completely copy/paste the entire thing into the latest release of [EnviroDIY/ModularSensors](https://github.com/EnviroDIY/ModularSensors) (since https://github.com/EnviroDIY/ModularSensors/pull/92). However, the present "code snippet" is still very useful for copy/paste each UUID into the appropriate place in the new code.

Eventually, we'll want to update the code snippet to reflect the new syntax expected by [EnviroDIY/ModularSensors](https://github.com/EnviroDIY/ModularSensors).

I think @SRGDamia1 suggested that we remove the "code snippet" only in the context that funding is presently tight, and that we might not prioritize updating the code snippet. We can decide that priority at a later date.

**Comment by SRGDamia1** [comment]
No, the current structure of ModularSensors makes it essentially impossible to generate a code snippet,  With some work, it may be possible to create a mostly-usable snippet, but until such time, providing anything is misleading so it should be removed.

We just another way of viewing GUID's and token's first. (#92, #163)

**Comment by SRGDamia1** [comment]
I'm sorry for the hassle and confusion on this one.  I was having problems due to the ordering (#89) and after a while realized that setting up two arrays where the ordering of each was crucial was just not a good way to go.  The UUID's really do belong to the variables, and shouldn't depend on some sort of pair-wise matching.  It's specially hard to get the order and matching right when the values in one of the arrays are long meaningless strings.

**Comment by horsburgh** [comment]
Still sort of confused here. If it's going to be virtually impossible to generate a code snippet that works consistently, I would prefer to get rid of it and not spend time here. If the only purpose to keep it is to get the UUIDs, we can focus on getting the UUIDs visible on the page (see #163, #92).

**Comment by SRGDamia1** [comment]
Sorry!

Get the UUID's visible, then as soon as they are, remove the code snippet.

Later, if we come up with a way that we can generate a good, usable chunk of code, we can add it back with explanation of how to use it.

**Comment by aufdenkampe** [comment]
I believe it's possible to refactor this code snippet, but clearly need to discuss with Sara. Let's not remove or change this feature until we have evaluated the options.

Sent from my iPhone

On Feb 9, 2018, at 4:14 PM, Sara Damiano <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry!

Get the UUID's visible, then as soon as they are, remove the code snippet.

Later, if we come up with a way that we can generate a good, usable chunk of code, we can add it back with explanation of how to use it.

-

**Comment by horsburgh** [comment]
This is done on the sandbox. Button for code snippet is gone. Adding tested label.

**Comment by aufdenkampe** [comment]
All, I really don't want the code snippet removed, as I mentioned above, in https://github.com/ODM2/ODM2DataSharingPortal/issues/139#issuecomment-364596356, which was the last comment on this issue.

I'll talk this week to @SRGDamia1 about why she believes it can't be refactored, but in the meanwhile, I believe that even the old Code Snippet is better than none, even if the UUIDs are visible in the UI (there are other reasons why this is good, such as having more than one instance of the same sensor at a site, at different depths for example).

**Comment by horsburgh** [comment]
@aufdenkampe and @SRGDamia1 - we need to know ASAP if we are removing this or not. We do not have any plans at USU to refactor or modify the code snippet to maintain order or do anything that we were not doing before, so I'm not sure how useful it is given that the GUIDs are now all shown on the page.

**Comment by SRGDamia1** [comment]
If the GUID's are shown, remove the code.  It's out of date anyway.

**Comment by SRGDamia1** [comment]
I don't see the point of leaving up an un-documented and out-of-date bit of code.  It's not even usable in the examples from the current release of the library it was meant to work with.  I think leaving it up is only going to confuse anyone who clicks on it.  If/when we refactor, then we can re-add it.

If Anthony's reason for leaving it up is to have a single quickly copy-able hunk of text with all the GUID's in it, then I think it would be better to label the button "View GUID csv" and then show a csv or something similar.

If the reason to leave it up is to get people to head over to the ModularSensors library to learn about how to send data, then I think that belongs in a help/documentation section.

**Comment by aufdenkampe** [comment]
@SRGDamia1 and I had a phone conversation, and we decided that there is a solution that solves both of our concerns and needs. The solution is:
* Keep the "code snippet" button, to allow users to copy/paste the entire UUID list into an external notes file for a deployment. We release this is somewhat redundant with #163, which we also love as a new feature.
* Change the button title from "View Code Snippet" to "View Token UUID List", to avoid the questions about regarding what code and where/how? We clearly are a way off from providing full documentation for this.
  * We should also change the title of the modal window from "Code Output" to "Token and UUID List".

This doesn't change the content of the code snippet at this time. Sara and I discussed a way forward on this for a future release that would mimic these lines of code in our [ModularSensors](https://github.com/EnviroDIY/ModularSensors) library examples: https://github.com/EnviroDIY/ModularSensors/blob/timing/examples/logging_to_EnviroDIY/logging_to_EnviroDIY.ino#L340-L404

**Comment by horsburgh** [comment]
@Maurier - Can we easily add the button back to the site details page with the same functionality as before but with a label of "View Token UUID List"? Sorry for the confusion. I've removed the ready for testing and tested labels until we finalize this.

**Comment by Maurier** [comment]
Yes, I'll add this back. No problem.

**Comment by aufdenkampe** [comment]
Thanks, that is much appreciated!

**Comment by horsburgh** [comment]
OK - final go. The button has been added back and is now called the "Token and UUID List". Adding the tested label back. Functional on the sandbox.
