### ISSUE TITLE
Add a link to GitHub

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#140]
Maybe a spiffy little box on the right or something.

**Comment by Maurier** [comment]
@SRGDamia1 Are we talking about a link in the footer to the repository? Or would it be somewhere else on the site?

**Comment by horsburgh** [comment]
@Maurier - I think the github link you added is fine for me. But, could you put it down by the Stroud logo so we can keep the footer more compact?

**Comment by SRGDamia1** [comment]
Should I be seeing this on http://envirodiysandbox.usu.edu/?  I'm not.

**Comment by Maurier** [comment]
No, this has not been added to this release.

**Comment by horsburgh** [comment]
@Maurier - since you've completed this, should it be included in Release 0.5.0?

**Comment by Maurier** [comment]
Yes, this could be added without problems.

**Comment by aufdenkampe** [comment]
I don't see it on Sandbox.

I agree with @horsburgh that if a feature or fix is completed and ready for testing, that it should by default go into the next release candidate on Sandbox, regardless of whether it was initial put in that Milestone.

**Comment by aufdenkampe** [comment]
I see it on Sandbox now. Thanks.
