### ISSUE TITLE
UI improvements to "Add Sensor" modal window

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#145]
Creating this issue to not loose suggested changes in UI and dropdown lists for the "Add Sensor" modal window, as described above in this comment: https://github.com/ODM2/ODM2WebSDL/issues/94#issuecomment-356397294

Specific suggestions include:
* Change the way each "Equipment model" is listed to use the manufacturer's OrganizationCode rather than the OrganizationName, as shown in Column E of the [sensors_for_websdl_v4](https://docs.google.com/spreadsheets/d/1x87AHmmCWmsgMVpbeEhw9iZm5iHPiUoJPuaUpzHsxW0/edit#gid=1117215732) Google Sheet. The present entries are too long (and infrequently used), and therefore hard to recognize. For example.
  * Change from "Decagon Devices" to "Decagon"
  * Change from "Yosemite Technologies Co." to "YosemiTech"
  * and many others. 
* Update ModelNames to the latest shown in column H of the [sensors_for_websdl_v4](https://docs.google.com/spreadsheets/d/1x87AHmmCWmsgMVpbeEhw9iZm5iHPiUoJPuaUpzHsxW0/edit#gid=1117215732) Google Sheet. I made some edits to those  for clarity. For example:
  * Change "Integrated Extremely Accurate I2C-Integrate RTC/TCZO/Crystal" to "DS3231 Real-Time Clock"
* Change list title (in UI Model Window) from "Equipment Model" to "Equipment Make-Model" (optional)

**Comment by SRGDamia1** [comment]
WRT listing of make/mode, also see #137

**Comment by horsburgh** [comment]
@aufdenkampe - is this still an issue on the sandbox with what will be 0.5 release?

**Comment by aufdenkampe** [comment]
Of the three suggestions above, the first one has been completed, and @SRGDamia1 and I can complete the second one with the new Admin panel:
- [X] Change the way each "Equipment model" is listed to use the manufacturer's OrganizationCode 
- [X] Update ModelNames to the latest
- [ ] Change list title (in UI Model Window) from "Equipment Model" to "Equipment Make-Model", also considering #137

The last of those can wait for a subsequent release, so no need to hold up Release 0.5

**Comment by horsburgh** [comment]
Closing this issue as we have now separated sensor manufacturer and sensor model in the user interface per other feature requests. So, there is not longer a need for a label "Equipment Make-Model", which is the last of the three items listed above.
