### ISSUE TITLE
Set schedule for Release 0.5

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#152]
@Maurier, @jcaraballo17 & @horsburgh,

I see that all the issues on the [Release 0.5 Milestone](https://github.com/ODM2/ODM2WebSDL/milestone/5) are labeled as ready for testing! That's exciting! Thanks for the hard work.

Does that mean that everything is deployed to the Sandbox?
If so, when should @SRGDamia1, I and others begin testing? What is your target date for moving Release 0.5 to production?

**Comment by horsburgh** [comment]
@aufdenkampe - I am just waiting for word from @jcaraballo17 that all of the 0.5.0 issues have been sandboxed to send you information and an invitation to test. How much time do you want to test?

I just spoke with him - all of the 0.5.0 issues are sandboxed, but we are having a little firewall issue between our sandbox web server and sandbox database server that we are sorting right at the moment.

FYI - we are not planning on an official 0.4.5 release. The 0.4.5 fixes have been made, except the one issue that required writing the data to the InfluxDB in real time. I believe everything else that was in 0.4.5 has already been fixed on production and the InfluxDB changes will be made with release 0.5.0, which is what we have just sandboxed.

**Comment by aufdenkampe** [comment]
Awesome! I would like to get testing done by Wednesday, if not sooner.
@SRGDamia1, do you have time to test the v0.5 Milestone issues on sandbox in the next few days? Could you also forward to Arscott and others at SWRC?

@horsburgh, we can also briefly discuss at tomorrow's EnviroDIY portal call.

**Comment by aufdenkampe** [comment]
It looks there are only three issues that still need to be fully tested before release: #77, #131 & #132. All of these require that either @SRGDamia1 or I set up a sensor station to report to Sandbox. 

@SRGDamia1, are you available to do that test? Let us know.
If not, I could get to it tomorrow sometime, but not today.

**Comment by aufdenkampe** [comment]
@jcaraballo17 & @Maurier, all issues have been tested. Let's release this!
Please let us know in advance when you plan on doing this, so that we know to expect possible down time on the system. Also let us know when it is completed, with an idea of how much down-time actually occurred. Thanks!

**Comment by jcaraballo17** [comment]
Released!
