### ISSUE TITLE
Change "begin date" to oldest value, not first value received

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#154]
The "historical" data is still loading, but in cases where it is loaded, the begin date is listed as the time a point was first received, not the oldest point in the series.

**Comment by SRGDamia1** [comment]
This is mostly a problem because TSA won't plot data earlier than the begin date, even if older data exists.

**Comment by horsburgh** [comment]
@SRGDamia1 - is this still a problem? I'm not sure which "begin date" you are referring to.

**Comment by SRGDamia1** [comment]
Yes it's still a problem.  The "begin date" is the date in TSA, which seems to take its values from the deployment date in the data portal.

![capture](https://user-images.githubusercontent.com/5374350/36567028-2d6b71f6-17f3-11e8-984e-b444215913d9.JPG)

![capture2](https://user-images.githubusercontent.com/5374350/36567045-404943c0-17f3-11e8-8069-c8c5819d7e50.JPG)

In the visualization within TSA, it is not possible to select or view points on the plot that are older than the begin date.  The data for this site (WCC019) actually goes back several years and TSA must know about the older observations because it has the right number of observations listed, but it's not possible to view them on the graphs.

**Comment by SRGDamia1** [comment]
*Hopefully* we won't have any more sites where we're back-loading "historical data" but I definitely don't want to promise that, especially once CSV upload becomes available to fill in holes at sites with bad/no cellular reception.

**Comment by horsburgh** [comment]
Ah - this is super helpful. I didn't realize this was a TSA issue. The TSA relies on a catalog of the time series to decide what is available for plotting, so this isn't a data availability issue, it's just an issue with the begin date being set incorrectly in that catalog.

**Comment by SRGDamia1** [comment]
Should I repost the issue over on the TSA repo?  I've posted a few others over there that I think are actually more important to fix than this one.

**Comment by aufdenkampe** [comment]
@jcaraballo17, Has this issue been fixed?
@SRGDamia1, did you create a separate issue in the TSA repo?

**Comment by aufdenkampe** [comment]
I think this issue has largely been resolved, with the replacement of TSA with TSV. 

Any remaining issues might be fully resolved when we fully migrate from using the `data loader` to putting all the data in ODM2 and finalize:
- #550 
- #511 

We can track any remaining bugs in those two issues.
