### ISSUE TITLE
Order tiles in my sites alphabetically

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#155]
Or perhaps by date/time last updated.. or by something.

**Comment by horsburgh** [comment]
@Maurier - I'm assuming this would be easy to do, so I'm going to add it to the restyling front end work associated with the 0.7 release.

**Comment by horsburgh** [comment]
This one appears to be working on the sandbox.

**Comment by SRGDamia1** [comment]
When I'm testing it looks like in the alphabetical sort, all capital letters are sorted before any lowercase letters (ie "WCC019" is coming before "desk_sensors" when ascending alphabetically).  The case should not matter in the alphabetical sort.
