### ISSUE TITLE
Set map view to satellite in register new site window

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#156]
Currently it's set to street/terrain, but satellite/street would be much more helpful which picking a location off of the map.

**Comment by horsburgh** [comment]
@jcaraballo17 and @Maurier - can we just add the google map control to this map to flip back and forth between the terrain map and the satellite map. Put it top right of the map.

**Comment by Maurier** [comment]
@horsburgh Yes, we'll do that.

**Comment by SRGDamia1** [comment]
Oh, that would be great.

**Comment by Maurier** [comment]
Should we also enable this control for other instances of the map?

**Comment by SRGDamia1** [comment]
If it's very easy to implement, it's nice to be able to switch any map between the views.  If it's difficult, then I don't know if it's needed elsewhere.

**Comment by Maurier** [comment]
It is just a setting, so it is easy to implement. Here is the list of controls: https://developers.google.com/maps/documentation/javascript/controls

Let me know if any other ones should be added too?

**Comment by horsburgh** [comment]
I think it's useful to be able to switch the map view. Let's not let this hold us up for the 0.5 release, but should be a quick implementation for the next one.

**Comment by horsburgh** [comment]
This appears to be done on the sandbox. Adding the tested label.

**Comment by aufdenkampe** [comment]
I really like the ability to switch between the two map views. Thanks for creating and implementing this issue.

Let's not have Satellite the default for all the map views, but only the Register Site map that allows you to click on a location.

For the My Sites and Browse Sites maps, lets have the terrain map as the default (not satellite).

**Comment by horsburgh** [comment]
@Maurier - if this is easy enough to do with a simple switch in the code, then go ahead and do it for the next release. Otherwise, this needs to be a separate issue.

**Comment by Maurier** [comment]
@aufdenkampe, 

Should we also use the Sattelite map for the Site Details page?

**Comment by aufdenkampe** [comment]
Yes, that sounds good. Satellite as default for Site Details and also Site Registration/Editing.

**Comment by horsburgh** [comment]
This is implemented on the sandbox. Tested and functional.
