### ISSUE TITLE
Ensure no more than one user exists per email address

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#157]
Add verification when creating users that a user does not already exist with specified email.  (Ref #71)

**Comment by horsburgh** [comment]
I tried to create a new user account with an email address that had already been used. The system reports a user with that email address already exists. I also tried adding a new user with a username that had been used before and the system reports that a user with that username already exists. 

This appears to be working correctly on the sandbox. Adding the Tested label.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
