### ISSUE TITLE
Battery voltage empty in status page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#160]
It's empty for all of my stations right now.

**Comment by jcaraballo17** [comment]
@horsburgh My sites didn't have any data for that variable either, so I ended up following some sites that did have that data and it shows up correctly.

**Comment by SRGDamia1** [comment]
It's showing for me on the sandbox.

**Comment by horsburgh** [comment]
OK. Marking this one as tested.
