### ISSUE TITLE
Add a way to view the GUID and registration token for a sampling feature

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#163]
Parallel to #92.  Display the values in the "details" box next to the map.  Values should be viewable if and only if logged in a an administrator or the owner of a given site.

**Comment by horsburgh** [comment]
@Maurier - this one is assigned to you, but I don't see any of this on the sandbox and I don't see an "In-progress" label. We need to get this one finished with #139. I'm not adding any labels because I don't see any evidence of this on the sandbox.

**Comment by horsburgh** [comment]
@Maurier - I see the registration token GUID for the site, but I don't see the SamplingFeature token GUID.  That needs to get added to the site details page. I would just put it right under the registration token for now. Also - GUIDs of all types (registration, samplingfeature, and variable) should only be visible to the site owner and admins of the system.

**Comment by Maurier** [comment]
Understood. I will be adding these this morning.

**Comment by aufdenkampe** [comment]
The labels on these are "GUID", but in ODM2 and in our modular code, we call them "UUID"s.
Can we change that. Also applies to #92.

**Comment by horsburgh** [comment]
Both the registration token and the SamplingFeatureUUID are now shown in the site details page. Tested and functional on the sandbox. Adding tested label.
