### ISSUE TITLE
Sharing to HydroShare: Add ability to link data sharing portal account with a HydroShare account

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#164]
Add capability on the user's profile page to link their profile in the data sharing portal to an existing HydroShare account. Assumes that they have already created a HydroShare account.

Also - add capability to disconnect the accounts. This should stop any automated data sharing that is scheduled for copying data to HydroShare from the data sharing portal.

**Comment by aufdenkampe** [comment]
Got this error when I disconnected.

```

Request Method: | POST
-- | --
http://envirodiysandbox.usu.edu/account/
1.11.7
IntegrityError
update or delete on table "dataloaderinterface_odm2user" violates foreign key constraint "dataloaderinte_User_48480eab_fk_dataloaderinterface_odm2user_id" on table "dataloaderinterface_deviceregistration" DETAIL:  Key (id)=(3) is still referenced from table "dataloaderinterface_deviceregistration".
/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py in _commit, line 236
/usr/bin/python
2.7.12
['/opt/websdlenvironment/ODM2WebSDL/src',  '/usr/local/bin',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Tue, 20 Mar 2018 10:15:45 -0500
```

**Comment by aufdenkampe** [comment]
Did previous with my LimnoTech account.
Therefore, I can't test my personal account, aufdenkampe.

I got this error when trying:
```
Request Method: | GET
-- | --
http://envirodiysandbox.usu.edu/hydroshare/oauth/?code=nAkyAwL3nxnFE1Upq6TeDHSS5ZHrm0
1.11.7
IntegrityError
duplicate key value violates unique constraint "dataloaderinterface_odm2user_hs_account_id_key" DETAIL:  Key (hs_account_id)=(4) already exists.
/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py in execute_sql, line 894
/usr/bin/python
2.7.12
['/opt/websdlenvironment/ODM2WebSDL/src',  '/usr/local/bin',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Tue, 20 Mar 2018 10:20:29 -0500
```

**Comment by aufdenkampe** [comment]
After "Create Resource", I click the blue button "Start Sharing", and the window stays as is, with no indication that anything has happened.
![screen shot 2018-03-20 at 10 28 56 am](https://user-images.githubusercontent.com/5166036/37664688-cddc8702-2c29-11e8-8e41-2a262e55b954.png)

However, I when I go to HydroShare, I can see that a resources was created. https://www.hydroshare.org/resource/9915903c092540f5b63688ac913e47da/

Therefore, the "Create Resource" button should somehow indicate success and then go away.

**Comment by aufdenkampe** [comment]
I just noticed that the Content directory on HydroShare is empty. It should contain some CSV files, right?

cc @jcaraballo17 & @Maurier . Please read all previous comments in this issue.

**Comment by horsburgh** [comment]
@aufdenkampe - this issue is only about linking accounts, so can you move your comments about the content directory and the create resource to separate issues?

**Comment by horsburgh** [comment]
@darksinge - I can confirm, we are currently getting an error when trying to disconnect a HydroShare account on the sandbox.

**Comment by darksinge** [comment]
> Therefore, the "Create Resource" button should somehow indicate success and then go away.

@aufdenkampe Thanks for the catch! There was a server side issue that occurred after the resource was created in HydroShare. I updated the form to display an error message so it will not look like nothing happens.

If no errors occur, the *create-resource* form is dismissed from the view.

**Comment by horsburgh** [comment]
Tested the following on the sandbox:

* Connected to HydroShare account with no problems
* Disconnected with no problems.
* Reconnected with no problems.
* Shared a site to HydroShare no problem, disconnected HydroShare account, and HydroShare sharing settings were gone from the site details page. This looks good.
* HydroShare sharing is only available on sites after you have connected a HydroShare account.

This all seems to be working as of today. Adding "tested" label.
