### ISSUE TITLE
Sharing to HydroShare: Add ability to copy time series data from registered EnviroDIY site to HydroShare

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#165]
Once a data sharing portal user has linked their profile with a HydroShare account, add the ability to share time series data from registered EnviroDIY sites to a new HydroShare resource.  Use the following guidelines:

* The HydroShare resource should be created automatically with metadata initially set based on metadata from the EnviroDIY site metadata
* The HydroShare Resource Type should be Composite
* For now, data copied to HydroShare should be the same CSV files available for download from the sparkline plots
* The resource created in HydroShare should initially be private
* The data sharing portal user should be the author and owner of the resource
* Variable names should get added to the HydroShare resource as subject keywords
* Spatial coverage should be the lat/long point location of the site
* The user should be able to manually trigger an update to HydroShare at any time with one click

**Comment by aufdenkampe** [comment]
Copying from #164 

I just noticed that the Content directory on HydroShare is empty. It should contain some CSV files, right?

cc @jcaraballo17 & @Maurier

**Comment by darksinge** [comment]
> See https://www.hydroshare.org/resource/9915903c092540f5b63688ac913e47da/

@aufdenkampe Will you make that resource public so we can look at it? And yes, it should contain at least one CSV file.

Also, will you put a link in here to the site registration that is associated with the resource?

**Comment by horsburgh** [comment]
Tested this on the sandbox with the following procedure:

* Created a new site and added 5 sensors/variables
* Loaded some historical data for all 5 variables using a Python script via the REST API
* Turned on sharing with HydroShare and did a Manual share
* I clicked the "Update Now" button to update the data in HydroShare

Based on this, the following are complete and working correctly:

* [X] The HydroShare resource should be created automatically with metadata initially set based on metadata from the EnviroDIY site metadata
* [X] The HydroShare Resource Type should be Composite
* [X] For now, data copied to HydroShare should be the same CSV files available for download from the sparkline plots
* [X] The resource created in HydroShare should initially be private
* [X] The data sharing portal user should be the author and owner of the resource
* [X] Spatial coverage should be the lat/long point location of the site
* [X] The user should be able to manually trigger an update to HydroShare at any time with one click

One little wiggle, this is also supposed to happen:

* [ ] Variable names should get added to the HydroShare resource as subject keywords

The variable names do get added, but it is also adding some terms that are not associated with this site for some reason. 

The site is: http://envirodiysandbox.usu.edu/sites/USU-LBR-Mendon/
The variables that should not get added as keywords (but are) include: Distance, Battery Voltage, Free SRAM, and Relative Humidity. 

@darksinge - can you look at the keyword creation part of this? Otherwise, I think this one tests OK.

**Comment by horsburgh** [comment]
@darksinge - there's still something weird going on. I just shared this site to HydroShare:

http://envirodiysandbox.usu.edu/sites/USU-Logan-Temp/

It only has one variable - temperature. Keywords added to HydroShare include pH, Turbidity, Electrical conductivity, Oxygen, dissolved, and Temperature. See:

https://www.hydroshare.org/resource/8647b1d1a499432c86095d83d6bc0abd/ 

By coincidence (or perhaps not) this is the correct list of keywords for this site:

http://envirodiysandbox.usu.edu/sites/USU-LBR-Mendon/

**Comment by darksinge** [comment]
This turned out to be an issue with the sandbox database. Some of the older sites had strange database issues from previous testing. Independent of database inconsistencies, I can confirm the keyword creation behaves as expected. @jcaraballo17 and I were able to fix the database issues on the sites you mentioned - they should create the correct keywords now.

**Comment by horsburgh** [comment]
Given that we tracked this down, I'm going to tag this one as tested.
