### ISSUE TITLE
Sharing to HydroShare: Add ability to manually schedule data uploads to HydroShare

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#166]
Once a user turns on data sharing from the data sharing portal to HydroShare, the user should be able to schedule an automated process to periodically update the data in HydroShare from the data that is held in the data sharing portal. Update frequencies should be daily, weekly, or monthly and should run with no intervention from the user once set.

**Comment by horsburgh** [comment]
Did some initial testing of this one the sandbox. I set up scheduled update for a site that I created that had historical data (no data are streaming for this site). The settings dialog allows me to change the schedule from daily, to weekly, to monthly, and the next scheduled update dates are correct. I'll leave it running with a daily update schedule and check on it tomorrow to make sure it ran.

@darksinge - can you confirm what happens if a scheduled update to HydroShare is set, but there are no new data at the site? Does it just replace the files in HydroShare anyway?

**Comment by darksinge** [comment]
@horsburgh 
> Does it just replace the files in HydroShare anyway?

Yes. Currently the functionality doesn't check if there is new data, it simply uploads whatever data is there.

**Comment by horsburgh** [comment]
@darksinge - thanks for the confirmation. I think this is the desired functionality for the first version. If the scheduled update runs today I will call this one tested successfully.

**Comment by horsburgh** [comment]
@darksinge - the scheduled update ran as expected today and the next update date was set for tomorrow. I'm going to mark this one as tested as it seems to be working correctly.
