### ISSUE TITLE
Sharing to HydroShare: Add ability to stop sharing to HydroShare and delete HydroShare resource

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#167]
For a site where the user has turned on sharing of data to HydroShare, the user should be able to do the following:

* Turn all sharing on and off (this should be a check box in the settings for sharing) - effectively pause sharing
* Turn sharing on or off for a particular data type (e.g., Time Series, Leaf Pack Experiments, etc.)
* Stop sharing and delete the HydroShare resource that was created by starting the sharing process - with a big fat pop up warning that all data will be removed from HydroShare and the associated resource will be deleted.

**Comment by darksinge** [comment]
> Turn sharing on or off for a particular data type (e.g., Time Series, Leaf Pack Experiments, etc.)

Since EnviroDIY only support the _Time Series_ data type, this option should be unavailable until we add more data types to the website.

**Comment by horsburgh** [comment]
Agreed - I like the ease of having check boxes for each data type. But, we shouldn't present options that don't exist yet.

**Comment by horsburgh** [comment]
Tested this one on the sandbox. Here are my notes:

* [ ] Turn all sharing on and off (this should be a check box in the settings for sharing) - effectively pause sharing

We implemented pausing of sharing as a check box on the settings dialog. I checked the box and user interface says that the sharing has been paused. @darksinge - if the sharing is paused, we should probably remove the next scheduled update because it won't happen given that sharing has been paused. Can you modify this please. When sharing is paused, remove the label for the next scheduled update. When sharing is unpaused again, the system should do an update if the time since the last update was longer than the scheduled period. Then, display a new time for the next scheduled update.
 
* [X] Stop sharing and delete the HydroShare resource that was created by starting the sharing process - with a big fat pop up warning that all data will be removed from HydroShare and the associated resource will be deleted.

Tried this one by clicking the stop sharing button and then choosing not to delete the HydroShare resource. I started sharing again and it created a new resource in HydroShare. When I stopped sharing again, but chose to delete the resource this time it removed the resource from HydroShare. This all seems to be working correctly.

NOTE: We only have time series at this point, so turning sharing on or off for a particular data type (e.g., Time Series, Leaf Pack Experiments, etc.) will have to come after we have added additional data types.

As soon as @darksinge makes the changes for pausing sharing we can call this one tested.

**Comment by darksinge** [comment]
Updated the sandbox so it does not display the "Next update scheduled for..." label.

**Comment by horsburgh** [comment]
@darksinge - now when I set up a daily sharing schedule, the times don't seem to match up:

![image](https://user-images.githubusercontent.com/3485902/37920288-b4427c20-30e3-11e8-8e9b-fdc8819ab548.png)

Why is the next update time at 5 AM instead of 1 day from when I scheduled the update?

**Comment by horsburgh** [comment]
@darksinge - I can verify that the when you choose to pause the data sharing, the next scheduled update is no longer displayed. However, now the last update date is not being shown. When sharing is paused, I should still be able to see the Last updated date and time.

**Comment by darksinge** [comment]
This is ready for re-testing.

**Comment by horsburgh** [comment]
Verified on the sandbox. Marking this one as tested.
