### ISSUE TITLE
Sharing to HydroShare: Handle the case where a user publishes the resource in HydroShare

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#169]
When a user formally publishes a resource in HydroShare it becomes immutable and so any further updates from the data sharing portal will be impossible. So, the data sharing portal should recover gracefully if it tries to do a data update to HydroShare, but can't because the resource is formally published. The user should be notified that the HydroShare resource cannot be updated because it has been published. Then, the user should be asked if they want to turn off data sharing or share to a different resource.

**Comment by horsburgh** [comment]
@darksinge - can you set up a test similar to what you did on your sandbox and make me the owner of a site registration that is "sharing" data with a published HydroShare resource just so I can verify this on envirodiysandbox.usu.edu? If the published resource is detected correctly and the message is displayed correctly, we'll call this one tested.

**Comment by darksinge** [comment]
You now have a new site that is "sharing" data with a published resource.
http://envirodiysandbox.usu.edu/sites/PublishedTestSite/

**Comment by horsburgh** [comment]
Tested on the sandbox. Craig associated a published HydroShare resource with a site for which sharing to HydroShare had been set up. The fact that the resource has been published is detected correctly, and the following message is displayed.

![image](https://user-images.githubusercontent.com/3485902/37848466-de990800-2e99-11e8-9b11-2380c0098552.png)

However, when I click the "Disconnect Resource" button, I get a HTTP ERROR 405. @darksinge - can you look into why the disconnect resource is not working correctly?

**Comment by horsburgh** [comment]
@darksinge - just resolved this one and deployed to sandbox. Another quick check and everything looks good. Marking this one as tested.
