### ISSUE TITLE
Restyle Site: Change domain from data.envirodiy.org to data.wikiwatershed.org

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#170]
Need to get the subdomain data.wikiwatershed.org set up and point it at the production server at USU. The IP address for the production server is in the Google Doc with our notes from the teleconferences.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, can you set up the subdomain for data.wikiwatershed.org, and work with @jcaraballo17 when it's time to do all the redirects?

**Comment by HeatherBrooks** [comment]
I've pointed data.wikiwatershed.org to 129.123.41.212. Now someone at USU needs to do the bit of magic on their end.

**Comment by aufdenkampe** [comment]
We're not quite ready for any big changes yet. That will come when we're ready to go public with Release 0.7. Right now, we're about to Release 0.5. Let's talk about timing today.

**Comment by horsburgh** [comment]
@HeatherBrooks - thanks for doing this. For now, I think we should just point this as the site that is currently data.envirodiy.org.

@jcaraballo17  - can you set this up? Eventually, this domain (data.wikiwatershed.org) will be the primary domain for the data sharing portal, but I think we want both to work for now.

**Comment by horsburgh** [comment]
The data.wikiwatershed.org domain is currently active and points at the site. We will continue to support both data.envirodiy.org and data.wikiwatershed.org, but I'm going to close this because it is working now.
