### ISSUE TITLE
Restyle Site: Restyle Home Page

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#171]
Need to restyle the home page to be the combined page for data.wikiwatershed.org. It needs to have elements of both EnviroDIY and Leaf Pack Network. Ignore my color schemes and use those from the WikiWatershed (https://wikiwatershed.org/), EnviroDIY (https://envirodiy.org/), and Leaf Pack Network (https://leafpacknetwork.org/) Sites.

This will replace the home page of http://data.envirodiy.org

![data](https://user-images.githubusercontent.com/3485902/36512860-af76bb6c-1729-11e8-9251-f857b16b8244.png)

**Comment by horsburgh** [comment]
@aufdenkampe - if you could give us input on the wording of how we should feature the leaf pack network workflow on this page it would be great.

**Comment by horsburgh** [comment]
@Maurier - there's still still a couple of things to do on this page:
* [ ] Add a "Sign Up" button to the top image banner just below the text "Data Sharing for the Citizen Science Community"
* [ ] Add the panel at the bottom just above the header with the "Ready to join? Create an account for free." text and the "Sign Up" button as in the mockup above.
* [ ] Add the EnviroDIY and Leaf Pack network logos near the top of the page so you can see both of them when the page initially loads, regardless of the browser window size. This is so people recognize that this is a site for both EnviroDIY and Leaf Pack Network.

I'm adding the "ready for testing" label because it's on the sandbox, but these changes need to be made before this page is finished.

**Comment by aufdenkampe** [comment]
The WikiWatershed Outreach team met today, and we had a lengthy discussion of branding elements across the WikiWatershed / Model My Watershed / Monitor My Watershed system, which are primarily relevant to https://github.com/WikiWatershed/model-my-watershed/issues/2741 but also here.

Part of this is a likely update of our logos. See our [WikiWatershed Toolkit Branding Ideas](https://docs.google.com/document/d/14QO72Oj5Tb_ATWHc_3cJuJcih0x8y9I3VHXD5BQWKsU/edit#) Google Doc for some of the things we're considering. No decisions on logos have been finalized.

See today's notes in our [2017-2019_Wikiwatershed_OutreachNotes-Cumulative](https://docs.google.com/document/d/14ZOGs80rQehmbMMJsx2cIpc29UEox7nNwFPn2xc0tzk/edit#bookmark=kix.1pozzdyrca5t) Google Doc.

We're still working on final decisions. I'll summarize by our next Tuesday meeting, and provide clear recommendations/instructions.

**Comment by horsburgh** [comment]
This is complete on the sandbox. Adding the tested label.

@aufdenkampe - I think we should push forward with this release as is and do any rebranding based on your discussions later.

**Comment by aufdenkampe** [comment]
I think that it does make sense to push this forward sooner than later, and replace logos, etc. in the next release. I would like to do one more review of the sandbox, but unfortunately the sandbox isn't working this morning. Please let me know when it is again ready for testing.

**Comment by horsburgh** [comment]
@aufdenkampe - I just tried the sandbox and it is working for me.

http://envirodiysandbox.usu.edu/

We need content very soon if we are going to switch things for this release. Otherwise, we can push it to the next release.

**Comment by aufdenkampe** [comment]
Sandbox started working for me again, shortly after I sent this.

Yes, @SRGDamia1 and I will try to get feedback to you soon. Can we target COB tomorrow, for a release on Friday?

**Comment by horsburgh** [comment]
@aufdenkampe - I'm still in Vienna through Saturday, so I would rather do a release early next week when I'm around if something goes wrong.

**Comment by SRGDamia1** [comment]
#219 is tied to this.

**Comment by aufdenkampe** [comment]
Just talked to Jeff, we need to add a "Coming Soon"  or something similar in the "Leaf Pack Network" section of the home page.

**Comment by horsburgh** [comment]
This is done on production.
