### ISSUE TITLE
Restyle Site: Restyle Register Site Page

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#175]
This page will have to be both restyled and the functionality will change. However, this issue is for restyling only to use the WikiWatershed styling to make it consistent with other page. There will be a separate issue for functionality changes.

![register_site](https://user-images.githubusercontent.com/3485902/36513293-39e7efc6-172c-11e8-9969-a7f78cfa4bf7.png)

**Comment by darksinge** [comment]
Closing since the only restyle issues on this page are in the header and footer, which are addressed in #178 and #171 .
