### ISSUE TITLE
Restyle Site: Restyle Site Details and Edit Site Details Pages

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#176]
These pages need to take on the WikiWatershed styling. These pages will also have modified functionality that will be specified in another issue.

![site_details](https://user-images.githubusercontent.com/3485902/36513713-2994fe82-172e-11e8-8a35-902db357c507.png)

**Comment by horsburgh** [comment]
This appears to be ready on the sandbox. Added "tested" label.

**Comment by SRGDamia1** [comment]
I'm not seeing anything related to macros right now when I'm looking at my sites.  Should I be?

**Comment by horsburgh** [comment]
Leaf pack network functionality is the next release. So, no, you shouldn't see anything yet.
