### ISSUE TITLE
Restyle Site: Review existing site footer and suggest changes

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#178]
Since the new site will be an amalgamation of the existing EnviroDIY website, we need input on what should be in the footer of the website. Please review the existing footer and suggest any changes that need to be made.

![image](https://user-images.githubusercontent.com/3485902/36513846-e41c717c-172e-11e8-825e-a146ba014360.png)

**Comment by aufdenkampe** [comment]
@Maurier, nice here are a few suggestions
* Put "Find us on GitHub" 
* Add "LimnoTech" logo next to USU logo under "Developed by"

02_whitelimno_for_dk_background.png (note that the word Limno is in white and can't be seen on screen with a white background)
![02_whitelimno_for_dk_background](https://user-images.githubusercontent.com/5166036/37666216-040a3844-2c2d-11e8-9a69-bd8d3ca7379f.png)
or
Logo_square.png
![logo_square](https://user-images.githubusercontent.com/5166036/37666282-357302bc-2c2d-11e8-9fdd-366caf9aa518.png)

Or square logo for dark background (I don't have that, but could get it to you).

**Comment by horsburgh** [comment]
@aufdenkampe - footer needs to be reviewed. I added the "ready for testing" label. Can you review and add the "tested" label once you think the footer is complete?

**Comment by SRGDamia1** [comment]
I do not like the way the "Find us on GitHub" sits up above everything else.  Can it be moved down in line with the other "developed by" images?

**Comment by Maurier** [comment]
@SRGDamia1 How about this:

![image](https://user-images.githubusercontent.com/2448568/38567983-b73ef72e-3ca4-11e8-9e6f-333041d67abf.png)

**Comment by SRGDamia1** [comment]
I like that.

**Comment by aufdenkampe** [comment]
Agreed. Much better.

**Comment by horsburgh** [comment]
@aufdenkampe and @SRGDamia1 - given that you both have commented on this issue, I'm going to add the tested label. We're getting pretty close to finishing up this release, so if you have additional comments, let us know as soon as you can.

**Comment by SRGDamia1** [comment]
Do we want to add the logos for WPF/NSF in the "With support from" block to match the CC/SWRC/USU/Limno logos in the other blocks?

I'm content either way. @HeatherBrooks?

**Comment by HeatherBrooks** [comment]
It might end up pretty crowded. I wouldn't add the additional logos unless someone else on the team feels strongly that we should.

**Comment by aufdenkampe** [comment]
I think the footer is looking good. I like @SRGDamia1's idea to have WPF & NSF logos under the "With Support From" block, given the current length of the footer and if it doesn't make the footer longer (i.e. I think there is room).

That said, I don't think this issue needs to hold up this release.

**Comment by horsburgh** [comment]
We'll move forward with what we've got. If someone wants to send additional logos, we can consider adding them, but I'm of the persuasion that the footer is already too big.
