### ISSUE TITLE
Update the variable names table

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#189]
It's behind http://vocabulary.odm2.org/variablename/

**Comment by SRGDamia1** [comment]
It would be good to have a mechanism to keep all of the vocabularies up to date.

**Comment by horsburgh** [comment]
@jcaraballo17 updated the controlled vocabularies as part of the 0.8 release. This includes the VariableName table. I'm going to close this one.
