### ISSUE TITLE
Separate unit-type and unit into two dropdowns

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#191]
The unit should only be select-able based on the unit type.

**Comment by aufdenkampe** [comment]
Let's think about how to best do this. Sometimes the term for the relevant Unit type is a bit obscure, and in my recent work with @roelofversteeg, I have found that first sorting my unit type is actually quite hard to do, even for me with all my previous work on Units. I found that it is much easier to search by unit name, especially if there is free-text filtering in the dropdown.

**Comment by horsburgh** [comment]
@aufdenkampe - @jcaraballo17 and @Maurier need some clarity. @SRGDamia1 suggests that the unit should only be selectable by unit type, but Anthony, your last comment suggests that we don't want to do this. It would be great if you and Sara can get together and decide what you want here. Juan and Mauriel can do whatever, but we need to tell them how this should work.

**Comment by horsburgh** [comment]
If it's just in the Admin panel, it should be pretty straightforward.

**Comment by jcaraballo17** [comment]
Adding a new dropdown that is not directly a field of the model and then filtering through it is a little bit complicated. 
I added the free-text searching to each dropdown in the admin instead. It's a lot simpler and easier to just filter the units selection through that.

**Comment by SRGDamia1** [comment]
The search seems to be working on staging.  I'd still prefer the split, but I guess that problem is an ODM2 structural one.
