### ISSUE TITLE
Expand list of Sampled Medium to include "sediment"

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#202]
We presently allow for 4 types of Sampled Medium:
- Air
- Soil
- Not applicable
- Liquid Aqueous
- Equipment

I would like to add the following additional options, based on the complete list from http://vocabulary.odm2.org/medium/:
- other
- sediment

I don't think there are any other terms we need to include in the near future.

**Comment by aufdenkampe** [comment]
If the following is trivial to do, it would also be nice to add display "Liquid Aqueous" as "Liquid Aqueous (water)", given that most of our users are looking at water, and many are quite confused by Liquid Aqueous.

**Comment by horsburgh** [comment]
@aufdenkampe - we can change this to whatever you guys want. If we modify the term here, it will be inconsistent with the ODM2 vocabulary, but that's probably the right thing to do for this audience. We discussed this earlier with @SRGDamia1 and I thought there was a reason why we decided to keep it as is, but I can't remember.

**Comment by aufdenkampe** [comment]
I don't really want to deviate from the ODM2 vocabulary under the hood, because of the web services we're providing and our desire to showcase our use of ODM2 and it's interoperability features. I was just hoping we could display it differently, but that may not be trivial to do.

**Comment by horsburgh** [comment]
@jcaraballo17 - I'm assuming this is an easy fix. Can you take care of this one for this release?

**Comment by jcaraballo17** [comment]
Yes, I'll make sure to add these for the next release.

**Comment by aufdenkampe** [comment]
Thanks!

So we'll have 2 new media (sediment & other).

And also display "Liquid Aqueous (water)" or "Water - Liquid Aqueous" (I like the second), but still keep the term as "Liquid Aqueous" in the database, so that our web services are still compliant with http://vocabulary.odm2.org/medium/ for interoperability.

**Comment by jcaraballo17** [comment]
@aufdenkampe we could also go with something more simple like just `Water`. This is really easy to change, so we can change our minds about it later without it being a setback.

**Comment by aufdenkampe** [comment]
I like "Water - Liquid Aqueous", so that the EnviroDIY user gets familiar with the actual term we use in for the web services.

**Comment by jcaraballo17** [comment]
Sounds good!

**Comment by horsburgh** [comment]
This is done on the sandbox, so I'm adding the tested label. One minor point - because of the way Juan added "Water" to the term "Liquid aqueous", it doesn't sort quite right in the list. But, the list is short and so I don't think this is an issue.
