### ISSUE TITLE
Help: Create "Data Services" Page

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#203]
On a prior teleconference we discussed developing a "Data Services" page that describes the different mechanisms for accessing the data available via the data.wikiwatershed.org website. We discussed adding text about the following:
* HydroShare (www.hydroshare.org) 
* CUAHSI Water Data Services (data.cuahsi.org)
* WikiWatershed

This page would describe each of these systems, what is available there, and provide a link for users to open the site i a new browser window.

**Comment by horsburgh** [comment]
Resolution - content will be authored at wikiwatershed.org/help and then we will add a help link to the top of the Data Sharing Portal with a "Help" link that points at that help system. None of the help content will be in the Data Sharing Portal site.

**Comment by jcaraballo17** [comment]
This is something that could be done if we have the content for that page.

**Comment by jcaraballo17** [comment]
Closing in favor of issue #216.
