### ISSUE TITLE
HydroShare Interoperability: Link to existing HydroShare resource

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#206]
If data sharing for a site is stopped, but the resource is not deleted from HydroShare, and then sharing is restarted, provide an option to reconnect to the previous resource instead of creating a new one. Starting sharing again would overwrite the content of the existing resource.

**Comment by darksinge** [comment]
This is ready for initial testing. I understand we may want to add additional help text or something, but the initial functionality is in place on the sandbox.

Steps to test:
1. Create a resource on a site by clicking "Turn On Sharing" and submitting the form.
2. Turn off sharing (but do not select option to delete the resource on hydroshare.org)
3. Select "Turn On Sharing". There should be a drop down list with an option to select the resource you created in step 1.

**Comment by horsburgh** [comment]
Tested by disconnecting a site that was sharing to HydroShare. Then, clicked "Turn on Sharing". Chose the resource that was used before from the drop down list. Started a manual share, which seems to have worked correctly.

This appears to be working correctly. Adding tested label.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
