### ISSUE TITLE
Restyle Site:  Styling issue on links to companion sites in main landing page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#209]
![image](https://user-images.githubusercontent.com/5374350/38566810-a5b3b446-3cb2-11e8-91c6-585675edc3dd.png)

The last line of the description of the companion site overlapps the "view site" link

**Comment by Maurier** [comment]
Found the problem and fixed. Will show up once we update the deployment.

**Comment by SRGDamia1** [comment]
Thanks!

**Comment by horsburgh** [comment]
Tested in Chrome and Firefox. Looks good on sandbox. Adding tested label.
