### ISSUE TITLE
Restyle Site:  Scroll bar is non-functional in filter pane when browsing sites on Firefox

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#210]
I can see an empty scroll bar, but there isn't a "bar" in it to move up and down.

Issue on Firefox 59.0.2 (64-bit), Chrome seems ok.

**Comment by Maurier** [comment]
Fixed. Will show up on the next update.

**Comment by horsburgh** [comment]
I just tested in both Chrome and Firefox. Looks good on the sandbox. Adding the tested label.
