### ISSUE TITLE
Help: Create a help section

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#216]
Have a "Help" drop-down in the upper tool bar with pages for getting started, post request syntax, sensor links/documentation etc.

![image](https://user-images.githubusercontent.com/5374350/38627208-6b3a2d2a-3d7c-11e8-8c53-7be7e0344e34.png)

**Comment by horsburgh** [comment]
Resolution - content will be authored at wikiwatershed.org/help and then we will add a help link to the top of the Data Sharing Portal with a "Help" link that points at that help system. None of the help content will be in the Data Sharing Portal site.

**Comment by jcaraballo17** [comment]
@horsburgh @SRGDamia1 What are we showing in in this `Help` dropdown menu?

**Comment by horsburgh** [comment]
@jcaraballo17 - Based on our resolution from June (see my comment above), we decided that help content would be at http://wikiwatershed.org/help and there would just be a link on the top bar that takes the user to a new browser tab that opens that page.

@SRGDamia1 and @aufdenkampe - @jcaraballo17 can obviously add this link to the Data Sharing Portal when the help content exists. How should we go about authoring said content?

**Comment by SRGDamia1** [comment]
Erm..  there's a lot of content about using the modular sensors library I've created on the wiki of that repo...

**Comment by aufdenkampe** [comment]
It seems that there are multiple help topics that can be covered here:
* Getting Started
  * potentially pointing to an article posted at https://wikiwatershed.org/help/ and/or https://www.envirodiy.org
  * @heatherbrooks would need to set up such a page
* REST POST request syntax
  * described in #254 
  * potentially pointing to https://github.com/ODM2/ODM2DataSharingPortal/blob/master/doc/example_rest_requests.md
* How to Send Sensor Data from an Arduino datalogger
  * potentially pointing to https://github.com/EnviroDIY/ModularSensors/wiki

Are there other topics?
Do we list this "menu" in the app, or put it all at https://wikiwatershed.org/help/ ?

**Comment by horsburgh** [comment]
When we discussed this on a prior teleconference, we decided to put the documentation at https://wikiwatershed.org/help/ because that would give you all the flexibility to create, edit, modify, and maintain the documentation without any changes to the code of the Data Sharing Portal. 

From our perspective, it doesn't matter where it goes, we just need to know where to point the link. 

Some other topics you might want to add to the list:
* Getting started with EnviroDIY Sensor Data
* Getting started with Leaf Pack Data (just to separate these two getting started topics)
* Sharing data to HydroShare
* Accessing and downloading data
* Viewing your data online
* Manually uploading data from a file

**Comment by aufdenkampe** [comment]
@horsburgh, thanks for those additional topic areas!
I agree that putting it all at a specific page under https://wikiwatershed.org/help/ will provide the most flexibility. However, that specific page doesn't exist yet. We need to make it, or at least reserve the URL.

**Comment by HeatherBrooks** [comment]
We have an established page at https://wikiwatershed.org/help/ but perhaps it is time to reorganize the tabbed content. It might make sense to separate the material by "tool," e.g. Model My Watershed, Monitor My Watershed, etc.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, I agree that it seems time to reorganize the  https://wikiwatershed.org/help/ section by tool. Are you able to do this anytime soon? Let @darscott and I know what kind of input you might need.

@Maurier and @jcaraballo17, for the moment, just point to https://wikiwatershed.org/help/. We'll send you an updated URL once we have it.

**Comment by SRGDamia1** [comment]
Looks good to me.
