### ISSUE TITLE
Move "logout" to submenu of "Logged in As"

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#217]
Also make "edit profile" another submenu in the same spot.  This matches what is done in app.wikiwatershed.org

![image](https://user-images.githubusercontent.com/5374350/38627450-fae05328-3d7c-11e8-8251-2f16677bd0b4.png)

![image](https://user-images.githubusercontent.com/5374350/38627590-569c7930-3d7d-11e8-8d27-073684063b6c.png)

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
