### ISSUE TITLE
Hyperlink color doesn't provide enough contrast

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#218]
Hyperlink text color doesn't provide enough contrast against the white background. See [https://webaim.org/resources/contrastchecker/](url). Recommend changing to the darkest of the three WikiWatershed brand colors, #336666. 
![data-portal-link-contrast](https://user-images.githubusercontent.com/9368629/38636033-199a68cc-3d95-11e8-811e-7bf8a3615fa2.jpg)

**Comment by horsburgh** [comment]
This appears to be fixed on the sandbox. Adding the tested label.
