### ISSUE TITLE
Server Error (500) when I edit a site!

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#232]
Hi @horsburgh, @Maurier and @jcaraballo17 

I just got a `Server Error (500)` when I tried to add the following new sensor to this new site: http://data.envirodiy.org/sites/update/WSU-1/
Sensor:
All External Voltage Divider	All_ExternalVoltage_Battery	Electromotive force: Volt (V)	Equipment

This seems reminiscent of the database issues that occurred after an update earlier this winter.

I did not get any errors when I added a sensor to this older site: http://data.envirodiy.org/sites/KINNI_Logger3/

I am planning on deploying a 6 sites on Thursday! Any help would be very appreciated.

**Comment by jcaraballo17** [comment]
Fixed. There was a duplicate entry for the unit `Milligram per Liter (mg/L)`. The entry with variable code `YosemiTech_Y4000_DOmgL` was using that duplicated unit and making the editing crash.
I added the sensor you wanted to add to that site and it worked just fine, you

**Comment by aufdenkampe** [comment]
Thank you!
