### ISSUE TITLE
Filters on browse sites should be applied together (AND not OR)

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#233]
So if I select a filter for organization = Stroud and site type = stream I want to see only sites that are BOTH deployed by Stroud AND site type stream, not ones that are either one or the other.

**Comment by horsburgh** [comment]
I just tried this and got the opposite result (or)?

**Comment by SRGDamia1** [comment]
Oh, I'm sorry.  Yes, I'm currently seeing OR, I want to see AND.

**Comment by horsburgh** [comment]
I believe this is working correctly. It uses AND across categories (e.g., if I click Leaf Pack data type and American Littoral Society as an organization) versus OR within categories (e.g., if I click the organization American Littoral Society at the same time as Berks Nature). I'm adding the Tested label to this one.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
