### ISSUE TITLE
Fix branding on WebTSA

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#237]
http://data.envirodiy.org/tsa/ still has the EnviroDIY branding/look.  I think this should be changed to the WikiWatershed scheme.  @aufdenkampe? @HeatherBrooks?

**Comment by HeatherBrooks** [comment]
The logo will need to be changed. I would wait until we have a new Monitor My Watershed logo, rather than switching to the WikiWatershed logo and then switching again to the Monitor logo.

**Comment by Maurier** [comment]
@SRGDamia1, do we have the desired logo available at this point?

**Comment by aufdenkampe** [comment]
The WikiWatershed Outreach Team made a final decision 2018-08-14 Biweekly Meeting
(see [2018-08-14 Biweekly Meeting](https://docs.google.com/document/d/14ZOGs80rQehmbMMJsx2cIpc29UEox7nNwFPn2xc0tzk/edit#bookmark=kix.sdztumdzheg0) Notes) to rebrand the WikiWatershed/EnviroDIY Data Sharing Portal to **Monitor My Watershed** at https://MonitorMyWatershed.org

We'll have all current URLs redirect to this once we implement it.

@HeatherBrooks and @darscott will have to provide the logo and branding fonts/colors.

**Comment by HeatherBrooks** [comment]
Branding font/color information, as well as the new Monitor My Watershed logo and site icon, are available in [WikiWatershed Branding Identity](https://drive.google.com/drive/folders/1MiPT4DBrtUaFxUiTf3CRYNVBl0X_pj0U?usp=sharing). Please let me know if you have trouble accessing or downloading the materials.
