### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#239]
To see website usage stats, etc.  @HeatherBrooks can generate keys, but then they must be inserted into the website.

**Comment by HeatherBrooks** [comment]
This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47047573-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-47047573-13');
</script>

**Comment by horsburgh** [comment]
I'm dropping this from milestone 0.8 because it is new functionality that is not related to the leaf pack stuff. It may be good to do, but we should prioritize it with other project cleanup/closeout issues. This isn't necessary for the initial leaf pack functionality roll out, which is what milestone 0.8 is focused on.

**Comment by HeatherBrooks** [comment]
The Google Analytics tracking code (posted above on May 1) has been updated to anonymize IP addresses. Only the last line before the closing tag has changed.


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47047573-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-47047573-13', { 'anonymize_ip': true });
</script>

**Comment by aufdenkampe** [comment]
Did this get implemented in Release 0.9?

**Comment by HeatherBrooks** [comment]
Yes, it was implemented. Here's a look at pageviews since the tracking code was generated in May.
![monitor-my-watershed-analytics](https://user-images.githubusercontent.com/9368629/45314316-65a87880-b4ff-11e8-905f-21e6a220c022.JPG)

**Comment by aufdenkampe** [comment]
Great! I'll close this issue.
