### ISSUE TITLE
Have site display icons on map indicative of site type and data age

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#24]
I think the TSA already has different icons for the different site types, but I love the little green/yellow/red dots vizer (http://viz.criticalzone.org/Christina) puts below the site icon to indicate data age.

**Comment by horsburgh** [comment]
@SRGDamia1 - The TSA sets its icon styles by a "network" grouping, not necessarily by SiteType (although for iUTAH, the sites are grouped into networks generally according to SiteType).  For the citizen science project - is there a short list of site/icon types we anticipate?  Should sites be symbolized by SiteType, by Organization, by User???

Also - I'm assuming this only applies to the Browse Sites page.

**Comment by aufdenkampe** [comment]
Could this be implemented as part of the plan to add facets to the map view?

**Comment by horsburgh** [comment]
@aufdenkampe - yes, if the envirodiy and leaf pack network websites get combined, we could potentially draw sites on the "browse" map based on their site type. But, what to do with sites where different types of data have been collected (e.g., a site where there are sensors and leaf pack network data)?  We can only draw sites using different icons if we have a discrete set of categories.

To do this, we need to know 1) which site attribute we are using to distinguish sites on the map and 2) which icons represent each category.

**Comment by aufdenkampe** [comment]
Sounds good. Let's re-evaluate how to prioritize this issue after we get Release 0.6 out the door.

**Comment by SRGDamia1** [comment]
+1 to this from Dave Arscott

**Comment by SRGDamia1** [comment]
The color of the symbol should indicate the data age:
green - has data within the last 24 hours
orange - within the last week, but not the last day
red - nothing with the last week

As for what the symbol should be, I was originally thinking of different symbols by site types, as they are done on the Nanoos visualization.  Now I think that would be too much effort for very little gain.

I think we should stick with a bubble pin for all symbols.  Use a slightly larger pin for user owned sites and a smaller one for others.

**Comment by SRGDamia1** [comment]
For consistency with the sparklines, we should probably change the "green" to be within the last 72 hours, thus:
blue - has data  within the last 6 hours
green - within the last 72 hours
orange - within the last 2 weeks
red - out of date

I do like the symbols within pins used in WebTSA.

**Comment by Maurier** [comment]
@SRGDamia1 Do you want to keep the current symbol in the middle? As is implemented it is bright for sites you follow or own and dark for sites you do not follow nor own.

**Comment by Maurier** [comment]
Here is how these changes look like
![image](https://user-images.githubusercontent.com/2448568/46551446-08e97500-c895-11e8-9fbd-c186034b5230.png)

Sites you own use a slightly larger marker
![image](https://user-images.githubusercontent.com/2448568/46551489-24548000-c895-11e8-8037-4aa2d7095664.png)

The color convention in the My Sites cards has been removed. All sites listed show as blue. Markers in this page use the same icons and colors as in Browse Sites
![image](https://user-images.githubusercontent.com/2448568/46551622-785f6480-c895-11e8-942f-883a66a93c85.png)

**Comment by SRGDamia1** [comment]
Hm.. I don't really love the blue on the status pins.  Could you change the < 6 hours to dark green (~ #1e8449) and <72 hours to a lighter green (~#90e522)?  It doesn't have to be those exact colors, just so you had an idea.

Dave Bresser would also prefer dark yellow to orange.

I like the different pin sizes.

I also like the re-coloring of the My Sites cards.  Blue is good.  Having them all orange was scary.

**Comment by Maurier** [comment]
@SRGDamia1 How about this:
![image](https://user-images.githubusercontent.com/2448568/46618314-6f140900-cadc-11e8-98cb-25c354344513.png)

**Comment by SRGDamia1** [comment]
I like the look of the map you just posted.  @dbressler75 ?

**Comment by SRGDamia1** [comment]
I really like the different colors in the new map you just showed.

Questions:  Will all leaf-pack-only site always appear red?  The timing categories don't really apply to leaf-pack type data.  I didn't even think of it until you were demonstrating other leaf-pack feathers just now.

@HeatherBrooks - Do you think leaf pack users will be bothered by their sites always appearing "out of date?"  Should we use a different color to represent sites where no sensors have been registered?  Blue? Green?

**Comment by horsburgh** [comment]
We might want to have a "Leaf Pack Only" site type.

**Comment by SRGDamia1** [comment]
I think grey is great for sites with no data at all.  I think we want blue or some other color for sites that do have leaf pack data but no sensors.  If there's leaf pack and sensors, use the coloring for a sensor.

**Comment by HeatherBrooks** [comment]
Tara would like to use Leaf Pack Network brand colors wherever possible. Here are colors in the logo:
Green: hex #8fba3e, RGB 143 186 62
Orange: hex #dc5428, RGB 220 84 40
I would prefer the orange. A deep golden yellow might also work.

**Comment by Maurier** [comment]
Here is how that looks like
![image](https://user-images.githubusercontent.com/2448568/46895427-93058080-ce35-11e8-9b01-e8a27d4a64fd.png)

I had to use a brighter orange since the one you mention was too close to red and looked to similar to other red markers.

The legend text can probably use changes. Let me know what you would like.

**Comment by HeatherBrooks** [comment]
Thanks for the example. I think the orange is still too close to the red, especially for people with red-green colorblindness. I see that you're using different shapes for ownership status ... is there a different marker shape you can use for the leaf pack data?

**Comment by Maurier** [comment]
How about one of these?

![map-markers](https://user-images.githubusercontent.com/2448568/47729882-9ca92980-dc26-11e8-8aa4-c6cd8c256073.png)

**Comment by HeatherBrooks** [comment]
Now that I see these, I think using a different marker shape in the orange will still be hard to distinguish. But I like the blue marker, can it be used? I know it's not in the leaf pack branding colors, but it will certainly be easy to tell the leaf pack data from the sensor data.

**Comment by Maurier** [comment]
Yes, I have added the blue marker for this case. This change will show up in the next update. Here is hot it looks like:
![image](https://user-images.githubusercontent.com/2448568/47754134-853a6280-dc5f-11e8-8787-faf68a5471e1.png)

**Comment by horsburgh** [comment]
@Maurier - nearest I can tell, this looks good on the sandbox. It's a little hard to test because all of the data are out of date on the sandbox, so several of the markers don't show up on the map at all.  I'm going to add the "tested" label.
