### ISSUE TITLE
User sdamiano exists twice...

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#244]
Please kill one of them and transfer all stations from that one to the other one.  I don't even know which one is which.

![image](https://user-images.githubusercontent.com/5374350/39708891-66439076-51e6-11e8-8271-0f1d109750cf.png)

**Comment by darksinge** [comment]
I checked the database and there is an account named "sdamiano" and one named "SGDamiano1". Do you own both of those accounts?

**Comment by SRGDamia1** [comment]
Most likely. I doubt I have any imposters. Could you please move everything from the lowercase user to the other and then delete the lowercase user?

**Comment by SRGDamia1** [comment]
Please delete the sdamiano account.

**Comment by darksinge** [comment]
This is done, closing.

**Comment by SRGDamia1** [comment]
Thank you!
