### ISSUE TITLE
After selecting the Campbell OBS3 variable in WebTSA, no variables appear to be selected

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#245]
![image](https://user-images.githubusercontent.com/5374350/39709050-cbe08f1a-51e6-11e8-9d7f-cd1126faf8a6.png)

This consistently happens, whether entering TSA from a specific site/variable or directly from data.envirodiy.org/tsa

**Comment by SRGDamia1** [comment]
Also unable to overlay turbidity from multiple sites

**Comment by SRGDamia1** [comment]
The filter for the Campbell_OBS-3+_Turb variable seems to be the problem.  Could it be the "+" in the variable code that is causing the problem?

**Comment by SRGDamia1** [comment]
I removed the "+" from the code in the admin panel, but that change doesn't seem to have propagated through to TSA.

**Comment by SRGDamia1** [comment]
Did you change anything?  It seems to be working now.

**Comment by horsburgh** [comment]
@SRGDamia1 - @jcaraballo17 can confirm for sure, but I suspect it just took a little bit for the change you made to get propagated to the TSA catalog database via the script that keeps the databases in sync.

**Comment by SRGDamia1** [comment]
Okay.  Then if the "+" was the problem, it's good to know and I'll double check that there are no other variables with special characters in them.

**Comment by horsburgh** [comment]
As a general rule, I would avoid special characters in SiteCodes, VariableCodes, etc. Thorough programming should ensure that they get escaped correctly, but that doesn't always happen.

**Comment by SRGDamia1** [comment]
@aufdenkampe I changed the Keller variables to remove the "+" in them.  It seems like the special character was really the only problem, so I'll close this for now.

**Comment by aufdenkampe** [comment]
Thanks!

Sent from my iPhone

On Jun 5, 2018, at 3:27 PM, Sara Damiano <notifications@github.com<mailto:notifications@github.com>> wrote:


@aufdenkampe<https://github.com/aufdenkampe> I changed the Keller variables to remove the "+" in them. It seems like the special character was really the only problem, so I'll close this for now.

-
