### ISSUE TITLE
Organizations are listed both as codes and full names in filters

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#246]
When browsing sites, the organizations seem to appear randomly as either a full name or a code.  So, in the snap below, "WSU" is a code; the full organization name is Winona State University, but "The Nature Conservancy" is the full organization name; it has a code of "TNC."  

![image](https://user-images.githubusercontent.com/5374350/39876670-d268bddc-5441-11e8-9c60-1763e356c152.png)

**Comment by SRGDamia1** [comment]
I created another issue (#243) for Stroud existing twice, but we're not the only ones who do.  The Nature Conservancy is actually there twice, once spelled out and once as TNC.  UWRL exists by that code and as Utah Water Research Laboratory.  I don't see any pattern in which sites are listed by code and which by full organization name.  Almost all of the sites that are listed as both "Stroud" and "Stroud Water Research Center" are registered to the same user.. me.

**Comment by horsburgh** [comment]
@jcaraballo17 or @Maurier  - can you check to make sure the browse facet is only using the organization name?

@SRGDamia1 - I'm not completely sure what's going on here, but given that the creation of organizations is free text and users can input whatever they want, there is potential for duplicate entries. We'll verify that the browse is working correctly and only including the organization name.

**Comment by SRGDamia1** [comment]
I definitely understand the potential for duplicate organizations, but at least from what I can see in the Django admin panel that I have access to.... none of these are actually cases of duplicate organizations.

**Comment by jcaraballo17** [comment]
As @SRGDamia1 mentioned, the problem is not that there are duplicate organizations, but we're showing both organization code and organization name as separate things.

**Comment by jcaraballo17** [comment]
@SRGDamia1  @horsburgh This should be fixed now.

**Comment by SRGDamia1** [comment]
Wahoo!  Looks good to me!  Thank you!
