### ISSUE TITLE
Can't connect data.envirodiy.org account to hydroshare

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#250]
When I try to connect via my user account in upper right it takes me to an authorize data.wikiwatershed.org tab - when I click that tab it gives me "Server Error (500)".

**Comment by horsburgh** [comment]
@dbressler75 - just to confirm, do you have a HydroShare account already?

**Comment by horsburgh** [comment]
OK. Great. Thanks for the quick reply. We'll follow up on this and see what's up.

@darksinge - can you look into this and see what's going on?

**Comment by dbressler75** [comment]
Ok great, thanks very much

David W. Bressler
Citizen Science Project Facilitator
Stroud Water Research Center
410-456-1071 (mobile)
610-268-2153 x312 (office)
dbressler@stroudcenter.org

**Comment by darksinge** [comment]
We're in the process of migrating the website domain name from `data.envirodiy.org` to `data.wikiwatershed.org`. It looks like you tried connecting your account to hydroshare from `data.envirodiy.org`, but hydroshare redirected you back to `data.wikiwatershed.org`, which caused the error.

If you log into `data.wikiwatershed.org` and try connecting your account again, it should work.

I'll get working on a fix for this. Thanks for submitting this issue @dbressler75 !

**Comment by dbressler75** [comment]
Great, thank you!

David W. Bressler
Citizen Science Project Facilitator
Stroud Water Research Center
410-456-1071 (mobile)
610-268-2153 x312 (office)
dbressler@stroudcenter.org

**Comment by darksinge** [comment]
The fix for this will make its way into production with the next release. Closing.
