### ISSUE TITLE
Add a "sensor" is misnomer - really adding a variable

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#252]
The buttons, etc, ask you to add a "sensor," but in reality you're adding a variable.  So you may actually enter the same "sensor" many times.  Functionally, this is fine, but we may want to think about changing the naming.  I'm not sure what to call it, though.  I'm afraid saying "add variable" will confuse anyone who isn't familiar with the ODM2 terminology.

**Comment by aufdenkampe** [comment]
This issue is connected to one of my earlier comments, in https://github.com/ODM2/ODM2DataSharingPortal/issues/71#issuecomment-364512461 and https://github.com/ODM2/ODM2DataSharingPortal/issues/74#issuecomment-332660214, regarding the potentially confusing (i.e. not conceptually correct) use of terms relative to our ODM2 concepts and terms.

**Comment by jcaraballo17** [comment]
@SRGDamia1 @aufdenkampe This is something we could do this time around. Did we ever agree on a name?

**Comment by SRGDamia1** [comment]
No, I don't think we did.

**Comment by aufdenkampe** [comment]
The current wording is 
1. "Manage Sensors" on a blue button on the Sites page
2. "Manage Sensors at *MySiteX*" as the title to the page where the user adds or edits sensor Results metadata, (i.e. Equip Make-Model, Measured Variable, Units, Sampled Medium, Height and Notes).

For 1, I think "Manage Sensors" works well for the blue button.

For 2, I might modify the title of the page to be one of the following: 
* "Manage Sensor Results Metadata for *MySiteX*", or
* "Manage Sensor Variables Metadata for *MySiteX*"

@SRGDamia1, any preferences for either of these?

I'm OK with either approach. As I described in https://github.com/ODM2/ODM2DataSharingPortal/issues/74#issuecomment-332660214, the combination of all this metadata is best grouped under the concept of an ODM2 Result. However, as Jeff pointed out in his reply, we use the EquipmentMakeModel+VariableName as  VariableCodes in this deployment of ODM2.

**Comment by aufdenkampe** [comment]
@SRGDamia1, I also think ""Manage Sensor Results Metadata for MySiteX" is potentially less confusing for new users, while also being more accurate for those of us who know ODM2 (which is also an important audience, as we are trying to leverage this as an important part of the ODM2 ecosystem).

@jcaraballo17, please change the page title (2 above) to "Manage Sensor Results Metadata for MySiteX".
