### ISSUE TITLE
Help: Document JSON input structure on website

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#254]
Right now I don't think it's documented anywhere, except maybe as an issue in this repo.  I'm not quite sure where it belongs; maybe part of the future help section (#216).

**Comment by horsburgh** [comment]
See the link on the front page of the repostitory: 

https://github.com/ODM2/ODM2DataSharingPortal

to this page: 

https://github.com/ODM2/ODM2DataSharingPortal/blob/master/doc/example_rest_requests.md

**Comment by SRGDamia1** [comment]
Yes, sorry.  I think there should be something actually on data.wikiwatershed.org.

**Comment by horsburgh** [comment]
Resolution - content will be authored at wikiwatershed.org/help and then we will add a help link to the top of the Data Sharing Portal with a "Help" link that points at that help system. None of the help content will be in the Data Sharing Portal site.

**Comment by aufdenkampe** [comment]
This will be implemented with #216.

**Comment by jcaraballo17** [comment]
Closing in favor of #216
