### ISSUE TITLE
Bugs in database for Organizations and potentially elsewhere 

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#256]
In our call last Tuesday I described a few bugs related to Organizations.

@jcaraballo17 said he understood and would fix the issue, but I don't see a place that it is being tracked.

@fisherba noticed another bug that might be a database bug, which I'll let her describe.

cc: @horsburgh & @Maurier

**Comment by fisherba** [comment]
When I try to view the data for http://data.envirodiy.org/sites/PM01/ in Time Series Analyst, it shows data for several other sites, including Limno Crossroads and the Kinni river sites by LimnoTech.

**Comment by horsburgh** [comment]
@jcaraballo17 - can you give us a quick update on this one? Is it a simple fix in the database? I want to see if we should leave this in the 0.8 milestone because I don't want to hold up the release of the leaf pack functionality.

**Comment by jcaraballo17** [comment]
@horsburgh The organization code problem is a simple fix in the database, so you can leave it as part of the milestone. I just haven't had time to address it yet.
I'll have to look into the time series analyst issue to see what's going on, but it sounds like an issue with either the url parsing in the tsa, or url we're using to redirect from envirodiy to the tsa.

**Comment by jcaraballo17** [comment]
@aufdenkampe The organizations should be back to normal now.
I think that any site that you register before the release it's going to temporarily display the organization code instead of the organization name, but this problem will go away after we deploy the latest version to the production server.

**Comment by horsburgh** [comment]
@jcaraballo17 - did you fix this on production or on the sanbox?

**Comment by jcaraballo17** [comment]
production.

**Comment by horsburgh** [comment]
I'm going to assume that Anthony's comment means that this one has been fixed. I'm adding the Tested label.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
