### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#257]
We just learned on today's Monitor My Watershed call that it is possible to get free security certificates from https://letsencrypt.org/, and that it would be a good idea for this site given user login info, registration tokens, etc.

@Maurier or @jcaraballo17, would it be possible to implement HTTPS for this release?

cc: @horsburgh & @emiliom

**Comment by horsburgh** [comment]
Dropping this one out of 0.8 release, which is focused on Leaf Pack functionality.

**Comment by aufdenkampe** [comment]
It looks like fixing this is now a very high priority. I just got this while browsing on Chrome to this URL
http://data.wikiwatershed.org/sites/WSU-3/

<img width="788" alt="screen shot 2018-06-13 at 2 50 38 pm" src="https://user-images.githubusercontent.com/5166036/41374676-7cbfa114-6f19-11e8-91c1-6769d8810826.png">

Clicking on the info button before the URL gives me this message.
<img width="791" alt="screen shot 2018-06-13 at 2 50 54 pm" src="https://user-images.githubusercontent.com/5166036/41374717-93cd694a-6f19-11e8-9653-3470ae05c2e0.png">

Which doesn't actually tell me that I can go into my browser setting to over-ride the "Server Error (500)" behavior. We can't expect our users to do that.

cc: @darscott & @HeatherBrooks

**Comment by aufdenkampe** [comment]
This is also occurring in FireFox, and it is unclear to me how to reset settings in either Chrome or Firefox to "trust" our website.

Did Google jump ahead on its plan to do this July 1st?
https://searchengineland.com/effective-july-2018-googles-chrome-browser-will-mark-non-https-sites-as-not-secure-291623

**Comment by jcaraballo17** [comment]
All,
We've found the issue and it should be fixed soon. It happens when you try
to access the site details page when you're logged out.

**Comment by aufdenkampe** [comment]
@jcaraballo17. Yes, that's it! Thanks for figuring that out!

Given that Google will be shaming us starting on July 1 for having an insecure site, I think we should still keep that issue on the priority list.

**Comment by aufdenkampe** [comment]
I can now see content in sites details pages Chrome and Firefox (such as http://data.wikiwatershed.org/sites/WSU-3/), even when not logged in. Thanks!

**Comment by jcaraballo17** [comment]
Yes! that problem is solved now, but this should still be a high priority issue given all the warnings that chrome and firefox are giving us.

**Comment by darksinge** [comment]
HTTPS is now enabled. To avoid potential issues, the website will remain open to HTTP traffic, but prepending `https://` to any URL on the website will establish a secure connection. Users who navigate to `/login`, `/register`, or `/password-reset/` will be redirected to the HTTPS equivalent page.

**Comment by jcaraballo17** [comment]
This fixed the map location services. The Browse Sites now asks for your location and zooms in to show you the sites around your area.
