### ISSUE TITLE
Fix 503 & 504 server errors

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#258]
@horsburgh, @Maurier and @jcaraballo17,

GetValues requests from the WikiWatershed / Monitor My Watershed web app to the EnviroDIY Data Sharing Portal are giving lots of 504 and 503 server errors. See https://github.com/WikiWatershed/model-my-watershed/issues/2859.

Also, this week @fisherba was getting a number of 500ish server errors when sending POST requests from one of her loggers. I wonder if it is related.

Can you work with @rajadain and others at Azavea to understand and hopefully fix this problem, preferably this week so that we can move forward with a big Monitor My Watershed release the following week?

cc: @emiliom, @rajadain

**Comment by horsburgh** [comment]
@aufdenkampe - first priority for this week for us is getting the 0.8 release done for the data sharing portal. @jcaraballo17 - if you've got time to look at this while you are waiting for results from testing of the 0.8 release that would be great.

I'm dropping this out of the 0.8 release milestone because it isn't related to the leaf pack network functionality. @jcaraballo17 - we might want to consider a hotfix for this when you figure out what is going on.

**Comment by emiliom** [comment]
@aufdenkampe I'm a bit confused. I assume the `GetValues` requests you mention are WOFpy requests. But the POST requests from loggers sound like something else entirely, right? ie, requests that send data to the EnviroDIY database.

So it sounds like you're lumping different system components and failure points into this issue, but suggesting that they might have a common cause?

**Comment by rajadain** [comment]
For this code:

<details>
<summary>
<strong>enviro-diy-failure.py</strong>

```python
from ulmo.cuahsi import wof
```
</summary>

```python
def get_values():
    wsdl = 'http://data.envirodiy.org/wofpy/soap/cuahsi_1_1/.wsdl'
    site = 'EnviroDIY:SHPK3S'
    variable = 'envirodiy:Decagon_CTD-10_Cond'
    from_date = '05/15/2018'
    to_date = '05/30/2018'

    wof.get_values(wsdl, site, variable, from_date, to_date, None)

if __name__ == '__main__':
    get_values()
```
</details>

Running a simple `time` command (and ignoring Python warnings to reduce noise of deprecated Pandas functions), we have:

<details>
<summary>
<strong>Timing EnviroDIY</strong>

```bash
$ time -p python -W ignore enviro-diy-failure.py
```
</summary>

```
Traceback (most recent call last):
  File "enviro-diy-failure.py", line 15, in <module>
    get_values()
  File "enviro-diy-failure.py", line 12, in get_values
    wof.get_values(wsdl, site, variable, from_date, to_date, None)
  File "/Users/rajadain/play/ulmo/ENV/lib/python2.7/site-packages/ulmo/cuahsi/wof/core.py", line 179, in get_values
    endDate=end_dt_isostr)
  File "/Users/rajadain/play/ulmo/ENV/lib/python2.7/site-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/Users/rajadain/play/ulmo/ENV/lib/python2.7/site-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/Users/rajadain/play/ulmo/ENV/lib/python2.7/site-packages/suds/client.py", line 752, in send
    return self.process_reply(content, e.httpcode, tostr(e))
  File "/Users/rajadain/play/ulmo/ENV/lib/python2.7/site-packages/suds/client.py", line 819, in process_reply
    raise Exception((status, description))
Exception: (504, u'Gateway Time-out')

real        62.12
user         0.63
sys          0.22
```
</details>

So we get a Gateway Time-out after 62 seconds. When this code [is called from Model My Watershed](https://github.com/WikiWatershed/model-my-watershed/blob/ea6467447137d32e6cc1a171e4f40e5eabfb1f01/src/mmw/apps/bigcz/clients/cuahsi/details.py#L55), it ties up our app workers for 62 seconds before releasing them. While the app workers are busy with this request, they cannot serve other requests. Hence, we're going to preemptively cap this to a much smaller timeout on our end.

Notably, other services (such as NWISUV) take ~2.7 seconds for a response. EnviroDIY seems to be an exceptional offender in this case.

<details>
<summary>
<strong>nwisuv-success.py</strong>

```python
from ulmo.cuahsi import wof
```
</summary>

```python
def get_values():
    wsdl = 'http://hydroportal.cuahsi.org/nwisuv/cuahsi_1_1.asmx?WSDL'
    site = 'NWISUV:01474500'
    variable = 'NWISUV:72204'
    from_date = '04/25/2018'
    to_date = '05/25/2018'

    wof.get_values(wsdl, site, variable, from_date, to_date, None)

if __name__ == '__main__':
    get_values()
```
</details>

<details>
<summary>
<strong>Timing NWISUV</strong>

```bash
$ time -p python -W ignore nwisuv-success.py
```
</summary>

```
real         2.70
user         0.88
sys          0.24
```
</details>

Hope this clarifies matters some.

**Comment by aufdenkampe** [comment]
@horsburgh, that makes sense to drop it from this milestone, but to keep it on high priority for a potential hot-fix.

@emiliom, yes, I understand that the `getValues` requests are processed by the WOFpy code and that the `POST` requests are processed by part of the Django code, so it is very possible that the failures are completely unrelated. However, there is also a possibility that the failures are connected, possibly via an infrastructure setting, firewall issue, or something like that. I don't really know. The perplexing thing that @fisherba was that the POST request would work about ~20% of the time, and fail ~80% of the time.  That said, I just spent some time on Data.EnviroDIY.org and found that other deployed  stations, such as http://data.envirodiy.org/sites/160065_Limno_Crossroads/, seem to be reporting continuously without any data gaps. So it now seems unlikely that there's a system-wide issue with `POST` requests.

@rajadain, thanks for your testing code and results.

**Comment by jcaraballo17** [comment]
@aufdenkampe This is unrelated to the problem @fisherba is having with the data stream api. It sounds like the issue described here is part of WOFpy, so I'll probably won't be of much help here.

**Comment by horsburgh** [comment]
@aufdenkampe - To do any real debugging here it would be helpful to have the specifics of requests that are successful and those that are failing. SiteCodes, VariableCodes, data ranges, etc.

**Comment by rajadain** [comment]
@horsburgh There's a failing and working example in my comment above with site codes, variable codes, and from and to date ranges: https://github.com/ODM2/ODM2DataSharingPortal/issues/258#issuecomment-393738600

**Comment by emiliom** [comment]
> To do any real debugging here it would be helpful to have the specifics of requests that are successful and those that are failing. SiteCodes, VariableCodes, data ranges, etc.

Yup. @rajadain 's report is very useful in this respect, at least for WOFpy assessments.

**Comment by horsburgh** [comment]
Ah. Sorry - I hadn't click the arrows to expand the examples. Thanks!

**Comment by emiliom** [comment]
> @aufdenkampe - first priority for this week for us is getting the 0.8 release done for the data sharing portal. @jcaraballo17 - if you've got time to look at this while you are waiting for results from testing of the 0.8 release that would be great.
>
> I'm dropping this out of the 0.8 release milestone because it isn't related to the leaf pack network functionality. @jcaraballo17 - we might want to consider a hotfix for this when you figure out what is going on.

BTW, I don't really know what this means, specially vis a vis the errors @rajadain is reporting and potential WOFpy implications. It *sounds* like I can ignore it?

**Comment by horsburgh** [comment]
So - are all requests to the EnviroDIY WOFPy service failing? The successful test above is from the NWISUV service.

**Comment by horsburgh** [comment]
Need to clarify here - this isn't a data.envirodiy.org issue (or at least it isn't an issue with the data sharing portal website developed by USU). 

This is a WOFPy issue that may be related to the code of the WOFPy service, its deployment on our server, and/or the size of the data. Given that it was working over the winter/spring, my suspicion is that the database/datasets have now gotten large enough that it is taking longer to retrieve them from the ODM2 database and serialize them to WaterML. We haven't changed or even touched the WOFPy deployment in several months. @emiliom can correct me if I'm wrong, but I don't think we have good scalability testing for WOFPy services that would reveal where we should expect to start running into trouble with timeouts.

Using the sample REST requests here:

http://data.envirodiy.org/wofpy/rest_1_1/

The service is running, and the GetSites, GetSitesByBox, GetSiteInfo, GetSiteInfoMultiple endpoints work and return responses. The GetVariables and GetVariableInfo endpoints work sometimes (but time out most times), and the GetValues endpoint is timing out in all of the examples. I tried modifying one of the GetValues request to get data from today only and it still timed out.

Given that we (USU) just deployed the latest version of WOFPy, we are likely going to need some help debugging. @jcaraballo17 is looking at things now to see if there is anything we can do immediately.

**Comment by emiliom** [comment]
I went back to the set of WOF benchmark testing I worked on earlier, which included EnviroDIY WOFpy. As Anthony said, back then (**mid March**), `GetValues` responses may have been slow, but they were working. I was getting one sample request for 11 months of data in 86 seconds  ("wall time", which includes processing time once the data has been fetched). I reused the code from back then, and the specific site and variable, but shortened the time period length to one month. The code used, while not strictly identical to @rajadain's, it's conceptually the same:

```python
from ulmo.cuahsi import wof

envirodiy_wof = dict(
    wsdl_url = 'http://data.envirodiy.org/wofpy/soap/cuahsi_1_1/.wsdl',
    site_code = 'EnviroDIY:JRains1',
    variable_code = 'envirodiy:MaxBotix_MB7386_Distance',
    start = '01/18/2018', # Initially, test a shorter time period
    # start = '03/18/2017',
    end= '02/15/2018'
)
```
```python
%time gv = wof.get_values(**envirodiy_wof)
```
```
CPU times: user 3.02 s, sys: 63.1 ms, total: 3.08 s
Wall time: 13.4 s
```

@rajadain's test (different site, different variable, and only half a month) timed out after 62 seconds, while this one executed successfully after 13.4 sec for a time period that's twice a long. A caveat: @rajadain's benchmarking is for everything in his code, all the way to the `import` statement. Mine is only for the actual `wof.get_values` request. Anyway, these are *qualitatively* different results!

I just reran the same test request with the original time period length (11 months), and it completed successfully with a wall time of 66 sec -- even faster than 3 months ago (86 sec)!

@horsburgh is correct about this:
> @emiliom can correct me if I'm wrong, but I don't think we have good scalability testing for WOFPy services that would reveal where we should expect to start running into trouble with timeouts.

What we've done is a bunch of spot checking of performance.

My conclusion: If one site and variable can yield reasonable/ok performance, "the problem" is not all encompassing and can't be just the increase in total data volume since March or early winter. Something else may be going that does have to do with the specifics of this ODM2 database. It'll take digging.

Also, in past testing we've found that problems with one or more variable can cause problems in unqualified `GetVariables` and `GetVariableInfo` requests. We implemented substantial error checking based on the use cases Don and I had at hand, but there's always new ways to fail!

Not sure where this leaves us. Let's reconnect early next week.

**Comment by rajadain** [comment]
On a tangential note, Ulmo is missing native support for timeouts, causing us to use a wrapper instead. However, its underlying components do support timeouts, so adding support for their specification would be useful for such cases in the future. I've added https://github.com/ulmo-dev/ulmo/issues/155 for that.

**Comment by aufdenkampe** [comment]
@emiliom, thanks for your extra testing.
The site you tested, http://data.envirodiy.org/sites/JRains1/, doesn't have any data since Feb (not sure that should matter).
I was able to find it on https://staging.app.wikiwatershed.org/analyze and did get some of the data to fetch.

@rajadain, did you find a fix?

@emiliom, can you run some tests to only fetch the last week, as we do for WikiWatershed?
It really doesn't make sense that it is so slow to just fetch a week of data.

**Comment by aufdenkampe** [comment]
I just did some spot testing of EnviroDIY sites in the White Clay Creek HUC10 (in SE PA), and I see that data values are now getting fetched for many of the variables, but fetching is still taking a very long time (>30 s). Did a fix get implemented?

Regardless, this is an acceptable situation for this release.
Speeding things up will be a priority for the next release.

**Comment by rajadain** [comment]
With https://github.com/WikiWatershed/model-my-watershed/pull/2866 deployed to staging, now we stop after 5 seconds for all data sources. This may be upped to 8s with https://github.com/WikiWatershed/model-my-watershed/pull/2870, but that would be the upper limit for APIs to respond.
