### ISSUE TITLE
Separate adding sensor/leaf pack data from editing a site

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#259]
I think the "edit" button for site data should only be to edit the metadata on the sampling feature itself (lat/long/etc).  There should be separate pages for editing sensors and for adding leaf pack data.  When the sensors were required for a site, it made sense the way it is, but it's not at all intuitive to have to "edit" a site to add a leaf pack experiment.

**Comment by SRGDamia1** [comment]
![image](https://user-images.githubusercontent.com/5374350/40922004-006dd19e-67df-11e8-99c7-792a38fe760d.png)

![image](https://user-images.githubusercontent.com/5374350/40922053-1fdf18bc-67df-11e8-9150-89a24aa8477b.png)

![image](https://user-images.githubusercontent.com/5374350/40922098-4cca5ae4-67df-11e8-9d3b-15e7f5261e5a.png)

**Comment by Maurier** [comment]
We have made changes accordingly. They are ready for testing at http://envirodiysandbox.usu.edu

**Comment by SRGDamia1** [comment]
This looks great!  Two very minor title changes:

Remove the word leaf here:  
![image](https://user-images.githubusercontent.com/5374350/41107659-c81a19b0-6a40-11e8-9e54-906d10ff634d.png)

And add the word "pack" after leaf here:
![image](https://user-images.githubusercontent.com/5374350/41107780-07045e60-6a41-11e8-9c83-49a3d7d73a41.png)

**Comment by horsburgh** [comment]
Tested on the sandbox. I edited site details and saved. I added sensors and they take effect immediately. The "Back to Site Details" button works great. I also added a leaf pack experiment. All are separate and working correctly.

Everything seems to be working correctly here. Adding tested label.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
