### ISSUE TITLE
Home page title should be "Data Sharing Portal"

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#262]
Page title should be "Data Sharing Portal".

This is correct on production, but not staging, which has incorrectly reverted back to "Water Quality Data Portal".

I *think* we decided on this with #171, or at least during a call at around that time.

Adding to this milestone, because I'm presuming this was just an oversight.

cc: @Maurier, @horsburgh

**Comment by aufdenkampe** [comment]
@darscott & @SRGDamia1, do we also change the subtitle?
* from "Data Sharing for the Citizen Science Community"
* to "Contribute your water quality data"

**Comment by SRGDamia1** [comment]
Also remove line "Data Sharing for the Citizen Science Community"

![image](https://user-images.githubusercontent.com/5374350/40999289-6cd499e0-68d8-11e8-8e3a-eac736832144.png)

**Comment by aufdenkampe** [comment]
@SRGDamia1, how about changing the subtitle to "Contribute your water quality data"?

**Comment by SRGDamia1** [comment]
That sounds good to me.

**Comment by horsburgh** [comment]
@Maurier - looks like the subtitle has changed on the sandbox, but the main title has not changed. I'm assuming you are working on this one?

**Comment by Maurier** [comment]
Done. This will show up on the next update.

**Comment by horsburgh** [comment]
Looks like this has been corrected on the sandbox. Adding the Tested label.

**Comment by horsburgh** [comment]
Live on production as part of 0.8 release. Closing.
