### ISSUE TITLE
Water quality index not calculated, taxa graph not shown

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#269]
I entered [leaf pack experiment data](https://data.wikiwatershed.org/sites/BogBrook_Rt312/leafpack/4/) and am seeing a blank box in Chrome and Firefox where the water quality index and macroinvertebrate graph should be?
![image](https://user-images.githubusercontent.com/9368629/41871302-8093da04-788c-11e8-9d02-1d0a476de749.png)

**Comment by darksinge** [comment]
Fixed. Thanks for the catch.
