### ISSUE TITLE
Changes to taxonomic text for leaf pack data input

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#273]
Some minor changes are needed to the text of the leaf pack data entry page related to the taxonomic classes.

Changes needed are described in this Google Doc:  https://docs.google.com/spreadsheets/d/11lJehfHBXBmD5dKPukVJnQZWqVgYyIEGvh7NLwF2n8M/edit#gid=0

@darksinge - should be pretty straightforward.

**Comment by darksinge** [comment]
@horsburgh [envirodiysandbox.usu.edu](http://envirodiysandbox.usu.edu) has been updated with the requested changes.

**Comment by horsburgh** [comment]
Tested on the sandbox. These changes have been made and look good. Adding the "tested" label.

**Comment by horsburgh** [comment]
Live on production. Closing.
