### ISSUE TITLE
Tweaks to Leaf Pack Experiment Data Entry Form

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#287]
Minor tweaks to text, which have been requested by @heatherbrooks and Tara around July 25.

See the [Tweaks to Leaf Pack Experiment Data Entry Form](https://docs.google.com/document/d/1Cx1--ngice9qP848oOUoRSghkkW--7VySifSoiZ-8r8/edit) Google Doc for details.

**Comment by aufdenkampe** [comment]
@darscott is updating the branding text for the "Explore Our Companion Projects" section of the home page, to align with the new [WikiWatershed Branding Identity](https://drive.google.com/drive/folders/1MiPT4DBrtUaFxUiTf3CRYNVBl0X_pj0U?usp=sharing) that @HeatherBrooks and I described and pointed to in #237.

The new text can be found in at the bottom of the [Tweaks to Leaf Pack Experiment Data Entry Form](https://docs.google.com/document/d/1Cx1--ngice9qP848oOUoRSghkkW--7VySifSoiZ-8r8/edit) Google Doc.

I'm separating this rebranding work into a new issue, #313.

**Comment by horsburgh** [comment]
@Maurier - I think this mostly looks good on the sandbox. I did find one small issue:

On step 2 under storm and non-storm events, they wanted you to remove the text "(depth)" from the total precipitation that occurred entry, but you also removed the "cm" label. You need to add the "cm" label back.

Otherwise this one looks good on the sandbox. I created a new experiment, and all of the data fields were saved and displayed on the view page after creating the experiment.

**Comment by darscott** [comment]
Jeff et al,
Just a small thing I noticed that I wasn't aware of as far as a requested
change...some of the font type on the home page changed to serif font. I
used to be a san serif font that was more inline with the
branding...specifically the headers: "Data Sharing Portal", "How it works",
and "Explore the WikWatershed Toolkit" font types...Please don't hesitate
to correct me if that was something that "we" called for changing?
Dave

___________________________________________________________________________________

Dave B. Arscott, Ph.D. - Executive Director, Research Scientist

Stroud Water Research Center -  Avondale, PA 19311 USA
Phone: (office) 610-268-2153 x 278, (mobile) 484-885-5225

Advancing knowledge and stewardship of fresh water through global research,
education, and restoration
_____________________________________________________________________________________



*Making a gift/pledge in honor or memory of someone special is a
particularly meaningful way to aid the mission of the Stroud Water Research
Center Special Gifts program.  In addition, please consider a challenge
match grant by contacting David Reinfeld to establish match
parameters. Make an online donation now
<https://stroudcenter.org/make-special-gift> or call 610-268-2153, ext.
314, with any questions about contributing a gift or a multi-year
pledge. Established Challenge Match grants:*

   - *$1 Million Challenge Match Grant generously sponsored by Rod and
   Alice Moorhead to benefit the Bernard W. Sweeney, Ph.D., Executive
   Director’s Fund:* This challenge grant will provide seed funding to
   ensure strategic initiatives that are vital for Stroud Water Research
   Center’s mission. Your charitable donation will be matched
   dollar-for-dollar thanks to the generosity of Rod and Alice. Help us meet
   and exceed the $1,000,000 goal!


   - *$50,000 Challenge Match Grant generously sponsored by Spurlino Family
   Foundation to benefit the Scientific Research Fund.* Your charitable
   donation will be matched dollar-for-dollar thanks to the generosity of the
   Spurlino Family Foundation. Help us meet and exceed the fund goal!

**Comment by HeatherBrooks** [comment]
Good catch! I'm seeing Ubuntu for the headings but that's because I have it installed on my PC. You can embed Ubuntu from Google Fonts or you'll need to use a fallback in your CSS, something along the lines of "font-family: 'Ubuntu', Helvetica, sans-serif;" so it doesn't default to Times New Roman for users that don't have Ubuntu.

**Comment by horsburgh** [comment]
The "cm" label is back! Adding the "tested" label to this one.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @htaolimno As I was testing the data entry form today I discovered one small problem remaining in regards to  [https://github.com/ODM2/ODM2DataSharingPortal/issues/287#issuecomment-434823270](url). "Depth" has been removed from the data entry form but not from the experiment display page.

Correct on data entry form:
<img width="177" alt="lpn-data-entry-storm" src="https://user-images.githubusercontent.com/9368629/71682713-75844580-2d5e-11ea-84af-bb812e74f64d.png">
Incorrect on experiment display page:
<img width="338" alt="lpn-display-storm" src="https://user-images.githubusercontent.com/9368629/71682718-787f3600-2d5e-11ea-99e5-15a0a580df5c.png">
Please remove "depth" from the text string on the display page.
