### ISSUE TITLE
Fix Home page text and hyperlinks

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#288]
@horsburgh, @Maurier and @jcaraballo17.

@darscott, @heatherbrooks and I noticed that the main landing page on Production seems to have lost all of it's new text and hyperlinks from logos and boxes below "How It Works". 

In other words, all the work on #219 for Release 0.7 seems to have been reverted with this Release 0.9.

Can we get the old home page back?

**Comment by aufdenkampe** [comment]
@horsburgh and @Maurier, thanks for looking into this. Thanks also for pointing out that I had not carefully read #219 and compared it to the current home page.

@darscott, @HeatherBrooks and I did all believe that the logos below "How It Works" had hyperlinks to their respective websites. I guess that might have been our memories of our discussion on this!

**Comment by Maurier** [comment]
Discussion moved to https://github.com/ODM2/ODM2DataSharingPortal/issues/287 as further changes have been specified there.

Closing
