### ISSUE TITLE
Hide 'height' if left empty for a sensor

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#291]
When looking at the sensor spark lines on a single site page, do not show the "height" value in the block if left blank ("-").  The notes field is already only visible if filled out (not "none"); I would just like the height field to have the same behavior.

**Comment by jcaraballo17** [comment]
This is done on the development branch. marking as fixed.

**Comment by horsburgh** [comment]
This appears to be fixed on the sandbox server. For a variable that has site and notes, they are shown. For a variable that doesn't have content for these values, they are not shown. Adding the "tested" label to this one.

**Comment by aufdenkampe** [comment]
This is a nice touch, as it is more efficient with space on the page.
