### ISSUE TITLE
Time zone is not labeled in WebTSA 

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#293]
The time axis appears to be in UTC, but is not labeled as such.

**Comment by aufdenkampe** [comment]
I mentioned this need for a Time Zone label in https://github.com/ODM2/ODM2DataSharingPortal/issues/236#issuecomment-412143248, and I suspect the additional label could be done very quickly.

I also mentioned in https://github.com/ODM2/ODM2DataSharingPortal/issues/236#issuecomment-412143248 several other issues relative to the time axis that would be worth exploring.

**Comment by jcaraballo17** [comment]
Fixed on the development branch. @Maurier added a label specifying that the times are in UTC. Marking as fixed.

**Comment by Maurier** [comment]
@horsburgh This issue can be tested now.

**Comment by aufdenkampe** [comment]
This looks quite good now. Thanks for also addressing many of the other time-axis styling suggestions that I mentioned in https://github.com/ODM2/ODM2DataSharingPortal/issues/236#issuecomment-412143248. 

Its nice to see TSA functional again! I had largely given up on it this summer.

**Comment by horsburgh** [comment]
This is done. I'm adding the "tested" label.
