### ISSUE TITLE
time series analyst tab in upper left not working

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#295]
![image](https://user-images.githubusercontent.com/39309124/46040991-badbb100-c0df-11e8-8525-47b344f0081b.png)

![image](https://user-images.githubusercontent.com/39309124/46041105-0c843b80-c0e0-11e8-96db-a53a95adb173.png)

**Comment by jcaraballo17** [comment]
This is fixed and will be included in the next release. 
Closing.

**Comment by aufdenkampe** [comment]
@dbressler75, thanks for creating this issue. I hadn't noticed that this wasn't working!
