### ISSUE TITLE
csv upload does not work on firefox

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#300]
Clicking the paperclip leads to a django error:

![image](https://user-images.githubusercontent.com/5374350/46815896-d4206680-cd49-11e8-97b8-f4b2ef391751.png)

**Comment by jcaraballo17** [comment]
Sounds like the file is not being sent.
@Maurier can you take a look at this?

**Comment by Maurier** [comment]
@jcaraballo17 Sure

**Comment by SRGDamia1** [comment]
No "browse" window every appears to allow you to select the file to upload.

**Comment by Maurier** [comment]
This has been fixed and will show up on our next deployment

**Comment by horsburgh** [comment]
I tested this with a file to add data to a new site. I tested first in chrome and the upload was successful. I also tested in Firefox and I am not getting the Django error shown above. I get the file browser window that allows me to select a file for upload. I'm going to add the "tested" label to this one.

**Comment by SRGDamia1** [comment]
Works for me.
