### ISSUE TITLE
Add free text search for "browse sites"

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#302]
Searching over all metadata for each site.

**Comment by Maurier** [comment]
@aufdenkampe This is the metadata associated with a site. Please check the items you would like in the free search.

- [ ] Deployment By
- [ ] Organization
- [ ] Deployment Date
- [ ] Latitude	
- [ ] Longitude	
- [ ] Elevation (m)	
- [ ] Elevation Datum	
- [ ] Site Type
- [ ] Stream Name
- [ ] Major Watershed
- [ ] Sub Basin
- [ ] Closest Town
- [ ] Notes

**Comment by aufdenkampe** [comment]
@Maurier, I just checked off fields in the list. The short answer is that all the text fields would be helpful for search. Thanks!

**Comment by horsburgh** [comment]
This seems to be working for me on the sandbox. It's cool that it zooms me in to the sites that match the search criteria and turns off sites that do not. I'm adding the "tested" label to this one.
