### ISSUE TITLE
Allow POST of data, even when one variable UUID is blank or wrong

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#303]
Presently, if any UUID is wrong, entire POST fails, even if multiple variable UUIDs are correct.

Desired behavior: If TOKEN and Sampling Feature UUID are correct, POST data for any correct variable UUIDs, and ignore any variables that have an incorrect or *missing* UUID.

This feature would be very helpful for troubleshooting radio connections and sketches.

**Comment by jcaraballo17** [comment]
> Presently, if any UUID is wrong, entire POST fails, even if multiple variable UUIDs are correct.

@aufdenkampe Can you give an example of a request where this is the case? I made this change in the web service about two years ago, so probably the request is failing for another reason. I just tested this on both the sandbox and production servers, and the web service skips any missing or wrong UUID.

**Comment by aufdenkampe** [comment]
A dummy UUID in the correct format allows the POST request to complete, such as:
-  "12345678-abcd-1234-efgh-1234567890ab" 

However, these following all cause 401 server errors:
- "12345678-abcd-1234-efgh-1234567890ab ", with an extra space after a correct UUID.
- "a"
- ""

The extra space happens very commonly, yet it is hard to find if the entire POST fails. It would be much more helpful to pass all the data with the correct UUIDs, then one could easily see which Variable/UUID has a bug.

A blank or single character entry would be very helpful too, to make it easy for a user to save on their cell phone data plan by not sending the 32-character UUID for variables that they really only want logged to the SD card. There are other ways to log a shorter list of variables to the Portal than to the SD card, but they are much more complicated to implement. It would be very nice to have a simpler and nearly-as-effective alternative.

@fisherba might have other examples.

**Comment by horsburgh** [comment]
@aufdenkampe - It seems like the most logical place to solve these issues is in the datalogger code. The web service for posting data will respond to whatever requests it gets. If you don't want to post data and you want to save on your cellular data plan, why send the POST request in the first place? Why not just log to the SD card and not send the POST requests? Could the Arduino code be configured to allow users to choose which variables get posted to the portal (i.e., which POST requests actually get sent)?

I understand that people may make mistakes when they put the GUIDs in their code. Stripping off trailing spaces is something that @jcaraballo17 should be able to do pretty simply, and he can also probably handle the other two cases, but people will still be sending POST request that will use data on their cellular plan for variables that won't get logged in the portal.

**Comment by aufdenkampe** [comment]
@horsburgh, I think you might have misunderstood the intent of this issue. As stated in the issue description:

> Desired behavior: If TOKEN and Sampling Feature UUID are correct, POST data for any correct variable UUIDs, and ignore any variables that have an incorrect or missing UUID.

My intent is to have the Portal accept all variables with a good UUID, even if it rejects one of them with a bad UUID. 

I'm not asking for any grace for a bad UUID; I don't want the Portal stripping trailing spaces. If a UUID is bad, then the Portal should not accept the value connected with the UUID. However, the Portal should accept all values for that request that do have a valid UUID.

**Comment by horsburgh** [comment]
@aufdenkampe - sorry about the confusion. By "handling the other two cases" I meant that instead of getting a 401 server error like you are getting now, we would make sure that the service skips (without errors) any requests with bad UUIDs (which is what it should be doing now anyway). But, sending POST requests with empty UUIDs or single character UUIDs will still chew up data (albeit at a potentially slower rate given that the UUIDs are omitted).

**Comment by aufdenkampe** [comment]
@horsburgh, no worries. It sounds like we're on the same page.

**Comment by SRGDamia1** [comment]
I think there is a json parse error going out when the parsing has a problem.  I think it's even saying the character position of the error.

@aufdenkampe - from the perspective of saving cellular data, we actually would want the server to say as little as possible back after the post request.  Everything the server says back after a post costs you data.  An empty page with no headers but the http status code would be ideal.  UDP would be even better so the logger could just fire and forget.  All the testing to make sure your logger is sending out the correct json should happen way before the logger is put out in the wild.

**Comment by jcaraballo17** [comment]
@aufdenkampe I've been testing these examples you posted, and as I expected all of them work just fine.
The web service doesn't try to insert whatever it finds in the post request, it loops through the list of results associated with the sampling feature and tries to find data for those results in the request.

Would it be possible for you or @fisherba to provide one of the POST requests that fail? I can think of a couple of reasons the requests would fail (including a json parse error like @SRGDamia1 mentioned,) but I'll have to look at an actual request that fails to identify the problem.

**Comment by aufdenkampe** [comment]
@jcaraballo17, I'll see if I can reproduce this, and if so, I'll get you that specific info.

**Comment by jcaraballo17** [comment]
@aufdenkampe Thanks, that would help a lot.

**Comment by aufdenkampe** [comment]
Here's an example of a POST that fails because of a blank UUID (""), this time with a 504 Gateway Timeout error.

```.json
Sending data to data.envirodiy.org
POST /api/data-stream/  HTTP/1.1
Host: data.envirodiy.org

TOKEN: e9bef9bc-0364-48d7-bafe-ac9267b9b275
Content-Length: 449
Content-Type: application/json

{"sampling_feature":"8035a3ef-b6e1-482d-8b40-5cf1968cf344","timestamp":"2019-04-30T21:28:00-06:00","decef2ab-b9ae-40eb-bba0-189050882c4e":593,"954bfb6f-eee5-4822-b93c-401e69f277cf":21.7,
"a01f77e8-b078-40c4-bd3a-ae41cdad7d60":-5.09,"7b04c1ef-1b53-4031-b7f0-23fca0a8b793":21.5,"13eb37ad-85ae-49ec-a89a-1670cd6330e6":-4.7,"288d245b-664b-4157-a02d-ad26ae2e4f2c":4.791,"1234567
8-abcd-1234-efgh-1234567890ab":-93,"":32}

-- Response Code --
504
------------------------------------------
```

**Comment by ptomasula** [comment]
@aufdenkampe, I believe this issue describes the current behavior implemented on production. My testing showed that I received a 201 response when my POST request included the correct token, sampling feature UUID, and one valid result UUID. Let me know if observe different behavior.
