### ISSUE TITLE
Fix "View Token UUID List" button to list Sensor Variables.

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#305]
The button shows the UUIDs, but no longer lists the sensor variables that each UUID is associated with. This is very valuable for proofing deployed code.

**Comment by horsburgh** [comment]
I think this looks good on the sandbox. Variable and sensor information are now shown next to each UUID in a comment. Adding the "tested" label.

**Comment by aufdenkampe** [comment]
Yes, that looks good. Thanks for that fix.
