### ISSUE TITLE
Use Pandas for CSV upload and download functions

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#312]
Pandas library, https://pandas.pydata.org/, makes reading, writing data tables in/out of CSV formats a breeze because of fantastic auto-parsing capabilities, especially for date time info. Also, Pandas is EXCEPTIONALLY easy and fast at merging time series into a combined data table.

Using Pandas with thus fix the bug described in https://github.com/ODM2/ODM2DataSharingPortal/issues/304#issuecomment-429935601. It will also facilitate solutions for issues described in https://github.com/ODM2/ODM2DataSharingPortal/issues/12#issuecomment-413281393, https://github.com/ODM2/ODM2DataSharingPortal/issues/294#issuecomment-429695024, #296, #311, and potentially #300.

**Comment by horsburgh** [comment]
Our plan for the next release is to push a fix for the CSV download. Rearchitecting to use Pandas for upload and download is something we can look at next. I'm going to move this issue to the next release.

**Comment by aufdenkampe** [comment]
@ptomasula began using Pandas and its wrappers around [SQLAlchemy](https://www.sqlalchemy.org) (i.e. `pd.read_sql()`) to fetch time series data, in this work:
- https://github.com/ODM2/ODM2DataSharingPortal/pull/506
- commit 7b9bc5d added the dependency

**Comment by aufdenkampe** [comment]
@ptomasula added pandas to this quick fix (Commit https://github.com/ODM2/ODM2DataSharingPortal/pull/526/commits/47047b1bb0f376fdf30924fb44fdd904c604b2f0 to Resotre CSV Upload Function), to better support datetime formats, as Django `parse_datetime` rejects some pretty reasonably formatted date strings. 

More complete use of pandas would likely improve performance substantially, but that would require a complete rewrite of the method, so we're keeping this issue open and moving it to a future milestone.

**Comment by ptomasula** [comment]
Pull Request #651 refactored the CSV download endpoint to utilize pandas resulting in about 25% decrease in processing time. Still leaving this issue open though because we have not refactored the csv upload endpoint.

**Comment by aufdenkampe** [comment]
Completed with v0.15
