### ISSUE TITLE
Fix branding to Monitor My Watershed

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#313]
As @HeatherBrooks and I described in https://github.com/ODM2/ODM2DataSharingPortal/issues/237 and #287, we are modifying the branding to *Monitor My Watershed* at https://MonitorMyWatershed.org.

See the [WikiWatershed Branding Identity](https://drive.google.com/drive/folders/1MiPT4DBrtUaFxUiTf3CRYNVBl0X_pj0U?usp=sharing) for new logos.  See the new branding text for the "Explore Our Companion Projects" section of the home page at the bottom of the [Tweaks to Leaf Pack Experiment Data Entry Form](https://docs.google.com/document/d/1Cx1--ngice9qP848oOUoRSghkkW--7VySifSoiZ-8r8/edit) Google Doc, as described in #287.

**Comment by horsburgh** [comment]
@Maurier - this all looks good to me on the sandbox except the fonts of the "Data Sharing Portal" text and the "How it works" text on the home page. There are other headers on other pages that need to be fixed too. It looks like some flavor of the Times font is being used, but it should be the Ubuntu font.

**Comment by HeatherBrooks** [comment]
Branding looks good with the exception of the Ubuntu fallback. A couple of text edits on the homepage:
"How it works" to "How It Works"
"The WikiWatershed Data Portal" to "Monitor My Watershed"

**Comment by horsburgh** [comment]
Fonts of headers look good now and the @HeatherBrooks tweaks are implemented. Adding the "tested" label to this one.

**Comment by HeatherBrooks** [comment]
Sorry, our Communications Manager caught a few more things on the homepage after I left work yesterday:
"water quality data" should be "water-quality data" (two occurrences)
"water monitoring data" should be "water-monitoring data"
WikiWatershed logo appears fuzzy because the image is 427 x 77 pixels and is being displayed at 503 x 91 pixels.
In the footer, "**EnviroDIY™** is presented by" should say "**Monitor My Watershed®** is presented by" and "fresh water through research, education, and **restoration**" should say "fresh water through research, education, and **watershed restoration**.

**Comment by horsburgh** [comment]
We'll hyphenate water quality and water monitoring if you want, but I don't think I've ever seen those terms hyphenated in any common scientific or other context.

**Comment by HeatherBrooks** [comment]
@darsott, this is your call. I brought it up because Stroud Center communications policy is to use AP style in our public communications. AP hyphenates compound modifiers as in those terms.

**Comment by horsburgh** [comment]
@Maurier - if you could make these changes really quickly I can add the tested label back to this one.

**Comment by Maurier** [comment]
Sure thing

**Comment by aufdenkampe** [comment]
Regarding @HeatherBrooks' https://github.com/ODM2/ODM2DataSharingPortal/issues/313#issuecomment-435062919 on hyphenating "water-quality monitoring", I tend to agree with Jeff that I have never seen it written that way. I understand using AP style is important, but perhaps not for all the things. For example, I just learned last month that AP would use Mr. Arscott, Mr. Horsburgh and Mr. Aufdenkampe rather than addressing us with 'Dr."

**Comment by horsburgh** [comment]
The changes suggested by @HeatherBrooks have been implemented on the sandbox. I'm going to add the "tested" label back to this one.

**Comment by darscott** [comment]
I don't think I've come across any common usage of the hyphen in this
phrase "Water quality monitoring". I'm fine if we break the AP rules here.
Dave

___________________________________________________________________________________

Dave B. Arscott, Ph.D. - Executive Director, Research Scientist

Stroud Water Research Center -  Avondale, PA 19311 USA
Phone: (office) 610-268-2153 x 278, (mobile) 484-885-5225

Advancing knowledge and stewardship of fresh water through global research,
education, and restoration
_____________________________________________________________________________________



*Making a gift/pledge in honor or memory of someone special is a
particularly meaningful way to aid the mission of the Stroud Water Research
Center Special Gifts program.  In addition, please consider a challenge
match grant by contacting David Reinfeld to establish match
parameters. Make an online donation now
<https://stroudcenter.org/make-special-gift> or call 610-268-2153, ext.
314, with any questions about contributing a gift or a multi-year
pledge. Established Challenge Match grants:*

   - *$1 Million Challenge Match Grant generously sponsored by Rod and
   Alice Moorhead to benefit the Bernard W. Sweeney, Ph.D., Executive
   Director’s Fund:* This challenge grant will provide seed funding to
   ensure strategic initiatives that are vital for Stroud Water Research
   Center’s mission. Your charitable donation will be matched
   dollar-for-dollar thanks to the generosity of Rod and Alice. Help us meet
   and exceed the $1,000,000 goal!


   - *$50,000 Challenge Match Grant generously sponsored by Spurlino Family
   Foundation to benefit the Scientific Research Fund.* Your charitable
   donation will be matched dollar-for-dollar thanks to the generosity of the
   Spurlino Family Foundation. Help us meet and exceed the fund goal!
