### ISSUE TITLE
500 Server Error on Admin Page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#314]
I cannot modify a variable or add a sensor output.  I'm getting a 500 server error.

**Comment by jcaraballo17** [comment]
This issue came up in #292. It's fixed, but it has to go through the sandbox and will be up in the next deployment.

**Comment by SRGDamia1** [comment]
Broken again

**Comment by aufdenkampe** [comment]
@ptomasula, could you look into this bug?

I'm wondering if it is connected to our Django upgrades?

**Comment by aufdenkampe** [comment]
Closing this because it is a duplicate of:
- #577
