### ISSUE TITLE
Add dimensionless integer variable for housekeeping

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#315]
After the next release, which will fix #292, we will want to implement the following suggestion from @neilh10 via his email. Addressing #261 will make it possible to implement the second half of this suggestion.

> I'd like to suggest a dimensionless number/integer  - possibly under 
> Sensor Manufacturer=ALL, Sensor Model =Calculated  Measured Variable= 
> Dimensionless 
> 
> Workaround: For data.envirodiy.org  I can use any sensor to create a 
> display and mark it in the comments as to its true purpose. 
> 
> The reason is for housekeeping - its standard in the transfer of data to 
> have a sequence number.  This allows a very easy method to determine if 
> all the data has transferred correctly. 
> 
> An idea could be the ability to mark the sensor as housekeeping - so it 
> only appears to the owner, similar to the UUID keys. 
> 
> Reason: When visualizing data on graphs from a distributed database- its 
> difficult to detect data transfer losses.  Its much easier to visually 
> detect a number or group of numbers have been skipped than analyzing all 
> the time records. Its also easier to see if there was a "reset" or new 
> series if the the sequence number starts again.. 
> 
> For the latest Mayfly testing I'm planning on creating a 
> processor_stats.sensor that sends a sequence number with each message. 
> This will start at 0 on hard reset or logging file creation, and  
> transfer with each message. 
> 
> many thanks for all the work going into data.envirodiy.org  - its great 
> to see the web presentation and shows up very quick. My main purpose is 
> to work the Mayfly example and to use simple local data to visualize 
> that first.  I suspect there is some fine tuning going on, as I'm trying 
> to figure out some of the visualization mappings.

**Comment by SRGDamia1** [comment]
Can't you just do that quickly on the admin panel?

**Comment by SRGDamia1** [comment]
I think this has been done.

**Comment by aufdenkampe** [comment]
Yes! Thanks @SRGDamia1  for the housekeeping on this!

**Comment by neilh10** [comment]
Just wondering - is this available on https://data.envirodiy.org - I don't see anything if I go through "Add New Sensor"  - I tried 
Sensor Manufacturer=ALL, Sensor Model =Calculated Measured Variable= 

I'm actually looking to create sensors that show current taken by a large piece of equipment - a fisheries PIT Tag array.  The current can go to 8A.
I'm using Sensor INA219, with Current Measurements A

**Comment by SRGDamia1** [comment]
Right now I think it's assigned to a Mayfly
