### ISSUE TITLE
Change nginx to redirect to MonitorMyWatershed.org

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#316]
From my email:

> Heather set up the DNS so that all three of these URLs point to the same web server:
> 
> - data.envirodiy.org  
> - data.wikiwatershed.org  
> - monitormywatershed.org  
> 
> We want to support all three of these for at least another year or two or longer, to not leave anyone stranded, as Jeff suggested.
> 
> I think Dave's intent was that we would like anyone who uses data.envirodiy.org​ or data.wikiwatershed.org​ to get redirected/resolved to ​a website that has "monitormywatershed.org" in the web browser URL bar.

Response from @jcaraballo17:

> That can be done on the nginx configuration. The way it works now, it accepts all three domains as aliases. 
> I can change it so it's a redirect to monitormywatershed.org or www.monitormywatershed.org instead.
>

**Comment by aufdenkampe** [comment]
We'll want to do this after release 0.9.5, to first let users get used to the new branding.

**Comment by jcaraballo17** [comment]
@aufdenkampe @horsburgh https://www.monitormywatershed.org and https://www.monitormywatershed.com have been live for about a week now. All the domain names work independently from each other, so if that's the desired behavior for this issue then we can close it.

**Comment by horsburgh** [comment]
@jcaraballo17 - I think they wanted https://data.envirodiy.org and https://data.wikiwatershed.org to be redirected to https://monitormywatershed.org so that if you enter one of those other domains into the browser you end up at https://monitormywatershed.org (which would be shown as the URL in the browser). 

@aufdenkampe - all three domains are active and point to the exact same content so the look and the feel will be the same regardless of which domain is entered. If we need to do the formal redirect we can do it.

**Comment by aufdenkampe** [comment]
This is the behavior we want for now.

As mentioned by @horsburgh in https://github.com/ODM2/ODM2DataSharingPortal/issues/316#issuecomment-434531758, in the future (not yet sure if for next release), we'll want to redirect all traffic to https://monitormywatershed.org.

**Comment by aufdenkampe** [comment]
UPDATE: For the January switch to LimnoTech production servers, @htaolimno redirected all traffic to https://monitormywatershed.org. Unfortunately, that resulted in immediate failures to the HTTP POST requests with new data from monitoring stations, which have been primarily programmed to send to http://data.envirodiy.org.

@jcaraballo17 responded that "I think the problem has to do with the server returning a 301 status code and the stations not sending another request to the actual url."

Reverting the redirect immediately fixed the problem. 
We'll need to test alternate approaches to this on staging servers.

**Comment by jcaraballo17** [comment]
@aufdenkampe I have an idea. 
If we redirect all traffic to https://monitormywatershed.org ***except*** http://monitormywatershed.org/api/data-stream, then all web traffic would normally be redirected to the right domain name (monitormywatershed.org) and protocol (https), but the streaming web service would receive request from any domain and protocol, so it wouldn't have any issues.

**Comment by aufdenkampe** [comment]
@jcaraballo17, I really like that idea! 

Are you thinking that you would like to implement that on staging in the next few days, or that we should do it sometime in the future?

**Comment by horsburgh** [comment]
@aufdenkampe - best to let the Limnotech team implement this one.

**Comment by aufdenkampe** [comment]
Sounds good!

**Comment by aufdenkampe** [comment]
@ptomasula reconfigured Nginx settings on staging, as described here: https://github.com/ODM2/ODM2DataSharingPortal/issues/522#issuecomment-973268492

This is all working now.
