### ISSUE TITLE
Post terms of use, DMCA, privacy, and cookie policies

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#324]
Stroud has developed policies for terms of use, DMCA, privacy, and cookies. These need to get added to the site. Here are links to the content:

Terms of Use: https://docs.google.com/document/d/1YGVdm_f8ZHlUbVGgelcjW3vaKkEf6KqlEIjbUJ8kpHU/edit?usp=sharing

DMCA: https://docs.google.com/document/d/1i8yMD_cuJpuNcOlHKWhM1brbPglQpA_fahhUTPll0_Y/edit?usp=sharing

Privacy: https://docs.google.com/document/d/1uh5q4U9taAv91Kyli1jI3hu0hDtLmq-a2-FuaytrFzs/edit?usp=sharing

Cookies: https://docs.google.com/document/d/1h5Vz39cRHNq33WN9c05Is9ysDv7j408bnIB9RPI7zl8/edit?usp=sharing

If the site is not using any cookies, we probably don't need to post the Cookie policy.  Each of these policy documents should be added to the site as a separate page with the text that is in the Google Doc. Links to them should be added to the Footer under the "Site License" section. Something like the following, where each item under the POLICIES header is a link to the correct page:

POLICIES
Terms of Use 
Privacy
Cookies (only included if we are actually using cookies)

The DMCA policy can be left out of the footer list and can be linked only in the Terms of Use policy document (see item 7 in that document). 

Finally, we should include acceptance of the terms of use in the checkbox text on the Register page (where users create accounts). That text should look like the following, and the text "Terms of Use" should be linked to the terms of use document:

>I agree to the Monitor My Watershed Terms of Use and that all data I post to this site will be made public according to the Creative Commons Attribution Share Alike License (CC-By-SA).

**Comment by jcaraballo17** [comment]
This is done already, moving to Milestone 0.9.5.

**Comment by horsburgh** [comment]
@Maurier - this all looks good on the sandbox. Based on @HeatherBrooks' comment I think we should combine this into one statement and checkbox. I think you can just remove the second checkbox and text.

**Comment by horsburgh** [comment]
The check box and text look good now. Adding the "tested" label.

**Comment by HeatherBrooks** [comment]
@Maurier It turns out that a half dozen or more cookies (Cloudflare, Google Analytics, session ID, Cross-Site Request Forgery token) are in use so we do need the [Cookie Policy](https://docs.google.com/document/d/1h5Vz39cRHNq33WN9c05Is9ysDv7j408bnIB9RPI7zl8/edit?usp=sharing) posted after all. Please add it to the Policy section in the footer and link it into the last sentence in the Cookies section of the Privacy Policy ("For more information, please see our Cookie Policy").

**Comment by HeatherBrooks** [comment]
Checked on staging; it all looks good to me.
