### ISSUE TITLE
Show height and notes fields in TSA

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#326]
They aren't there now.  For sites with repeats of the same sensor, it's currently impossible to tell which is which.

**Comment by SRGDamia1** [comment]
It would be nice to also be able to see the GUID.  I'm afraid that would be complicated, though, since we want it hidden for non-owners.

**Comment by horsburgh** [comment]
@SRGDamia1 - can you give us an example of where you are not seeing the height, notes, and GUID? On the sandbox, here is an example of what I am seeing for one of my sites:

Site UUID and Registration token:

![image](https://user-images.githubusercontent.com/3485902/47860538-5b478400-ddb6-11e8-925e-4faf508dfb25.png)

Height, notes, and UUID for time series - one has height and notes and one does not:

![image](https://user-images.githubusercontent.com/3485902/47860584-7914e900-ddb6-11e8-9a9e-2c2cd78b3de1.png)

**Comment by horsburgh** [comment]
I guess I should read the full label of the issue. You are referring to TSA - sorry about that.

The TSA uses a catalog database that is based almost entirely on ODM 1.1 (given that the bulk of the code existed prior to this project).  A time series in ODM 1.1. is defined as the unique combination of site, variable, method, source, and qualitycontrollevel. The offset is not one of the things that distinguishes a time series in ODM 1.1. This is a deficiency in the design of ODM 1.1 that carried into TSA. In most instances, users of ODM and TSA have distinguished vertical offsets in their method descriptions to get around this limitation. We might be able to do something similar by concatenating some information about the offset/height into the method information that gets written to the catalog database.

I'll have to talk to @jcaraballo17 to see what we can do with this one. We do not have authentication in TSA, and so displaying content based on whether a user is logged in or not is not a capability of the TSA.

**Comment by SRGDamia1** [comment]
Yeah, I figured the GUID/permissions probably wouldn't be possible.  That's ok, it would only be to help tell series apart, so the notes and height should cover it.

**Comment by aufdenkampe** [comment]
This would be a nice feature, especially given that we'll probably be using TSA for some time.

However, I've long wondered how much investment we should continue to give to TSA, given that it is based on ODM1.1?

@horsburgh & @jcaraballo17 , if the fix is relatively straightforward, it might be worth considering, but I understand if that might be too challenging without a major refactor.

**Comment by jcaraballo17** [comment]
To add the Height and Notes to the TSA I would have to extend the Catalog database to add those new fields.
Would the UUID work for telling the series apart? Adding those two fields wouldn't be a lot of work, but we already have the UUIDs in the catalog.

**Comment by horsburgh** [comment]
@jcaraballo17 - each time series should have a unique UUID in the ODM2 database because each one is a unique Result. So, I *think* this should just be a matter of moving the height and notes information to the catalog.

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 

Our new TSV displays the height, but not the notes. We're open to ideas on how to do that. 
Closing this for now. Let's create a new issue if this is necessary.
