### ISSUE TITLE
Question:  What is the "series" number in TSA

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#327]
I'm guessing it's the primary key in the table.  If that's all it is, it probably shouldn't be displayed as the first column by default.

**Comment by horsburgh** [comment]
I think it's just a unique identifier for the series. @jcaraballo17 can confirm.

**Comment by jcaraballo17** [comment]
@SRGDamia1 That's exactly what it is.

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 
We think our new TSV addresses this issue.
