### ISSUE TITLE
CSV Download Files Created by TSA Need to be Fixed

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#328]
Here's some things I observed in looking at the CSV files generated by the TSA. I tested this by looking at the data for this site: https://envirodiysandbox.usu.edu/sites/USU-LR-UWRL/ 

Under Site Information:
* [ ] The value of "IsActive" is set to 1 for the site I tested. I loaded some old data to this site from 10 years ago. There are no recent data for this site, so what does the 1 mean? I think this should be removed and the user can determine if the site is active using the functionality of the data sharing portal (and by looking at the data in the file to see how recent it is).
* [ ] Elevation and VerticalDatum are reported as "Undefined" even though there is data for them in the data sharing portal. These should be populated.
* [ ] State and County should be removed (because we don't have data for them) and the additional attributes that are now part of the data portal should get added: Stream Name, Major Watershed, Sub Basin, Closest Town, and Notes.

Under Variable Information:
* [ ] The variable creation process in the data sharing portal does not record a NoDataValue or TimeSupport. These should be removed from the Variable Information in the header because we don't record this information.

Under Method Information:
* [ ] MethodDescription is "null". There should be a value here, even if it is "Unknown". You could create a string by saying something like "Data collected using an "X" sensor." where "X" is the text name of the sensor from the Data Sharing Portal.
* [ ] MethodLink is listing the SiteCode for some reason. For this field we could use the Equipment Model Link from the Data Sharing Portal where that value exists. If there is no valid URL for the equipment model being used, this field should be null.

Under Series Information:
* [ ] The BeginDateTime doesn't make sense. For the file I downloaded, it has a BeginDateTime of 2018-06-08T22:29:12, but the first DataValue in the file is 2008-09-29 07:00:00.
* [ ] EndDateTime is "null". This should be the date/time of the last observation in the file.
* [ ] "DateLastUpdated" is redundant with "EndDateTime" and should be removed.

Under Source Information:
* [ ] Source Description is null. We only collect an organization name when a user signs up, so we should remove Source Description from the header as it will always be blank.

Under the DataValues table:
* [ ] The DateTime value is incorrect. The value listed is the UTCDateTime, but it is in the DateTime column instead of the DateTimeUTC column, which is blank. 
* [ ] We should remove the CensorCode, and QualifierCode because these columns will never include any values for the EnviroDIY data.

**Comment by horsburgh** [comment]
After looking at the CSV files generated by the two systems, I'm going to close this issue in favor of creating a new issue that defines one structure for individual time series download as CSV from both the Data Sharing Portal and the TSA.

**Comment by aufdenkampe** [comment]
Thanks for outlining these issues. Connected to new issue #329.
