### ISSUE TITLE
Create Consistent CSV File Download from Portal and TSA for Individual time series

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#329]
I'm labeling this issue as both bug and enhancement because the files need to be reconciled (enhancement) and also cleaned up too remove errors (bug).

Here's is an example for what the format of the CSV download file should be for individual time series. This file format should be consistent across the data sharing portal and the TSA. Where stuff needs to be filled in, I've included it in "<>" to indicate that it is missing now but needs to be created based on information we have already. I've removed a bunch of stuff that exists in ODM, but that we aren't collecting as part of the data entry forms in the data sharing portal so that we don't have a bunch of fields where we are just reporting "none". I think the file naming convention we are using now is fine.

**NOTE: I've uploaded the file with a ".txt" extension so it will upload to GitHub, but the files should be written with a ".csv" extension.**

[Example_Data_File_Individual_Time_Series.txt](https://github.com/ODM2/ODM2DataSharingPortal/files/2542816/Example_Data_File_Individual_Time_Series.txt)

**Comment by aufdenkampe** [comment]
This looks good to me. Thanks for setting up this template with a nice header and consistent metadata.

**Comment by jcaraballo17** [comment]
Issues solved in #396.

**Comment by aufdenkampe** [comment]
I just did a comparison of different files for https://staging.monitormywatershed.org/sites/WCD696/, and they look very consistent to me.

There are very minor differences in the header and columns, but these will not affect how these files are parsed.
