### ISSUE TITLE
Modify "register" links on home page

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#333]
From the home page, the link to register a site under the EnviroDIY instructions should link to the following URL:

https://monitormywatershed.org/sites/register/

It is currently linking to the login screen even if you are already logged in. The default should be to link to the site registration page. If you're not logged in it should go the login page then login and hit the site registration page.

**Comment by HeatherBrooks** [comment]
Tested on staging; this is not fixed. According to Jeff's original comment, the link should go to the [site registration page](https://monitormywatershed.org/sites/register/) (with a stop on the login page if user is not logged in). The link is instead going to the [user registration page](https://staging.monitormywatershed.org/register/).

**Comment by aufdenkampe** [comment]
Thanks for noticing that. We'll correct it.

**Comment by htaolimno** [comment]
An improvement to the code based on checking user's authentication status has been pushed to branch.

**Comment by aufdenkampe** [comment]
Hua, that is awesome. Is it ready to be tested on staging?

Sent from my iPhone

On Aug 1, 2019, at 8:34 PM, htaolimno <notifications@github.com<mailto:notifications@github.com>> wrote:


An improvement to the code based on checking user's authentication status has been pushed to branch.

-

**Comment by htaolimno** [comment]
looks like it works as intended.
