### ISSUE TITLE
Update page titles

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#335]
I think a couple of title tags still need to be updated to reflect the branding change. 
Homepage: from "Data Sharing Portal" to "Monitor My Watershed"
Register page: from "Join the EnviroDIY Data Portal" to "Join Monitor My Watershed"

**Comment by HeatherBrooks** [comment]
The page titles appear to have reverted to the earlier text. This issue is no  longer fixed.

**Comment by aufdenkampe** [comment]
Yikes! @jcaraballo17, what happened to this fix? It seems to have disappeared on https://staging.monitormywatershed.org.

**Comment by jcaraballo17** [comment]
@HeatherBrooks @aufdenkampe From looking at the commits and the [staging server](https://staging.data.envirodiy.org/), the title tags were edited as suggested.

![image](https://user-images.githubusercontent.com/4700505/52310016-490e5080-2978-11e9-8573-e23459cb8e2f.png)

**Comment by HeatherBrooks** [comment]
Checked on staging; titles have been updated.
