### ISSUE TITLE
Leaf pack experiment data form: macroinvertebrates missing Latin names

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#336]
The sandbox shows the Latin names but the production site does not. Correct names are listed in this [Google Doc](https://docs.google.com/spreadsheets/d/11lJehfHBXBmD5dKPukVJnQZWqVgYyIEGvh7NLwF2n8M/edit?usp=sharing).

Sandbox
![macros-sandbox](https://user-images.githubusercontent.com/9368629/48151458-58093800-e28f-11e8-9646-d24a6d911c52.JPG)
Production
![macros-production](https://user-images.githubusercontent.com/9368629/48151584-a0285a80-e28f-11e8-9e21-4934472edf80.JPG)

**Comment by HeatherBrooks** [comment]
Oh, and the production site is missing the "super categories," e.g. "All crustaceans (Crustacea)"

**Comment by Maurier** [comment]
@horsburgh I sent a message to @darksinge about this. I remember we set a script to take care of this.

**Comment by HeatherBrooks** [comment]
Hi @Maurier, any progress on this issue? We'd like to have some Leaf Pack Network users try entering data soon but we can't do that until the macroinvertebrate super categories and Latin names are reinstated. Thanks.

**Comment by jcaraballo17** [comment]
@HeatherBrooks the Latin names and macroinvertebrate categories should be back now.

**Comment by HeatherBrooks** [comment]
@jcaraballo17 They're mostly back but it looks like we're still missing the crustaceans:

All crustaceans (Crustacea)
Scuds (Amphipoda)
Aquatic sowbugs (Isopoda)
Crayfish (Decapoda)

**Comment by jcaraballo17** [comment]
@HeatherBrooks Can you double check it? I'm seeing those right now on the page.
![image](https://user-images.githubusercontent.com/4700505/49608246-85203780-f96e-11e8-835b-c5227b28da4d.png)

**Comment by horsburgh** [comment]
Maybe clearing browser cache is needed?

**Comment by HeatherBrooks** [comment]
Sorry, I should have been more specific; I was seeing the problem on the page displaying the leaf pack data, not on the data entry page, but everything's there in a new incognito window. Thanks!
