### ISSUE TITLE
TSA shows Decagon_CTD-10_Depth for most variables

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#363]
New-ish sites are showing repeated series of Decagon_CTD-10_Depth instead of multiple other variables.

Sites I see it on:
BCPC1S
BCPC2S
BRMuseum
MSSR2S
NHLR1S
PUSR1S
PUSR2S
WCC178

The spark lines look fine.

PLEASE FIX ASAP!
![image](https://user-images.githubusercontent.com/5374350/50858728-3eec3880-135f-11e9-965e-f8d84f7074fc.png)

**Comment by jcaraballo17** [comment]
Closing. Not using the script that caused this anymore.

**Comment by aufdenkampe** [comment]
Related to the bug described in #284. Look to those comments for pointers to the new script.
