### ISSUE TITLE
Fix repeat UserNames in drop down when Admin is Editing a site.

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#365]
From my message in Slack:

> Also, I noticed today that the "Deployment by..." dropdown list shows that for many if not most user names there are multiple repeat entries. Often one record is affiliated with an organization and the other records (up to four replicates) for that user name are not affiliated. Is this an issue with the UI or with the underlying data? How did this happen and how do we fix it?

**Comment by SRGDamia1** [comment]
I still see Kenny's name 4 times in the list.

**Comment by jcaraballo17** [comment]
@SRGDamia1 Checked the users list, and Kenny had 4 different users registered to his name. Deleted 3 of them in both the staging and production databases. Let me know in a new issue if there's another person that's repeated several times.

**Comment by aufdenkampe** [comment]
I just checked and I see a few repeated names, but most are associated with different organizations. I'm suspecting that the remainder are from different accounts that might have bee recreated by accident.

Closing this issue.
