### ISSUE TITLE
Unable to edit existing sensors in admin panel

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#366]
After clicking "save" I get an 500 server error.

**Comment by aufdenkampe** [comment]
Thanks for finding this bug. 

It seems like a permissions issue. @steveskrip, @htao and I will look and ping @jcaraballo17 for a quick suggestion.

**Comment by aufdenkampe** [comment]
@htaolimno, I think this is related to errors in the PostgreSQL/ODM2 database, where the sensor information is stored in the equipment tables.

For entity relation diagrams for the ODM2 Equipment, see http://odm2.github.io/ODM2/schemas/ODM2_Current/diagrams/ODM2Equipment.html

**Comment by aufdenkampe** [comment]
This was "hot fixed" on the production servers with the fix for #342 (and https://github.com/ODM2/ODM2DataSharingPortal/commit/298bc70093bf90773708e7f221fae8db4baebf35). 

Note that to see the fix, a user was/is required to do a hard "Empty Caches" command in Safari or other web browser.
