### ISSUE TITLE
Registration page says Organization is optional, but fails without it

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#372]
We're getting ready to push Leaf Pack Network users to the data portal so I thought I should step through the registration process. On the Sign Up page, Organization is marked as optional but when I didn't provide one before submitting the form I was taken to a screen that indicates Organization is required? When I chose an Organization and tried again my registration was successful.

@aufdenkampe, can LimnoTech team investigate soon or should we hold off on launching this to LPN?

![image](https://user-images.githubusercontent.com/9368629/53191045-d5577f00-35d8-11e9-8d19-7202206ec59c.png)

**Comment by aufdenkampe** [comment]
Thanks for finding this bug. @steveskrip and I will look to see if this is an easy fix or not. Perhaps @jcaraballo17 has a quick suggestion.

Regardless, even if it is and we fix it quickly on staging, it will be a good bit longer before staging gets tested and pushed to production.

**Comment by HeatherBrooks** [comment]
Just want to confirm that this will be fixed in the next release? A user from [Great Lakes Data Watershed](https://gldw.org/) just sent a help request about this issue through the WikiWatershed contact form. He tried to register without choosing an organization and got the error message I posted when I opened this issue.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, that is our plan, but we haven't yet gotten to this one.

**Comment by htaolimno** [comment]
I made changes to the branch to allow blank organization name when new user signs up.

**Comment by htaolimno** [comment]
I tested the registration without entering an organization name and no error occurred.
