### ISSUE TITLE
Upgrade Django to version 1.11.20 LTS

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#380]
There are security vulnerabilities in our existing Django v1.11.15. See: 
https://github.com/ODM2/ODM2DataSharingPortal/network/alert/requirements.txt/django/open

Suggested remediation: Upgrade django to version 1.11.19 or later.

Django 1.11.20 (LTS) is the [latest version to support Python 2.7](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django), and support ends in 2020.

Ideally we would upgrade to the [latest Django v2.2](https://www.djangoproject.com/download/), but that would require a stack upgrade to Python 3.

There hasn't been a Django 2.x Long Term Release (LTS) yet, but upgrading to v2.2 is clearly the path to longer term support.

**Comment by aufdenkampe** [comment]
Because of our integrations with WOFpy & WebTSA, we probably can't make the jump right away to Django 2 and therefore Python 3. See #381.

I recommend upgrading to Django 1.11.20 (LTS) for release 0.11.

**Comment by SRGDamia1** [comment]
Yes, please!

**Comment by aufdenkampe** [comment]
Completed on staging.The previous version it was running was 1.11.18, and the update is pretty trivial to what we're doing.

From Django release notes:
>Django 1.11.20 fixes a packaging error in 1.11.19.
>Django 1.11.19 fixes a security issue in 1.11.18.

At the moment, however, staging does not yet reflect the work completed in the `development` branch.
