### ISSUE TITLE
Color of map symbols does not correctly align with real data updated time

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#383]
It sort-of kind-of does for some sites, but not for all of them.

ie:
PUHR1S still is green on the map even though it hasn’t had data in months
PUPP2S is grey even though it has data and is up to date

I'm sure it's related to the issues with WOFpy not working/TSA indices being off/influx integration.

**Comment by aufdenkampe** [comment]
@SRGDamia1, now that TSA and Sparkles are working for stations that were registered before January (see https://github.com/ODM2/ODM2DataSharingPortal/issues/378#issuecomment-493220171 & #390), can you let us know if this is still an issue for sites those sites that were registered before Jan?

Knowing that would help us figure out how to fix. Thanks.

**Comment by SRGDamia1** [comment]
I'm not sure how well I can test this on staging because none of the sites are live.

**Comment by jcaraballo17** [comment]
Both sites mentioned seem to have the correct color for their data last update time. This was probably an issue when the InfluxDB instance was all messed up.

**Comment by aufdenkampe** [comment]
We'll do a final test with #419.

**Comment by aufdenkampe** [comment]
Confirmed in Preproduction Test in #419!

**Comment by SRGDamia1** [comment]
It seems that the "liveness" of the data for purposes of the coloring is based on the time of the last registered variable. 

Search for NHPK9S - it shows grey = no data from sensors but it actually has live data from several sensors - it's only a single added new variable that doesn't have data:

![image](https://user-images.githubusercontent.com/5374350/65281975-cc447700-db01-11e9-99e9-7d343943491b.png)

![image](https://user-images.githubusercontent.com/5374350/65281960-bf278800-db01-11e9-8647-09382a3975fe.png)

I think the color should be based on the single most recent value from *any* variable at that site.

**Comment by aufdenkampe** [comment]
Thanks for figuring out the details of this bug!

**Comment by SRGDamia1** [comment]
Interestingly, at that site, I started back-filling the missing turbidity data.  As soon as a single point was added to the turbidity, the site became green - even though that single turbidity point was from 2017.

Note:  I'm adding the data via post requests, not by uploading csv's.

**Comment by aufdenkampe** [comment]
Ah, so there are two fixes to make here:
1. look for actual date time of the data value, rather than the date time it was last updated.
2. look at the most recent date time for any variable at the station, not just the last one added.

**Comment by aufdenkampe** [comment]
@ptomasula, this might be related to the issue you are current fixing on staging.

**Comment by aufdenkampe** [comment]
This appears fixed, and it probably happened with #617 and related work in the v0.14 release.
