### ISSUE TITLE
Users being warned that site is unsafe due to expired SSL certificate

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#387]
User began reporting trouble on April 26: when attempting to access https://monitormywatershed.org she is warned that site is unsafe due to expired certificate. I just verified this is still happening. There is also a warning on the login page. @aufdenkampe, can someone at LimnoTech take a look?
![Screen Shot 2019-04-29 at 4 07 30 PM](https://user-images.githubusercontent.com/9368629/56966160-95f36480-6b2c-11e9-831d-e93ed9f73e51.png)
![login-warning](https://user-images.githubusercontent.com/9368629/56966169-97bd2800-6b2c-11e9-9e3b-ad6ed9903de7.JPG)

**Comment by aufdenkampe** [comment]
We've been aware of this and working on it. 
I think @tslawecki just fixed it, but with it unfortunately created bug #389, which we are now working on fixing.

**Comment by HeatherBrooks** [comment]
I'm still getting the security warning at https://data.envirodiy.org/, https://data.wikiwatershed.org/, and https://monitormywatershed.org.

**Comment by tslawecki** [comment]
This is not yet fixed, next step to try is to add a CAA record to DNS for www,monitormywatershed.org. 

I've got the certbot renewal error down to just (?) "CAA record for www.monitormywatershed.org prevents issuance". This apparently needs someone to check/update/add a CAA record per https://letsencrypt.org/docs/caa/. It looks pretty straightforward, but I'm not sure who owns the domain, which is apparently registered through namecheap … is this you, @HeatherBrooks?

**Comment by HeatherBrooks** [comment]
@tslawecki yes, I manage the domains. I will refer to my notes from when Hua had me set up CAA records in January. I'll let you know when it's in place.

**Comment by HeatherBrooks** [comment]
@tslawecki Has something changed with the SSL certificate? I put a CAA record in place for www.monitormywatershed.org in January. The propagation checker shows it's still working: [https://www.whatsmydns.net/#CAA/www.monitormywatershed.org](url). 
![monitor-dnsJPG](https://user-images.githubusercontent.com/9368629/57308521-86d45f80-70b4-11e9-97c8-7ccfc1b845ab.JPG)

**Comment by HeatherBrooks** [comment]
Just fixed a typo. The correction is propagating now.

**Comment by aufdenkampe** [comment]
Was the typo the likely problem?

**Comment by tslawecki** [comment]
AFAIK the cert is valid again now. I'm not happy about the process, but here is what I did:

1. Suddenly the CAA problem disappeared ... presumably thanks to @HeatherBrooks' action [two comments back](https://github.com/ODM2/ODM2DataSharingPortal/issues/387#issuecomment-490110546).

2. When running  `certbot renew` the error turned back into an inability to access the challenge files, preceded by warnings about conflicting server names.

3. After a bit of trial and error, I made "www.monitorywatershed.org" the only `server_name` in the `/etc/nginx/sites-enabled/data`, restarted nginx, and was able to successfully execute `certbot renew`.

4. I changed the server_name back to include our laundry list and re-restarted nginx, and things appear to be copacetic, except that monitormywatershed.com is not covered under the cert.

I'm thinking that the certificate is tied in some way to the domain www.monitormywatershed.org and for now that's just what we have to deal with even though it is a bit ugly. A little down the road we could perhaps open a ticket with Let's Encrypt and see if they have any suggestions.

Someone else please check and close ...

**Comment by aufdenkampe** [comment]
@tslawecki, thanks for the update, getting it to work, and for documenting how. 

While you were doing all that, did you notice an option to auto-renew? We want that. However, it sounds like it will fail the auto-renew process with the way things are currently configured.

Is it possible to just set up a new certificate, that is tied to monitormywatershed.org (rather than www.monitormywatershed.org). Could that possibly be the issue?

**Comment by HeatherBrooks** [comment]
@aufdenkampe, on a related note, once the SSL certificate issue is sorted out, I think the web server needs to be configured to redirect traffic from www.monitormywatershed.org to monitormywatershed.org. Some subset of users will inevitably add the "www" when they type the URL in their browser and you want them to end up in the right place. Right now they are seeing this: 
![image](https://user-images.githubusercontent.com/9368629/57314797-54306400-70c0-11e9-98ca-858c14c7e75b.png)

**Comment by tslawecki** [comment]
Auto-renew is just setting up a cron job to do the requisite steps. Here it might consist of:
- swapping out the configuration;
- restarting nginx;
- running the renew request;
- restoring the configuration;
- restarting nginx; and
- alerting all that the renew has been attempted so that we can verify renewal and confirm operation.

If we are able to resolve the domain name issue, we may not have to restart nginx, which would be preferable. I suggest we look at this a little later as we work through the new staging protocol.

**Comment by tslawecki** [comment]
@HeatherBrooks, I corrected the configuration so that www.monitormywatershed.org gets to the home page. @htaolimno or @steveskrip might be able to better write the necessary directive(s) to shave of the www.

**Comment by aufdenkampe** [comment]
Closing after creating daughter issue.
