### ISSUE TITLE
Leaf Pack data entry error

### ISSUE THREAD

**Issue by skerlinStroud** [ODM2/ODM2DataSharingPortal#388]
KeyError received when trying to submit data in Leaf Pack data entry form. April 29, 2019.

[KeyError at.docx](https://github.com/ODM2/ODM2DataSharingPortal/files/3135052/KeyError.at.docx)

**Comment by HeatherBrooks** [comment]
@skerlinStroud I am able to create a new leaf pack experiment without encountering the error you described. Can you please try again and see if this is fixed for you?

**Comment by skerlinStroud** [comment]
I can now input and submit Leaf Pack data. Submission is working.
