### ISSUE TITLE
2019-05-06:  Site is completely down

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#389]
Receiving a "400" bad request error for both data.envirodiy.org and data.wikiwatershed.org

**Comment by neilh10** [comment]
ALso accessing through the front page - there is no data showing for me.

https://data.envirodiy.org/sites/LCC45a3/ - 
it says last May 6, 2019, 6:45 a.m. (UTC-08:00)  - I'm PDT

**Comment by aufdenkampe** [comment]
Thanks for the quick bug notice, regarding our HTTP Post web service.

@tslawecki and @htaolimno were working on some server fixes this morning related to the failure of our security certificates to auto-renew late last week.

@tslawecki and @htaolimno, it appears that devices are no longer able to HTTP Post new data to the server. This seems to be happening for all sites.

**Comment by aufdenkampe** [comment]
@tslawecki just fixed this. Sorry for the down-time.

**Comment by SRGDamia1** [comment]
I can see the page again; Thanks!
