### ISSUE TITLE
Sparkline display problems

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#390]
From the current system down report yesterday, my regular site is still not showing graphs
https://data.envirodiy.org/sites/LCC45a3/
The individual graphs report an observation time that implies a recent update, but the visualization area says "No data exist for this variable.
If I try the "Time Series Analyst" and select the data - it goes into a forever loop.
Similarly if I try a download - says "Compiling files" and never completes
This is the same for Chrome and Firefox.   
Do I need Adobe Flash to run, I did tweak chrome "flash" settings recently - but they seem to be on
https://support.google.com/chrome/answer/6258784

**Comment by SRGDamia1** [comment]
Probably the same problem as with #378 and #379.  I'm seeing it too.

@neilh10 - just fyi - the data is stored in two places after being received by the server, both a postgreSQL database and an influx database.  The graphs on the site and on webTSA look to a combination of both of these databases and a generated WaterML index of the data for plotting.  Right now the communication between the working parts is shaky at best, so there are a lot of viewing issues, particularly for any site created after about January 31.

**Comment by neilh10** [comment]
#378 that looks like what I'm seeing.
SRGDamia1 thanks for the info

**Comment by aufdenkampe** [comment]
Yes, we are beginning to work on this and other bug fixes, which we hope to complete in the next several weeks or more.

**Comment by aufdenkampe** [comment]
@htaolimno, I think this is related to errors in the connection or construction of the InfluxDB database.

This issue has repeatedly occurred in the past when a new version is released to production. See issues #193, #131, #99 for previous versions of this issue that appeared to be resolved manually. Some of the connected behaviors are described in #130.

**Comment by aufdenkampe** [comment]
@tslawecki fixed this issue.
It appears to have been related to SSL security routing issues on our database servers, that cropped up when our SSL certificates expired in late April. See #387. We're setting up SSL auto-renew to avoid this in the future.
