### ISSUE TITLE
Deploy clone of production as staging server

### ISSUE THREAD

**Issue by tslawecki** [ODM2/ODM2DataSharingPortal#393]
Because of ongoing gateway issues and other concerns on the current staging server, we are cloning the production web server and using that as the starting point for a replacement.

**Comment by tslawecki** [comment]
Clone of production server made available by LTICO support at (internal) 10.89.1.79; I tested to make sure the main page was accessible, found that I needed to add the internal IP to /opt/websdlenvironment/ODM2WebSDL/src/WebSDL/settings/settings.json. 

Next step is to have LTICO switch external IP on this VM to external IP for current staging server.

**Comment by aufdenkampe** [comment]
Done!
