### ISSUE TITLE
TSA doesn't show from DateTime - uses UTC

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#399]
The TimeSeriesAnalysis (TSA)graph window appears to display in TimeZone (TZ) "DateTimeUTC". This makes it difficult to discuss and display it to other interested parties.

The intial  "72hrs Charts" display with the recorded TZ. https://data.envirodiy.org/sites/LCC45a3/
The downloaded data uses the recorded TZ, and specifies the offset from UTC.

I start the TSA graph from the "72hrs Chart" by pressing the button"open in Time Series Analysis"

It would expect the TSA graph to use the recorded zone. Alternatively if the TZ=UTC is required, it would be nice if that was an option, rather than the default.

The attached graph shows a snapshot of the TSA graph with some anomolies in it. Hovering over the rightmost anomolies shows its time as using "DateTimeUTC", instead of the local "DateTime" 

from the .csv download     
DateTime       | TimeOffset | DateTimeUTC     
6/12/2019 7:15 | -8:00 | 6/12/2019 15:15 | 0.97    

![EnvirDIY_TSA_190613_0943](https://user-images.githubusercontent.com/2766619/59420169-4e672600-8dc4-11e9-90bd-48d163e37661.JPG)

**Comment by aufdenkampe** [comment]
Agreed. This would be a nice feature that was suggested but not prioritized in https://github.com/ODM2/ODM2DataSharingPortal/issues/236#issuecomment-412143248 and #293.

I've added it to a future feature milestone, but we might not get to it soon due to limited funding and priority to our bug fix milestone for release 0.10.

**Comment by neilh10** [comment]
Ok thanks, whenever. I looked through the open issues and didn't see it, so thought I should enter it for reference.

**Comment by aufdenkampe** [comment]
@neilh10, I really appreciate you posting this issue, especially with the level of detail that you provide on what you would see as helpful and why. Do so is a very helpful contribution to our long-term development, and I think it also helps us generate more funding to do the work. Many thanks!

I also appreciate that you looked through the open issues. Indeed, there was nothing that was open that was related to this topic. Thanks.

**Comment by neilh10** [comment]
hey you're welcome.  I've been through a number of software development projects, and been on the fixing end of issues.  :)

**Comment by dbressler75** [comment]
To follow up on what @heilh10 said:  The TSA display in UTC is fine for general data consistency; however, in terms of actual data usage in the here and now and in the citizen science context displaying it this way is probably going to be problematic. Ideally, maybe there would be an option to display data in the current time where a station is located (or possibly a standard time for a region - e.g., for eastern time zone maybe always displaying in EST, as opposed to switching between EST and EDT). Main point being that displaying data in UTC is going to make it a lot harder for users to connect the dots.

**Comment by dbressler75** [comment]
Time stamps in the 72-hour pop-up tables associated with the sparkline plots are also only in UTC and are in 24hr time - listing current local time along with UTC 24hr would be very helpful.

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 
We think our new TSV addresses this issue.
