### ISSUE TITLE
Spark lines and TSA down?

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#403]
Are these known to be down?  I haven't been able to get them to work in several days, even after multiple cache clears.

**Comment by SRGDamia1** [comment]
@aufdenkampe

**Comment by aufdenkampe** [comment]
@SRGDamia1, yes, I'm aware of this. It looks like the production web server got disconnected from InfluxDB on the production database servers at around 3:45 ET on Friday. 

@jcaraballo17 was working on Friday afternoon, setting up our staging web and database servers with our new git tracking approach for managing configuration files, and also doing something similar with our security certificates (possibly with @htaolimno). We'll get on this. It is likely related to the issues we saw with #378 and #390.

@Volk3rJ & @gcutrell, data is still being saved to the main database (in PostgreSQL), but its just not readable from database that we use for visualizations (in InfluxDB).

**Comment by jcaraballo17** [comment]
@aufdenkampe, @SRGDamia1 The sparklines and TSA should be working normally now. The sparklines are shown in all the sites I checked, can you confirm that everything is working again?

**Comment by aufdenkampe** [comment]
Awesome! Looks good to me. Thanks.
