### ISSUE TITLE
Updates to macroinvertebrate data entry: add taxa, hide taxa, change taxa labels and taxa display order

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#404]
The following updates to the macroinvertebrate data entry form (/leafpack/create/) are required to align it with new leaf pack experiment protocols.

- [x] Add these taxa to database and data entry form:
- Other caddisflies (Trichoptera)
- Rat-tailed maggots (Syrphidae)

- [x] Hide these taxa from the user interface but retain in the database:

- All caddisflies (Trichoptera)
- Dobsonflies/fishflies (Corydalidae)
- Alderflies (Sialidae)
- All beetles (Coleoptera)
- All true flies (Diptera)
- All crustaceans (Crustacea)
- All snails (Gastropoda)

- [x] Change these taxa labels:
- Water-penny beetles (Psephenidae) to Water pennies (Psephenidae)
- Right-handed/gilled snails (Prosobranchia) to Right-handed/gilled snails (Gastropoda)
- Left-handed/lunged snails (Archaeopulmonata) to Left-handed/lunged snails (Gastropoda)
- Watersnipe flies (Athericidae) to Aquatic snipe flies (Athericidae)
- Aquatic sowbugs (Isopoda) to Sowbugs (Isopoda) UPDATE 2019-10-08: final version is Aquatic sowbugs (Isopoda)
- All clams and mussels (Bivalvia) to Clams/mussels (Mollusca)
- Common net-spinning caddisflies (Hydropsychidae) to Net-spinning caddisflies (Hydropsychidae)
- Midges (Chironomidae) to Midge flies (Chironomidae)
- Planaria (Turbellaria) to Planarians/flatworms (Turbellaria) UPDATE 2019-10-08: final version is Planarians (Turbellaria)
- [x] Change taxa display order: instead of listing insects first and then non-insects, display in three pollution sensitivity groups. Example:
![image](https://user-images.githubusercontent.com/9368629/60361601-a7ca7a00-99ac-11e9-94e2-4b7acf03c0ac.png)
- [x] Update title in related link box from “Aquatic Macroinvertebrate Collection” to “Atlas of Common Freshwater Macroinvertebrates of Eastern North America”

**Comment by htaolimno** [comment]
@aufdenkampe I am new to Leaf Pack Network. Could you verify that the LPN registration link isn't working? Clicking the link would redirect user to login page. Is this link a known issue also ?

**Comment by SRGDamia1** [comment]
@HeatherBrooks

**Comment by HeatherBrooks** [comment]
@htaolimno Are you asking if the LPN "Register" link on the homepage should have the same fix you implemented for the EnviroDIY Register link (#333)? If so, the answer is yes. It should link to http://monitormywatershed.org/sites/register/. If user is not logged in, it should send the user to the login page. After logging in the user should be redirected to the site registration page.

**Comment by htaolimno** [comment]
@HeatherBrooks a few questions: 1. for the two newly added taxa, you provided common name and scientific name . Do you have additional information to fill fields in the "macroinvertebrate" table ?, like URL, latin name, etc. 2. both snails have their scientific_name changed to "Gastropoda". Are scientific name no longer unique in the database ?  3.  I saw a new "Odonata" scientific name in Group 2 picture, but it isn't stated anywhere in the change list.

**Comment by htaolimno** [comment]
@HeatherBrooks  4. Is "Dobsonflies,fishflies, and alderflies" in "Group 1:Sensitive" same as "Alderflies, dobsonflies, fishflies" in the MacroInvertebrate table ? 5. What are the group assignment for "dobsonfilies/fishflies" and "Alderflies" ? these are two separate taxa in the Macroinvertebrate table.

**Comment by htaolimno** [comment]
@HeatherBrooks I also fixed the LPN "Register" link according to your comment a few days ago. You'll see it in the new release.

**Comment by HeatherBrooks** [comment]
@htaolimno Just talked with Dave Arscott; here are the answers to your first set of questions: 
1. See the yellow highlighted rows in [this Google Sheet](https://docs.google.com/spreadsheets/d/1KDY1lx4A5zW-6jlLcv_YrS8MrrjNZredL_QijpJct9I/edit?usp=sharing). Let me know if you need any additional information.
2. Retain the current assignments in the database, i.e. Left-handed/lunged snails (Archaeopulmonata) and Right-handed/gilled snails (Prosobranchia). However, in the user interface (data entry form), please label them both as Gastropoda to align with the data entry sheets in the Leaf Pack Experiment Kit.
3. Retain the current assignments in the database, i.e. Damselflies (Anisoptera) and Dragonflies (Zygoptera). However, in the user interface, please label them both as Odonata, again to align with the experiment kit. Arscott asks that you create a new taxa in the database for Odonata and assign it as the parent taxa for damselflies and dragonflies. Please see the blue highlighted row in the Google Sheet linked above for URL, etc. Odonata should not be visible on the data entry form.

**Comment by HeatherBrooks** [comment]
@htaolimno Next set of answers: 
4. Yes, this is just a reordering of the names to align with the data entry form in the experiment kit.
5. Dobsonflies/fishflies and Alderflies shoiuld be assigned to Megaloptera. I assume since Megaloptera appears on data entry form, it already has an entry in the database? I have added it to the ITIS identifier Google Sheet in case you need more information.

**Comment by htaolimno** [comment]
@HeatherBrooks yes, Megaloptera is a separate entry. three following three are all separate entries in the macroinvertebrate table:
- Alderflies, dobsonflies, fishflies(Megaloptera)
- Dobsonflies/fishflies(Corydalidae)
- Alderflies(Sialidae)

**Comment by HeatherBrooks** [comment]
@htaolimno Thank you. Please see the second task in #405 for how the three separate table entries need to be treated.

**Comment by aufdenkampe** [comment]
@htaolimno, let's use these GoogleSheets to organize our information for these connected issues:
- [Leaf Pack Network Macroinvertebrate ITIS Identifiers](https://docs.google.com/spreadsheets/d/1KDY1lx4A5zW-6jlLcv_YrS8MrrjNZredL_QijpJct9I/edit#gid=0)
- [Biotic Index Calculation](https://docs.google.com/spreadsheets/d/1CjhS9nFur2oBzLn0ob7-Lrs5AEEZLGGXiv4yPjc2wsg/edit#gid=1466203958)

@HeatherBrooks, I just added Group and DisplayOrder columns to the [Leaf Pack Network Macroinvertebrate ITIS Identifiers](https://docs.google.com/spreadsheets/d/1KDY1lx4A5zW-6jlLcv_YrS8MrrjNZredL_QijpJct9I/edit#gid=0). Could you complete the entries in those columns? That would then allow us to sort.

@HeatherBrooks, could you also provide us with an updated version of the paper Biotic Index Sheet and other forms that are provided in the Leaf Pack Kits? We have [Biotic Index Sheet2019 FNLwithExample.pptx](https://docs.google.com/presentation/d/1bFmN5KP0-3bWMGal2NqXS_iLzzwAgRFk/edit#slide=id.p1), but it is clearly outdated from the recommendations at the top of this issue.

**Comment by htaolimno** [comment]
@HeatherBrooks I probably have to break the uniqueness on "scientific_name" field of macroinvertebrate table anyway, because taxa "All caddisflies (Trichoptera)" and "Other caddisflies (Trichoptera)" share the same scientific_name.

**Comment by HeatherBrooks** [comment]
@aufdenkampe I've completed the Group and DisplayOrder entries in the ITIS identifiers sheet.

Here are the final versions of the [LaMotte data sheets](https://drive.google.com/drive/folders/1GlpD9CC6LITthxGEQMQrt0gEIFSwk4tF?usp=sharing).

@htaolimno Please be aware that I haven't yet updated the common names in the ITIS identifier sheet to match the final files. I can do that tomorrow. They should match those in the third task at the top this issue.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, thanks for filling out the new columns in the [Leaf Pack Network Macroinvertebrate ITIS Identifiers-2019](https://docs.google.com/spreadsheets/d/1KDY1lx4A5zW-6jlLcv_YrS8MrrjNZredL_QijpJct9I/edit#gid=0) sheet!

I've now sorted the sheet in display order.

@htaolimno, that is correct that the recent decision to include partial taxonomic groups such as  "Other caddisflies" means that the scientific names are no longer always unique, unless we write it out as "Trichoptera other than Hydropsychidae" (which we could do). 
@HeatherBrooks, what do you think of that idea? If so, would it be a good idea to write out "Caddisflies other than net-spinning"? If you remember from our discussions more than a year ago, I never liked the "Other..." categories because they always depend on knowing what is in the categories that are not counted, which could change, and which makes it much harder to adapt in the future.

**Comment by HeatherBrooks** [comment]
@htaolimno I've updated the common names in [Leaf Pack Network Macroinvertebrate ITIS Identifiers-2019](https://docs.google.com/spreadsheets/d/1KDY1lx4A5zW-6jlLcv_YrS8MrrjNZredL_QijpJct9I/edit?usp=sharing) to match the final experiment kit data sheets. I've also noted two name changes in the third task in original post in this issue. Sorry for the late changes ... I just received the final versions yesterday.

@aufdenkampe I've forwarded your question about the "Other" categories to Dave Arscott. I hope to hear back from him shortly.

**Comment by HeatherBrooks** [comment]
@aufdenkampe I talked with Arscott and he agrees that we need the category to be more specific than "Other caddisflies (Trichoptera)." [This datasheet](https://sitesmedia.s3.amazonaws.com/creekconnections/files/2014/02/PTIdatasheet.pdf) from an adaptation of the EPA Volunteer Stream Monitoring Methods Manual refers to non-net-spinning caddisflies, so how about this category name: _Non-net-spinning caddisflies (Trichoptera other than Hydropsychidae)_

It's lengthy but we really need to specify both common and Latin names.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, sounds good. Did you update the  [Leaf Pack Network Macroinvertebrate ITIS Identifiers-2019](https://docs.google.com/spreadsheets/d/1KDY1lx4A5zW-6jlLcv_YrS8MrrjNZredL_QijpJct9I/edit?usp=sharing)?

@htaolimno, can you make this change?

**Comment by HeatherBrooks** [comment]
@aufdenkampe Thanks for the reminder. I've just updated [Leaf Pack Network Macroinvertebrate ITIS Identifiers-2019](https://docs.google.com/spreadsheets/d/1KDY1lx4A5zW-6jlLcv_YrS8MrrjNZredL_QijpJct9I/edit?usp=sharing).

**Comment by aufdenkampe** [comment]
@htaolimno just deployed his work on this issue to staging. So far it just includes the "results" of a completed LP experiment, and does not yet include the data entry form.

For an example, see https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/.

@HeatherBrooks, feel free to provide feedback.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @htaolimno I've checked all of the tasks assigned in the original post against the leaf pack data for [https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/](url). 

Tasks were completed properly with one exception; it appears the last task was missed.

- Update title in related link box from “Aquatic Macroinvertebrate Collection” to “Atlas of Common Freshwater Macroinvertebrates of Eastern North America"

**Comment by aufdenkampe** [comment]
@HeatherBrooks, the "create" experiment data entry now works.

@htaolimno, can you do this last update to the "Leaf Pack Details" pages ([example](https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/)): 
- Update title in related link box from “Aquatic Macroinvertebrate Collection” to “Atlas of Common Freshwater Macroinvertebrates of Eastern North America"

**Comment by aufdenkampe** [comment]
Looks good! Thanks!
