### ISSUE TITLE
Changes to leaf pack experiment calculations: recalculate "All xxx" fields

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#405]
The following updates to the macroinvertebrate calculations are required to align it with new leaf pack experiment protocols. 

Recalculate the following “All xxx” fields:
1. All caddisflies
- This category will now be hidden from the user interface but will be retained in the database.
- Present behavior is that system auto-populates “all” but allows user to edit.
- Change to remove user ability to edit because we are adding an “other” category that can be user edited. This field should now auto-populate with the sum of the “Other caddisflies (Trichoptera)” and “Common net-spinning caddisflies (Hydropsychidae)”
2. All Megaloptera
- Dobsonflies/fishflies (Corydalidae) and Alderflies (Sialidae) will be hidden on data entry form because we are no longer asking users to identify to family level.
- User will now enter their counts as “Dobsonflies, fishflies, and alderflies (Megaloptera)” so this field must be changed to be editable by the user. 
3. All true flies 
- This category will be now hidden from the user interface but will be retained in the database. 
- Make sure it now sums five taxa instead of four (aquatic snipe flies, crane flies, midge flies, black flies, and rat-tailed maggots).

**Comment by aufdenkampe** [comment]
@HeatherBrooks, can we use this site as a test that the calculations are being done correctly?
https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/

Is there another site we could use?

**Comment by HeatherBrooks** [comment]
@aufdenkampe Since I'm not able to add a new leaf pack experiment using the leaf pack manual example, I think [https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/](url) and [http://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/](url) will work well enough for testing.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, I'm presuming this issue was completed with #407 and commit https://github.com/ODM2/ODM2DataSharingPortal/commit/6aa4ba72f746a67ee3fa4be1d52c913f3a7b5ed4. Feel free to confirm.
