### ISSUE TITLE
Changes to biotic index calculation

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#407]
A new (simpler) Pollution Tolerance Index will replace the biotic index calculation that uses taxa-specific tolerance values. As a result, the following constants and calculations are no longer needed:
- Pollution tolerance values (TV) for individual taxa
- Calculation of total TV for individual taxa (average individuals*taxa TV)
- Biotic index calculation using taxa-specific TV
- Calculation of average individuals over leaf packs (total count per taxa/number of leaf packs retrieved)

**Please note,** the following calculations remain unchanged: total individuals across all leaf packs, % EPT. Additionally, “Number of leaf packs placed” and “Number of leaf packs retrieved” fields should remain on data entry form and be displayed on the leaf pack experiment details page but will no longer be used in any calculations.

- [x] New calculation

1. Sum the total # of taxa groups present (_not individuals counted_) for each of the three sensitivity groups. 
**Example:** In Group 1, 7 out of 8 possible taxa are present. In Group 2, 5 taxa are present. In Group 3, 4 taxa are present.
2. Multiply the sum of the total # of taxa groups by the group weighting factor (Group 1 weighting factor = 3; Group 2 = 2; Group 3 = 1) to get the index value. 
**Example:** Group 1 = 7 taxa * 3 = 21; Group 2 = 5 * 2 = 10; Group 3 = 4 * 1 = 4.
3. Add together the three index values to get the Pollution Tolerance Index score. 
**Example:** 21+10+4 = 35
4. Fetch the Pollution Tolerance Index Rating and Degree of Organic Pollution. 
**Example:** 35 = Excellent - Organic pollution unlikely.
![image](https://user-images.githubusercontent.com/9368629/60365197-106a2480-99b6-11e9-989d-8a126011d655.png)

- [x] Changes to index/water quality nomenclature and ranges

- All incidences of “Biotic Index” in the user interface will be replaced by “Pollution Tolerance Index Score”
- All incidences of “Water Quality Category” will be replaced by “Pollution Tolerance Index Rating”
- Index range will change from 0-10 to 0-47

**Comment by HeatherBrooks** [comment]
@aufdenkampe Tara Muenz has asked me for a progress update as she is hoping to introduce the new leaf pack data entry process at a workshop on October 5. I believe the new leaf pack experiment kit with the updated data entry forms and biotic index calculation is on sale or will be soon. How soon are the changes likely to reflected in the data portal? I see you've assigned a due date of August 31 but not sure if that's going to happen?

**Comment by htaolimno** [comment]
I implemented the new Pollution Tolerance Index. Changes will be available for testing soon.

**Comment by aufdenkampe** [comment]
Now on staging. Please look it over at https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/, 
http://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/, 
or elsewhere.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @htaolimno I checked the calculations for the two sites Anthony mentioned and I'm seeing a couple of issues. 

New calculations: (examples from [https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/](url))
1. Sum the total # of taxa groups present for each of the three sensitivity groups. **Needs work.** Taxa with 0 counts are being included in the tally. In Group 1, Total # of Taxa Groups Present should be 7 instead of 8; in Group 3, Total # of Taxa Groups Present should be 6 instead of 7.
2. Multiply the sum of the total # of taxa groups by the group weighting factor to get the index value. **Working properly.** 
3. Add together the three index values to get the Pollution Tolerance Index score. **Weirdly, this is working properly.** It appears that while an _incorrect number is being displayed_ for Total # of Taxa Groups Present (see above), the _correct number is being used in this calculation_. The numbers displayed are 24+16+7=47, but the PTI score is displayed as 43, which shows that the correct numbers are being used, 21+16+6.
4. Fetch the Pollution Tolerance Index Rating and Degree of Organic Pollution. **Working properly.**

Other issues:
1. I'm not sure how this is possible, but it looks like the total number of individuals is calculated **correctly** for [https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/](url) (22) but **incorrectly** for [http://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/](url) (should be 647 but is showing 666).
2. Percent EPT appears incorrect. For [https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/](url): 1 mayfly + 1 stonefly + 0 other caddisflies = 2 EPT/22 total individuals = 9.09% instead of the 13.64% being displayed. For the Bog Brook site 49 + 9 + 0 = 58. If you divide 58 by either the correct or incorrect total number of individuals you get just under 9% instead of the 14.41% being displayed.

**Comment by aufdenkampe** [comment]
@htaolimno, it looks like we have more work do to on this.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @htaolimno Regarding [earlier mention of problems with percent EPT](https://github.com/ODM2/ODM2DataSharingPortal/issues/407#issuecomment-567191496): it is now being calculated properly for [StroudEduc_TEST](https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/) and [BogBrook_Rt312](http://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/). 

However, I created a new experiment today for [WCC_SpencerRd](https://staging.monitormywatershed.org/sites/WCC_SpencerRd/leafpack/28/) and the percent EPT is incorrect: 
55 stoneflies + 30 mayflies + 16 non-net-spinning caddisflies = 101
101 EPT/184 total individuals = 0.5489
Percent EPT should be 54.89% but is displayed as 46.20%

Not sure why it works for some experiments but not others?

**Comment by aufdenkampe** [comment]
@htaolimno, can you look at this?

**Comment by htaolimno** [comment]
@HeatherBrooks regarding matching up to WCC_Spencer example, I've just updated the filter string in the code to use the correct scientific name "Trichoptera other than Hydropsychidae". It's ready for testing. thanks.

**Comment by HeatherBrooks** [comment]
@htaolimno That did the trick. Thanks!

**Comment by aufdenkampe** [comment]
Thanks you both!
