### ISSUE TITLE
Changes to leaf pack experiment details display page

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#408]
The following changes should be made to the page that displays leaf pack experiment results (/sites/sitename/leafpack/4/).
- [x] Changes to "Placement Information" Section. 
In [#337](https://github.com/ODM2/ODM2DataSharingPortal/issues/337) I asked for both Deployment Type and Stream Habitat Type to be deleted. However, it appears that Deployment Type is still being used but a different label should be applied. The Content field is not currently being used so perhaps it can be hidden from the user interface.
- Change “Deployment Type” label to “Stream Habitat Type” or if a closer match to the variable name would be less confusing, the label could be "Deployment Location"
- Hide “Content” field.

- [x] Changes to the "Macroinvertebrate Counts" Section
- Display the data by pollution sensitivity group, in the same order as in the data entry form.
- Display three new fields below the group taxa count listings with the following labels and the appropriate values displayed from the database:
    - Total # of Taxa Groups Present
    - Group Weighting Factor
    - Group Index Factor 
      Example:
![image](https://user-images.githubusercontent.com/9368629/60366647-24178a00-99ba-11e9-9aab-30bcfed683be.png)

- [x] Changes to "Summary" Section
- Change section title from “Water Quality Index Values” to “Summary Analysis”
- Move summary table above chart
- Update summary table
    - Change title from “Summary” to “Results Overview”
    - Total Number of Individuals Found remains unchanged 
    - Pollution Tolerance Index Score replaces Biotic Index
    - Pollution Tolerance Index Rating replaces Water Quality Category
    - Percent EPT remains unchanged
 Example:
![image](https://user-images.githubusercontent.com/9368629/60366827-a902a380-99ba-11e9-9a35-bd54105e43ae.png)

- [x] Update chart

- Add title “Relative Abundance of Macroinvertebrate Taxa” above chart
- Keep basic mechanics the same (i.e., continue charting % of total individuals versus taxonomic group; retain “sort values” option).
- Number of groups being charted will increase from 14 to 23 to reflect taxa changes.
- Legend should display taxa in the same order as in the data entry form (Groups 1-3).

**Comment by htaolimno** [comment]
@HeatherBrooks I assume that the "/sites/Pt_Lookout_Forest/leafpack/6/update/" page needs to change to display the taxa names and counts by three groups under section 3 "Enter your macroinvertebrate count data".

**Comment by HeatherBrooks** [comment]
@htaolimno Yes, that's correct. Anywhere we're displaying macroinvertebrate counts, display the data by pollution sensitivity group. Thanks!

**Comment by aufdenkampe** [comment]
Now on staging, along with #406 & #407. Please look it over at https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/, 
http://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/, 
or elsewhere.

@htaolimno, it looks like you missed two minor components that @HeatherBrooks had requested. Remaining are:
1.  Move the "Results Overview" table to the top of the "Summary Analysis" section, above the charts.
2. Add titles to the charts. First one is “Relative Abundance of Macroinvertebrate Taxa”. Not sure about second chart.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @htaolimno Changes look good other than the two missed ones Anthony listed above. The title for the second chart should be "Relative Abundance by Sensitivity Group."

**Comment by HeatherBrooks** [comment]
@aufdenkampe @htaolimno A few questions about the display page:

**Macroinvertebrate Counts Section**
1. Can the Related Link box be moved above the counts, just below the section title, to make it more prominent?
2. Can this section have three columns so all three groups can be displayed side by side? If not, please add whitespace between the bottom of Group 1 results and the top of Group 3 results.
3. Can the group names be in a larger font/different color than the Taxon/Tally column labels?

**Summary Analysis Section**
1. Can the Results Overview table be moved so that it is the first item in the section rather than the last?
2. Can the Sensitivity Group chart be moved above the Taxonomic Group chart?
3. The legend for the taxonomic groups chart is lengthy -- can it be moved underneath the chart and split into columns? Three columns might allow for them to be grouped by sensitivity group. If that's too tricky, six columns would allow for four taxa per column which would shorten the legend nicely.

**Comment by htaolimno** [comment]
@HeatherBrooks Please review new improvements on staging server. thanks.

**Comment by aufdenkampe** [comment]
@htaolimno, thanks for all these updates just before the holiday!

This issue looks completed to me, so I'll close it but @HeatherBrooks may still wish to review.

**Comment by HeatherBrooks** [comment]
@aufdenkampe @htaolimno I'm back from holiday and just checked the changes. Looks great, thanks!

**Comment by HeatherBrooks** [comment]
@htaolimno Is it possible to remove the underline from the chart titles? I think they might mislead people into thinking they're hyperlinks that aren't functional.
