### ISSUE TITLE
Add new chart to summary section of leaf pack experiment details page

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#409]
With the addition of the new pollution sensitivity groups, it would be valuable to Leaf Pack Network users to have a new chart added to the experiment details page (/sites/sitename/leafpack/4/).

The new chart would be similar to the existing relative abundance chart, but it would display only three bars -- one for each sensitivity group. If possible, colors of bars should match the colors used on the LPN Biotic Index Data Sheet:
- Group 1 (Sensitive): turquoise, (#00A0D3; RGB 0, 160, 211)
- Group 2 (Somewhat Sensitive): dark purple (#7B439A; RGB 123, 67, 154)
- Group 3 (Tolerant): orange (#EE7E22; RGB 238, 126, 34)

**Comment by tslawecki** [comment]
Although I'm generally not a fan of pie charts, I feel like this may be a not-bad time to use one for two reasons:

1) It would be more visually interesting to have both a pie chart and a bar chart ; and

2) It's a simple enough data set.

On the other hand, maybe a stacked bar chart like #3 in [this blog post](http://www.storytellingwithdata.com/blog/2014/06/alternatives-to-pies) might work, too. Does either alternative (pie or stacked bar) feel interesting?

**Comment by HeatherBrooks** [comment]
@tslawecki I'm sorry, I was waiting for feedback from our education department on your suggestion but they're all out of office for the week. Let me know if you still need it or if you've already worked it out.

**Comment by tslawecki** [comment]
No worries, regular bar chart is being implemented. We can always revisit later!

**Comment by aufdenkampe** [comment]
Now on staging, along with #406, #407, & #408. Please look it over at https://staging.monitormywatershed.org/sites/StroudEduc_TEST/leafpack/18/, 
http://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/, 
or elsewhere.

**Comment by HeatherBrooks** [comment]
@aufdenkampe The new chart looks good, thanks.

**Comment by HeatherBrooks** [comment]
@aufdenkampe Sorry, missed one thing: the y-axis label should be "% of Total Individuals" instead of "Count" to match the other chart.

**Comment by aufdenkampe** [comment]
@htaolimno fixed this with https://github.com/ODM2/ODM2DataSharingPortal/commit/6aa4ba72f746a67ee3fa4be1d52c913f3a7b5ed4
