### ISSUE TITLE
Move add new sensor button to above request notice

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#412]
I'm sick of scrolling down past the notice.  It's annoying.

![image](https://user-images.githubusercontent.com/5374350/61552375-aa594600-aa25-11e9-9180-5a2b8a0ba8b9.png)

**Comment by aufdenkampe** [comment]
@SRGDamia1, I agree that the location of this button is quite annoying when adding new sensors, as it typically requires scrolling to see it on laptop screens.

@htaolimno, I'm presuming that this would be an easy change. Let us know if you might be able to make the change easily.

**Comment by htaolimno** [comment]
@SRGDamia1 please test this new change on staging server.

**Comment by aufdenkampe** [comment]
@htaolimno, looks great to me! thanks!

**Comment by SRGDamia1** [comment]
Great, thank you!
