### ISSUE TITLE
monitor my watershed

### ISSUE THREAD

**Issue by armstrongcl** [ODM2/ODM2DataSharingPortal#413]
The MMW turbidity legends in the time series analyst data sets do not give an indication of which is turbidity-high and -low.  This only becomes significant if there is a large gap between the two, so that one cannot tell which is more accurate for the given level.  Could the legend be changed to reflect high and low?

**Comment by SRGDamia1** [comment]
Ideally, we'd be able to see all notes in TSA. I'm closing this issue because it's a part of #326.
