### ISSUE TITLE
Show notes field in the table on the manage sensors page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#415]
![image](https://user-images.githubusercontent.com/5374350/62147278-2d4f8b80-b2c5-11e9-96b5-8dffdcc2de95.png)

**Comment by htaolimno** [comment]
@SRGDamia1 I added "Notes" column to the table. Please check staging server for testing.

**Comment by aufdenkampe** [comment]
That is helpful. Looks good!

**Comment by SRGDamia1** [comment]
I see it, thank you!
