### ISSUE TITLE
Confirm everything is correct in `requirements.txt` for R0.10

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#417]
Confirm everything is correct in the `requirements.txt` file in the `development` branch to reflect our recent Django 1.11.20 updates to staging (see . https://github.com/ODM2/ODM2DataSharingPortal/blob/development/requirements.txt. 
See https://github.com/ODM2/ODM2DataSharingPortal/issues/380

I changed the file to reflect the update to Django==1.11.20 (https://github.com/ODM2/ODM2DataSharingPortal/commit/cb826db4dacdbd8f33517f97bcb499080bab7c0f), but I'm not sure about the other versions.

**Comment by jcaraballo17** [comment]
Yes, this is the correct `requirements.txt` file.
