### ISSUE TITLE
data sets not clickable (see attached)

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#425]
![datasets_not_clickable](https://user-images.githubusercontent.com/39309124/62732991-a9e41780-b9f3-11e9-9f19-539c4d354bb1.JPG)

I'm simply trying to graph cond data from different sites and it won't allow me to click more than two variables to plot.

**Comment by dbressler75** [comment]
![datasets_waterdepth_not_clickable](https://user-images.githubusercontent.com/39309124/62733154-047d7380-b9f4-11e9-85c7-f706c8c0b70d.JPG)

Nothing is clickable for water depth

**Comment by dbressler75** [comment]
![datasets_temp_is_clickable](https://user-images.githubusercontent.com/39309124/62733366-705fdc00-b9f4-11e9-80e8-26f89003dcdb.JPG)

Temperature works though

**Comment by dbressler75** [comment]
![datasets_turb_is_clickable](https://user-images.githubusercontent.com/39309124/62733487-bb79ef00-b9f4-11e9-9546-758d7d4c9dde.JPG)
 
Five turb (five is max correct?) are clickable, so turb seems to be working too

**Comment by dbressler75** [comment]
Problem of data sets not being clickable seems to be persisting

![datasets_not_clickable2](https://user-images.githubusercontent.com/39309124/65341007-69a0b900-db9d-11e9-883f-a92125606611.JPG)

**Comment by aufdenkampe** [comment]
@dbressler75, Thanks for documenting this bug with screenshots!

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 
We think our new TSV addresses this issue.
