### ISSUE TITLE
Sites are duplicated on map

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#435]
Some sites have duplicate markers on the map when browsing sites.

Some I've found:  Coldwater Moorse, SWRCWEATHER, Davis Weather,

**Comment by s-hicks2** [comment]
I've found at least 8 stations that are duplicated on the map, and some are actually on the map 3 times, all at the exact same location and with the same Site ID and URL link.

http://monitormywatershed.org/sites/MSHO2S/
http://monitormywatershed.org/sites/BCMR1S/
http://monitormywatershed.org/sites/HR_Weir/
http://monitormywatershed.org/sites/WCC718/
http://monitormywatershed.org/sites/SWRCWEATHER/
http://monitormywatershed.org/sites/DavisWeather/
http://monitormywatershed.org/sites/ColdwaterMorse/
http://monitormywatershed.org/sites/PCHS_POND2/

**Comment by mbarneytu** [comment]
Just checking in on this issue, as I encountered it for our site [Coldwater Morse](http://www.monitormywatershed.org/sites/ColdwaterMorse/). I notice that if  I go to My Sites and navigate to the ColdwaterMorse site, the map displays one pin, as expected.

**Comment by aufdenkampe** [comment]
Fixed with v0.16 release
