### ISSUE TITLE
Security vulnerability reported

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#440]
A user privately reported a security vulnerability to me earlier today. I sent details in an email to @aufdenkampe but have received no response. As I am not an admin on this repository, I can't open a security advisory. Please contact me ASAP for details. @htaolimno @jcaraballo17

**Comment by aufdenkampe** [comment]
Thanks for those details emailed privately. We're working on it.

**Comment by aufdenkampe** [comment]
Update:

After additional information on Oct. 17 & 23 (via "SECURITY VULNERABILITY reported for Monitor My Watershed" email thread), our development team still has not been able to reproduce the issue.

**Comment by htaolimno** [comment]
I've traced down the issue with helps from @HeatherBrooks. Will talk about it through private email exchanges.

**Comment by aufdenkampe** [comment]
According to @HeatherBrooks, the fixes that @htaolimno applied last week to staging appear to work well! Thanks all!
