### ISSUE TITLE
Clarify our Gitflow workflow conventions; clean stale branches

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#442]
For this project we've generally used a form of the collaborative [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), which is an extended form of the [Git Feature Branch Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) that is suited for projects with a release cycle. Atlassian's documentation (links above) explain these well, and the figure below provides a summary.

<img width="1442" alt="Gitflow_Atlassian" src="https://user-images.githubusercontent.com/5166036/66778009-2251d380-ee90-11e9-98ec-660aa6488de0.png">

We'll more closely adhere to these conventions:
- head of `master` branch always deployed to https://monitormywatershed.org
- head of `develop` branch always deployed to https://staging.monitormywatershed.org
- `develop` will be the default branch for all PRs, etc.
  - This is a change, but Azavea sets their repos this way, and it makes sense for Gitflow.
- Feature branches only available for testing in private development environments
- Issues will be `closed` when the relevant branch is tested on `develop` and reviewed as completed or fixed.

In the meanwhile, we'll cleanup all the stale branches, including `development`, which was the equivalent to `develop`, but hadn't been maintained with any hot fixes, so we're renaming and functionally rebasing.

cc: @tslawecki, @htaolimno, @SRGDamia1, @HeatherBrooks, @darscott

**Comment by SRGDamia1** [comment]
Thank you!

**Comment by aufdenkampe** [comment]
@htaolimno and I cleaned up stale branches in the repo yesterday and today. Today we confirmed that staging currently reflects the `develop` branch. 

Also, I think we will not likely create separate "release" branches, as shown above, because it's added complexity and unnecessary as we don't have the developer bandwidth to work on new features simultaneously with finalizing a release.
