### ISSUE TITLE
TSA Cannot distinguish between multiple timeseries with same variable code, thus all appear when code selected via url

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#444]
I've just a got a new simple onsite sensor system working - yeah!
I'm just wondering how to understand the underlying visualization presented for the specific sensor arrangements here http://data.envirodiy.org/sites/TU-RC-01/
Thanks for any insights.

I have a simple power(VA) monitoring application that is being performed on a  pit-tag system embedded in a stream that is  solar powered. The pit-tag system requires large pulsed currents (4000mA) to stimulate an antenna and read possible tags embedded in any fish swimming through the antenna. The power system design is a voltage regulator that provides an accurate stable voltage from a solar charging battery array. The solar charged battery array voltage, varies a few volts voltage depending on its charge storage status.

The monitoring is 1) Regulated Voltage from regulator (0-24V), 2) Current (mA) max and 3) Current min  (ma) from regulator, and 4) Solar/battery Voltage 5) Internal LiIon battery voltage. 6) Unique sequence number .
I'm of course using modular sensors:) 
In order to do the Current Max and Min, I have one sampling array running at 5min intervals measuring the supplied current and then comparing against internal record and deriving a virtual sensor Max and Min. Every 4hours it reports all sensors to data.enviorDIY.

So the sensing is split into two phases a) before Nov 12- 8am PST where it is in validation mode using  a simple solar cell and there are daily solar fluctuation, and no effective current load. 
 b) after Nov 12 1pm PST where the system is running on the target system

When I look at 1) regulated voltage - and step to Time Series Analyst Tab, it shows two lines, almost the same but not quite. 
On the  [datasets] they are identified as Series 1906 and 1909
Just wondering why two data sets.?
2) Similarly Regulator Supplied max current - data sets 1907 and 1908
3) Regulator Supplied min current. dataset as 1907 and 1908 
4) Solar Battery Voltage (0-26V) 1906 and 1909
5) LiIon Battery voltage - dataset 1910 
  
The "front door dashboard graphical summaries" seem to be somewhat accurate - accurate for the time (Nov 12, 2019 2:52pm ) but not all the graphical elements. 
Can I expect these to be accurately scaled each time or is there an intergration delay?
![image](https://user-images.githubusercontent.com/2766619/68719958-8dabc580-0562-11ea-8f26-da7285f9affe.png)

For the 1st sensor/graph, 1) Regulated voltage, when I just select dataset 1907 the graph I get is roughly the one I expect of uniform voltages peaking at 16V (but different from the dashboard view)

![image](https://user-images.githubusercontent.com/2766619/68720298-9e107000-0563-11ea-9dfd-0f275f1cca1e.png)

For the 4th sensor/graph "battery Solar Charged Voltage" and selecting dataset 1909 I get a different view from the dashboard view. 
Dashboard view shows (un-uniformly scaled)
 Last observation Nov. 12, 2019, 2:52 p.m. (UTC-08:00)  27.661(V)
Data analysist is a bit obscured for time but indicates 0.097V

![image](https://user-images.githubusercontent.com/2766619/68720441-170fc780-0564-11ea-84b1-f6d4ac8fc8db.png)

The Regulator supplied max current appears roughly as expected between the dashboard and data analytics view.
 
Thanks for any insights.

**Comment by SRGDamia1** [comment]
TSA can only distinguish between the datasets to the level of "variable_code."  It doesn't know anything about notes, offsets, or UUID's.  When you use the "Open in Time Series Analyst" button next to a spark line/summary plot it opens a new page with TSA with the site and variable code specified in the URL.  But because TSA doesn't get more granular than variable codes, all variables with the same code will appear.

The front-door/spark lines are auto scales to whatever range falls within the last 3 days.  If you only have two hours of data within the last 72 hours, the time axis will have a full scale of 2 hours - even if that available two hour period was 24 hours ago.  I forget exactly what the threshold is before a gap is displayed in the sparklines - it's a few hours.  (TSA will connect the dots no matter how big the gap is.)  To see the gap, you need to have data both before and after the gap within the 72 hour cutoff.

The point data values, sparklines, and TSA plots are *supposed* to always be in sync with each other, but they can be off from each other by up to half an hour.

**Comment by neilh10** [comment]
Hello @SRGDamia1 thanks for the explanation,    
1) I agree with your name change to this bug report and the intent
In addition I would add that where there are multiple data sets of the level of "variable_code", with no way of differentiating the sensors, it requires a guess to figure out the assocation. I've used Notes to do this for the front-door dashboard sparkline. It appears Notes is not selectable on the  TSA plots.

2) The front-door/spark lines plots, which state the Last Observation reading, does not actually appear to include that Last Observation data point. This is confusing as I would expect it to include it as its the only method available to the viewer to understand the scaling.
If you compare the plot below for the 1st plot Regulated Voltage now and the first reading above - both indicate Last Observation 16.0(V). However for the plot above while indicating 16.0(V) does not show the Last Observation.  Should I report this as a seperate issue/bug.?  


![image](https://user-images.githubusercontent.com/2766619/68784852-19206780-05f2-11ea-8769-486dc4f4a6fa.png)

**Comment by SRGDamia1** [comment]
The spark line is probably just delayed.  I think the sparklines are usually about 30 minutes behind.

**Comment by aufdenkampe** [comment]
Removed WOFpy label because the related issue is covered in #445.

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 
We think our new TSV addresses this issue.
