### ISSUE TITLE
WOFpy &variable doesn't specify exact series with multiple timeseries with same variable code

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#445]
For TU-RC-01 I have specified multiple  All_ExternalVoltage_Battery.
Inspecting with TSA Datasets they are 1906 and 1909
When accessing however I can only specify &variable=envirodiy:All_ExternalVoltage_Battery and this seems to alaternatively provide the data point from 1906 and 1909

http://data.wikiwatershed.org/wofpy/rest/1_1/GetValues?location=envirodiy:TU-RC-01&variable=envirodiy:All_ExternalVoltage_Battery

I would expect that the dataset could be uniquely identified and selected in some fashion.
This may be related to https://github.com/ODM2/ODM2DataSharingPortal/issues/444

**Comment by aufdenkampe** [comment]
We might get to address this with the next round of development.

**Comment by aufdenkampe** [comment]
@neilh10, as I described in:
- #450

> WOFpy, on the other hand, is built around WaterML 1.1 [which doesn't contain the required metadata for this issue], so it can not easily be updated to contain that info. Since WOF and WaterML 1.1 will be deprecated by CUAHSI in the next two years, we have decided to focus our web service efforts on emerging OGC standards being adopted by USGS, such as OGC SensorThings API and/or OGC Environmental Data Retrieval (EDR) API. Both are still in their infancy and have no client libraries, so we are waiting for things those software ecosystems to mature.

So, we won't be solving this for WOFpy.

However, it is firmly on our roadmap to implement OGC SensorThings API and/or OGC Environmental Data Retrieval (EDR) API within a year or so (although funding is not yet in hand for those specific tasks).
