### ISSUE TITLE
Site serving insecure pages (not redirecting to https)

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#456]
@aufdenkampe I'm getting insecure site warnings for all URLs at monitormywatershed.org, data.envirodiy.org, and data.wikiwatershed.org in multiple browsers. When I add "https" to the URLs it solves the problem. We had the same problem in January 2019; @htaolimno fixed it by changing the configuration file to redirect from http to https but he remembers that the redirect was reverted at some point.

This is of particular concern on the login and registration pages.

**Comment by aufdenkampe** [comment]
@htaolimno and @tslawecki, can you look into whether we can update the config files to include the redirects, as we also complete https://github.com/LimnoTech/ODM2DataSharingPortalConfig/issues/34?

Given that www.monitormywatershed.org was dropped, it seems like we indeed had a reversion of some config file settings. We need to always apply the fix to our config repo, to avoid this problem in the future.

**Comment by aufdenkampe** [comment]
@htaolimno, can you look into fixing this. It seems you fixed in early 2019, but it somehow reverted.
Let's fix it via our config repo, so that it can't get reverted.

**Comment by aufdenkampe** [comment]
I'm nearly certain that @ptomasula fixed this on staging.
