### ISSUE TITLE
Remove leaf pack test data

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#458]
Please delete the test leaf pack data for these two sites:
[http://monitormywatershed.org/sites/STUDIO_AIR/](http://monitormywatershed.org/sites/STUDIO_AIR/)
[http://monitormywatershed.org/sites/TestSiteC/](http://monitormywatershed.org/sites/TestSiteC/)

If the sensor data was also for testing purposes as well, please delete the sites entirely.

Kerlin, Muenz, and Brooks will delete their own test data but we can't delete the data owned by Craig Blackburn and Juan Caraballo.

**Comment by HeatherBrooks** [comment]
Tara Muenz had to create a new login and therefore can't access the test site she created on her original login. So an admin will need to delete [http://monitormywatershed.org/sites/TEST1Tara/](http://monitormywatershed.org/sites/TEST1Tara/) for her.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, I deleted Tara's site and removed the Leaf Pack experiments from the sites setup  by @jcaraballo17 and @darksinge.

BTW, @SRGDamia1 has superuser privileges and can also do this for any site. She/we also have the ability to change the owner of a site to any other user.

**Comment by HeatherBrooks** [comment]
@aufdenkampe Thanks! Can I be made a superuser so that I can manage issues that crop up with Leaf Pack Network data?

**Comment by aufdenkampe** [comment]
Yes, that makes sense.
