### ISSUE TITLE
time stamps on 72hr pop-up tables - 24hr UTC

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#461]
Time stamps in the 72-hour pop-up tables associated with the sparkline plots are in 24hr UTC but the offset (-5) seems to indicate that it should be in EST - this seems to be an error.  Regardless, listing current local time along with UTC 24hr would be very helpful.

**Comment by aufdenkampe** [comment]
I think we're resolved this in our current development version (0.12-beta) on staging: https://staging.monitormywatershed.org.

@ptomasula, can you confirm and close if true?

**Comment by ptomasula** [comment]
I believe this was resolved with [Release V0.12.0](https://github.com/ODM2/ODM2DataSharingPortal/releases/tag/v0.12.0). The pop-up table appears to be reporting local time of the sensor along with UTC offset. The same is true of the sparkline plots, though no date information is actually plotted.
