### ISSUE TITLE
WOFpy not responding with data after release 0.11

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#465]
It appears tha WOFpy has not been giving responses for some sites since our [v0.11 Release](https://github.com/ODM2/ODM2DataSharingPortal/releases/tag/v0.11) on Thu. 1/23/2020.

Jeff Van Note emailed on Jan. 29:

> Since the weekend, I’ve noticed some trouble retrieving values from the end point for Monitor My Watershed.  This is an example of a call:
> https://monitormywatershed.org/wofpy/rest/1_1/GetValues?location=envirodiy%3ACWS-ThomasDairy3&variable=envirodiy%3ABosch_BME280_Humidity&startDate=2020-01-23T16%3A30%3A00&endDate=2020-01-23T16%3A40%3A00
>  
> This is the response I get back if I enter this URL:
>  ```bash
> <ns0:Fault xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/">
> <faultcode>soap11env:Server</faultcode>
> <faultstring>
> Values Not Found for CWS-ThomasDairy3:Bosch_BME280_Humidity for dates 2020-01-23T16:30:00 - 2020-01-23T16:40:00
> </faultstring>
> <faultactor/>
> </ns0:Fault>
>  ```
> If I log into the Monitor My Watershed site and open the time series, I can see values at Thomas Dairy 3 for humidity on this date.

However, going back in time (2019-11-23) for this same site seems to work:
https://monitormywatershed.org/wofpy/rest/1_1/GetValues?location=envirodiy%3ACWS-ThomasDairy3&variable=envirodiy%3ABosch_BME280_Humidity&startDate=2019-11-23T16%3A30%3A00&endDate=2019-11-23T16%3A40%3A00

I get a similar response for site [PR-ID1](https://monitormywatershed.org/sites/PR-ID1/):
- No response from 2020-01-23: https://monitormywatershed.org/wofpy/rest/1_1/GetValues?location=envirodiy%3APR-ID1&variable=envirodiy%3AEnviroDIY_Mayfly_Batt&startDate=2020-01-23T16%3A30%3A00&endDate=2020-01-23T16%3A40%3A00
- Response from 2019-11-23: https://monitormywatershed.org/wofpy/rest/1_1/GetValues?location=envirodiy%3APR-ID1&variable=envirodiy%3AEnviroDIY_Mayfly_Batt&startDate=2019-11-23T16%3A30%3A00&endDate=2019-11-23T16%3A40%3A00

Last, even when I do get a response, the two responses give me -9999.00.
I'll need to explore further if this is for all times or just that time.

@SRGDamia1 & @gcutrell, have you seen anything similar?

@tslawecki & @htaolimno, could this be related to issues connecting to our database server since we upgraded the routers? Or maybe because things aren't being redirected properly, such as mentioned in #456?

**Comment by SRGDamia1** [comment]
I haven't done anything calling WoFpy in ages.

**Comment by emiliom** [comment]
Hmm. I'll try to look into this around Friday. I'm currently out of town at a workshop.

**Comment by emiliom** [comment]
I haven't touched the WOFpy deployment in a long time -- unfortunately ...

**Comment by aufdenkampe** [comment]
New info via email from @vannotej:

> I made a notebook and looked a little more systematically at the issue.  I also took a look at a site in Puerto Rico.  I can look a little more next week, but I’ve found that I get data reliably from 10/15/2019 up to this specific time: 2019-12-09 07:00:00
>  
> That time is just the value I send to the DB – I’m not accounting for local time zones.  It is consistent for CWS sites and the one for Puerto Rico.  The increments I’m using are 10 minutes apart, so the first failure is for the range of 2019-12-09 07:10:00 to 2019-12-09 07:20:00
>  
> Up to that time, I get actual values as a measurement – not -9999.

**Comment by aufdenkampe** [comment]
It seems that @emiliom's recent troubleshooting work has fixed this issue! Thank you!

**Comment by SRGDamia1** [comment]
Is this fix live?  I'm still not seeing more than a single data point.

**Comment by SRGDamia1** [comment]
http://monitormywatershed.org/wofpy/rest/1_1/GetValuesForASite?site=envirodiy:BENNETTSRUN3&startDate=2020-09-01T00:00:00&endDate=2020-10-01T02:30:00

**Comment by emiliom** [comment]
Hi Sarah!! The single-data bug is a different problem. I'm not going to be able to fix it w/o funding support :cry:. The success now is that WOFpy is running, whereas it wasn't a week ago!

**Comment by aufdenkampe** [comment]
Yes, the fix is live. All sites are now providing one real data point for any time period with data.

Unfortunately, this fix didn't address **Fix WOFpy returning only most recent value #432** within the specified time interval. That issue has been around for a long time; one workaround is to just iterate though the time intervals.

We just reached out to CUAHSI to re-catalog our sites, so the sites appear in [CUAHSI HydroClient](http://data.cuahsi.org) and in Model My Watershed.

**Comment by SRGDamia1** [comment]
Oh, ok. Thanks!
