### ISSUE TITLE
Allow user to affiliate with more than one organization?

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#469]
Here's an example: it would be helpful to have the Delaware River Watershed Initiative listed as a filter on the Browse Sites so all of those sensor stations could be seen together. Right now, DRWI partners are affiliated only with their "home organization" (e.g., Great Marsh Institute). There's no way to show the reach of the project as a whole.

Also, how can the data portal accommodate the scenario of a user that changes affiliation over time? Or has sensor data and/or leaf pack data collected at the same time for more than one organization? For example, a teacher may have years of LPN data at one school, and then she moves to a different school and implements LPN there. Would that need to be handled by creating two different accounts, with two different email addresses?

**Comment by ScottEnsign** [comment]
This feature request touches the tip of an iceberg, and that is the need for users to provide more metadata about who they are (as a water data collector/sharer), who they work with, why they are monitoring, how they recommend the data be used (if at all), and who someone should contact if they have questions. Some of this info walks a tricky line with personal information, and we should obviously be cautious about overstepping. How can we force or encourage people to provide more metadata?

**Comment by dbressler75** [comment]
To follow up on Scott and Heather's comments, and at a much simpler level, there currently is no requirement for a station owner to even enter their organization, so for some sites the only info you have about the owner is their name (e.g., https://monitormywatershed.org/sites/1872ARTSCHOOL_CS/).  Possibly a low hanging fruit on this could be to simply require  an organization affiliation when registering a station.

**Comment by ptomasula** [comment]
The [Milestone for release 0.17](https://github.com/ODM2/ODM2DataSharingPortal/milestone/29) includes reworking to the code to allow users to be affiliated with multiple organizations. There still needs to be a URL mechanism developed to allow organizations to manage the users affiliated with their organization, but we now support the first portion of this request. 

We also support the second portion of this through a change to how site ownership works. We have now changed site ownership from an individual account to the organization level. So in the example use case @HeatherBrooks proposed, the LPN sites said teacher generated could remain owned by the organization that corresponds to each of the respective schools.
