### ISSUE TITLE
500 Server Error when leaf species not selected

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#470]
A user has reported getting a 500 error when submitting the leaf pack data entry form  “when don’t check off a leaf species ... even if I fill out the “Other” field to indicate experimental materials.” 

It sounds like the code is requiring leaf species. It should be optional because we offer the “Other” field not only for experimental materials but also for leaf species not listed (especially important for users outside of eastern US). 

I’m marking this as high priority because we hope to push Leaf Pack Network traffic to Monitor My Watershed this week. Thanks!

**Comment by aufdenkampe** [comment]
@htaolimno, is there any chance you might be able to fix this and push it as a Hotfix to production?

**Comment by htaolimno** [comment]
looks like a simple fix. I'll try hotfix it today.

**Comment by aufdenkampe** [comment]
Thanks!

**Comment by htaolimno** [comment]
@HeatherBrooks I just pushed the change to staging server. Please test it. thanks! An example link: https://staging.monitormywatershed.org/sites/ARSP_1/leafpack/19/

**Comment by HeatherBrooks** [comment]
@htaolimno, tested and I am now able to leave leaf species checkboxes unchecked and use the "Other" text box. Thanks!

I'm concerned that there might be another similar situation that I've missed. Can you tell me which fields are required on the leaf pack data entry page? I'd like to be sure our users aren't going to be tripped up by this.

As a side note, it looks like the experiments aren't being sorted by experiment date on the site page? 
![Annotation 2020-03-03 144146](https://user-images.githubusercontent.com/9368629/75813003-3b82f000-5d5d-11ea-8cb5-75d41d52b8d9.jpg)

**Comment by htaolimno** [comment]
@HeatherBrooks everything else are not required except for: Placement Date, Number of Packs Placed, Retrieval Date, and Number of Packs Retrieved.

**Comment by HeatherBrooks** [comment]
@htaolimno Excellent! Thanks so much for making the fix so quickly.

**Comment by htaolimno** [comment]
@HeatherBrooks  how about I sort the LPN by "Begin Date" decreasingly (newer first) ?

**Comment by HeatherBrooks** [comment]
@htaolimno Yes, newer first would be great.

**Comment by htaolimno** [comment]
@HeatherBrooks Great! Please check out the staging server. Example: https://staging.monitormywatershed.org/sites/VLA4-WBLSS/

**Comment by HeatherBrooks** [comment]
@htaolimno Looks good! (I accidentally went to the production site first and saw [my new tests](http://monitormywatershed.org/sites/WCC_TEST/) and the new ordering there too? Anyway, it looks good in staging and production.) We'll be announcing the new leaf pack data entry capabilities to our 1000+ educator list soon so I really appreciate you getting this done.

**Comment by aufdenkampe** [comment]
@htaolimno, nice work! I also really appreciate your timely response to this!
Did you also do those software updates? #464, #468? If so, thank you for those too!
