### ISSUE TITLE
MonitorMW Data Loss on Visualization Graph

### ISSUE THREAD

**Issue by d8kline** [ODM2/ODM2DataSharingPortal#471]
Hello Team,
We hosted a "Teach the Teacher" workshop this weekend to show educators how to use Monitor My Watershed in the classroom.

For one of the exercises participants were to select a specific date range and view the data. When scrolling over the visualization graph of the data we noticed that the data started at 01/07/2020 instead of 01/01/2020. We tried a few date ranges, and it seemed that the begin date needed to start on a Sunday for all of the data to be included in the visualization.

I tried this from home on Sunday and could not replicate the error. I tried here at work today and the error occurred again. I have attached a screenshot of the issue and included the instructions to get there below.

A few questions:
1. Is this normal? Do we need to select date ranges that start with "Sundays?"
2. When the graph does not display the full data for the selected date range, is the information in the Summary Statistics panel accurate for the entire date range or just what is displayed on the graph?
3. FUTURE FEATURE REQUEST: Add a button to the visualization tab to download just the data for the selected date range shown in the graph.

Any explanation or assistance would be wonderful as we are developing lesson plans and we will alter the directions to fit however the Monitor My Watershed tool works best.

Thank you!
David Kline

White Clay Creek 19m Upstream of Spencer Road (WCC019)
13. Click on the “Time Series Analyst” box above the individual variable graphs. A new tab will open displaying all of the variables measured at this site over the last month.
14. In the “Plot” column on the left click the boxes for all three Decagon_CTD-10 sensors (water depth, temperature, and electrical conductivity) as well as both Campbell_OBS3 Turbidity options.
15. Then click on the Visualization” tab above the variables and a graph will load showing all of the data for the selected variables over the last month.
16. Change the date range in the “Plot Options” box to a “Begin Date” of 1/1/2020 and an “End Date” of 1/31/2020, then click on “Plot” and wait for the new graph to draw.

At this point the graph showed only data from 1/7/2020 to 1/31/2020.
![Date Range Data Anomaly DTK](https://user-images.githubusercontent.com/61714400/75722410-28621880-5ca8-11ea-92a9-eeb0cd35164f.png)

**Comment by aufdenkampe** [comment]
@d8kline, thanks for this. It looks like a bug. We're working on funding so that we can address the accumulation of fixes and requests. Hopefully you've been able to work around this one.

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 

We think our new TSV addresses this issue, but we'll keep this issue open to track it.

**Comment by aufdenkampe** [comment]
We've completed our first round of work on TSV when we merged:
- #515

Its ready to test at https://staging.monitormywatershed.org/tsv/ or any of the usual places where you previously to launched TSA.

Note that the data are not yet fully synced with our production database, so recent data is missing. We may not be able to fully test this until we release to production.

**Comment by aufdenkampe** [comment]
Our new TSV seems to be showing all the data on our staging servers at  https://staging.monitormywatershed.org.

Closing this issue.
