### ISSUE TITLE
Sparkline plots & TSA not connecting to database

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#473]
As of at least 2020-03-15 we're again experiencing connection issues with our InfluxDB database that we use to support sparkline plots and Time Series Analyst (TSA). Thanks @dbressler75 for the heads up.

This issue is similar to #448, #436, etc. The long-term fix unfortunately requires an architectural overhaul, as described in #434.

Fortunately, the data are safe, as they are being stored in a separate database. 

We'll work on a hot fix.

**Comment by aufdenkampe** [comment]
Two updates from @tslawecki.

March 17:
> I've taken a first look, confirming that all SSL certificates are in place and valid, and that the necessary services are running on both the web and database servers. I restarted the tsa and influxdb services, but the data are still not being accessed. I will start a deeper dive, and report again later tonight ofr first thing in the morning.


March 18:

> There was another strange issue with security certificates which I think I've addressed by renewing the cert for dbs.monitormywatershed.org. Please check and advise.
> 
> The strange issue is that when I checked the certificate on the database server, it showed 
> 
>     Domains: dbs.monitormywatershed.org
>     Expiry Date: 2020-06-02 16:33:09+00:00 (VALID: 75 days)
> 
> However, when I did a test query directly (copying the query used in the SiteDetails page to access data into a browser address bar), I was notified that the certificate had expired four days ago. I renewed the certificate, and now have
>
>     Domains: dbs.monitormywatershed.org
>     Expiry Date: 2020-06-16 20:24:29+00:00 (VALID: 89 days)
>
> I will check the forums to see if there are any similar issues reported. Otherwise, I'll note in Github that when this situation arises again we shouldn't trust the certbot report and should then do a similar manual test.

**Comment by aufdenkampe** [comment]
It all seems to be working now. Thanks @tslawecki

**Comment by dbressler75** [comment]
@tslawecki and @aufdenkampe , thanks so much for your quick response on this, very much appreciated!  There were a lot of people asking about what was going on - so lot's of people paying attention to their data, which is great.
