### ISSUE TITLE
tsa graph labels overlap (not readable) and persist when variable not clicked 

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#474]
When hovering over graphs the labels overlap and are not readable.  Also, the labels persist even when the variables are not clicked on in the side bar.  See attached. 
![tsa_graphs_labelsoverlap_persistwhennotclicked](https://user-images.githubusercontent.com/39309124/77319444-39b9a600-6ce5-11ea-8ba0-cdbbdb7bfcd7.PNG)

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization System, starting with:
- #512

Closing this issue, which should be fixed with our migration.
