### ISSUE TITLE
Allow embedding Monitor My Watershed content in Google Data Studio

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#479]
@aufdenkampe @htaolimno I'm hoping this might be an easy setting change?

From email conversation with a Delaware River Watershed Initiative partner:
"I am building a Google Data Studio platform for displaying the Musconetcong Watershed Association's water quality data and as part of that I wanted to embed a hyperlink to each sensor we have online. However, when I go to embed it it gives me a message that it can't due to provider site restrictions, do you have any work arounds or advice for this?"

From [Google Data Studio Help](https://support.google.com/datastudio/answer/9132022?hl=en):
"You can embed virtually any content that is accessible via a URL. However, **the provider of that content must allow it to be embedded**, and the content must be visible to your report viewers. If you try to embed content from a blocked site, the embedded content box will remain blank, and you'll see an error in the External Content URL field."

**Comment by aufdenkampe** [comment]
@HeatherBrooks, hmm. We can look into that and see if it could be implemented as a quick hot-fix.

@tslawecki, is there any chance that this is a setting for our virtual machine or router? Or is it more likely an nginx or Django setting?

**Comment by HeatherBrooks** [comment]
@aufdenkampe @tslawecki Have you had a chance to look into this? Our watershed partner has emailed again.

Good Morning,
I had contacted you a few weeks back about embedding a URL for our sensor stations into Google Data Studio and was wondering if you have heard back about the permissions or a work around for that? 
Thanks,
Christa Reeves
Water Quality Field Specialist
Musconetcong Watershed Association

**Comment by tslawecki** [comment]
Heather,

Apologies for not following up earlier. I’ll reach out to Christa and ask her for an example URL.

Tad

**Comment by tslawecki** [comment]
Christa figured out the issue with help from Adam Griggs at the River Network. She wrote today after I reached out to her:

> I talked to Adam Griggs at River Network and he figured it out, I needed to create a text hyperlink instead of embedding the URL. So, if anyone in the future needs to do this for Data Studio that's what you do, highlight the text and on the panel to the right there is an option to create a text hyperlink (in Edit view) and you just input the link there. It is confusing because Data Studio gives you the option to paste a URL, which I have done with YouTube videos no problem, but with a basic page link like this it kicks it back. PHEW!

**Comment by aufdenkampe** [comment]
@tslawecki, thanks for following up!
