### ISSUE TITLE
Update WOFpy to latest commits, latest versions of dependencies

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#486]
There are 48 commits on the develop branch since the last release (v2.3.0).
 
For upgrading to Python 3, see https://github.com/ODM2/WOFpy/issues/231 and the discussion in PR https://github.com/ODM2/WOFpy/pull/230 (which was never merged).

**Comment by aufdenkampe** [comment]
@emiliom, as we think about kicking off the next development round in early December, let's list out what dependencies might benefit from updating.

**Comment by emiliom** [comment]
I realize this issue has been closed but given the parting comments @aufdenkampe made, I'd like to add some clarifications:

> CUAHSI is building a new cyber-infractructure that will not use WOF or WaterML 1.1, so these will be functionally deprecated in the next two years.

I'd need to look at my notes, but I think the timeline for support is likely more than 2 years. But that support will most likely entail no new developments, and as alternatives are developed and deployed the robustness of that support will invariably degrade.

> USGS is on the path to fully adopting OGC SensorThings API and OGC Environmental Data Retrieval (EDR) API. Both are still in their infancy and have no client libraries, so we are waiting for things those software ecosystems to mature.

- A SensorThings Python client is emerging, https://github.com/NMWDI/PySTA, though it's definitely still in its infancy.
- For EDR, I'm not aware of a dedicated client, but EDR is built on the OGC API set of standards. Those are supported by the robust, long-standing and widely used https://github.com/geopython/OWSLib package. Though I can't find direct examples, it's quite possible that most, if not all, EDR client requests can already be constructed with OWSLib.

**Comment by aufdenkampe** [comment]
@emiliom, thanks for those clarifications and also the links to those client libraries for the newer OGC APIs!  I appreciate you sharing!

**Comment by aufdenkampe** [comment]
I just found two other very new Python client libraries for OGC SensorThings API:
- https://github.com/zMoooooritz/stapy 
- https://github.com/FraunhoferIOSB/FROST-Python-Client
