### ISSUE TITLE
Add a marker at each data point in TSV graphs?

### ISSUE THREAD

**Issue by mbarneytu** [ODM2/ODM2DataSharingPortal#490]
When you look at a chart of, say battery voltage, it looks as though the value is holding steady during a time when there was actually no data being sent due to poor cell signal or low battery. In other words, the TSA plot shows a solid line but, unless you move your mouse over the line and watch for the values to change, you don’t realize that the data are in fact discontinuous. This would be more straightforward if there was an option to either a) place a dot/marker at each data point (similar to Excel’s “Line” vs. “Line with Markers”), or b) plot only the points, without a continuous line between them.

**Comment by aufdenkampe** [comment]
TSV shows individual points once zoomed in close enough that the user would be able to distinguish the points.
