### ISSUE TITLE
MonitorMyWatershed is down

### ISSUE THREAD

**Issue by mbarneytu** [ODM2/ODM2DataSharingPortal#491]
monitormywatershed.org page won't load. Sometimes returns a gateway timeout. Issue also reported at https://www.envirodiy.org/topic/mmw-is-down/.

**Comment by tslawecki** [comment]
Thanks. We are looking into this.

**Comment by tslawecki** [comment]
Quick update. We are looking at a possible (internal) DNS issue and also a possible need to increase the number of allowed connections.

**Comment by tslawecki** [comment]
Update - A likely cause has been identified. A catch-up archiving/backup job was scheduled for the server's virtual host that took up more resources than planned. We are terminating the job and will re-assess.

**Comment by tslawecki** [comment]
We terminated the job, but had to restart the virtual host. Service seems back to normal. The road to downtime seems paved with good intentions like backups - but we can be smarter going ahead in implementation.

**Comment by aufdenkampe** [comment]
@tslawecki, thanks for your responsive sleuthing and fixing of this problem!
