### ISSUE TITLE
Pass parameters to URL so that organizations can share a link to a map of their sites

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#500]
Request received through the contact form on WikiWatershed.org:

> I am using the http://www.monitormywatershed.org/browse/ map and would like to share a link that opens the map directly to the Lynchburg Water Resources organization sites. Is it possible to pass these parameters through the URL?

This is not unrelated to requests we've received for the ability to embed Monitor My Watershed site data in other websites. Is there a plan for something like this? I think that if you were able to pass parameters to the URL, people could use that URL to create an iframe to embed in their own website. Caveat: iframes can only display content from sites with the same Hypertext Transfer Protocol. Since MonitorMW is currently HTTP, you could only embed in sites that also use HTTP (not HTTPS). 

There is probably a more elegant way to approach this but I thought I should mention it here so the team is aware that there are requests for this functionality.

**Comment by HeatherBrooks** [comment]
@aufenkampe, I received another request for this functionality. I see you marked it as part of a milestone from a year ago. Any update to the timeline?
"We've recently installed some EnviroDIY Mayfly CTD monitors in our area with the intent of sharing the data with the public on our websites.  However, it appears that we can't embed the monitormywatershed graphs on our website via iframe or other means.  It would be very valuable for the organizations that invested in these stations to be able to do that.  Our supporters have generously donated for these stations and would like to see the product of our efforts on our websites (Spokanefallstu and spokaneriverkeeper).  Is there any way to make these graph pages embeddable?"

**Comment by ptomasula** [comment]
@HeatherBrooks 
I'm not sure when/if we will be adding embedding support, for the map, but our latest round of funding for StreamWatch Schools updates includes the ability to preselect those map filters based on url parameters. So I think that will at least address this issue when we implement that.

**Comment by ptomasula** [comment]
Tagging related issue which will implemented this feature. #670

**Comment by ptomasula** [comment]
This feature was added with [Release 0.16.0](https://github.com/ODM2/ODM2DataSharingPortal/releases/tag/v0.16.0).
The query parameter `organizations` followed by a comma delimited list of organizations is now supported by the browse sites page. 

For example the url [https://monitormywatershed.org/browse/?organizations=Stroud%20Water%20Research%20Center](https://monitormywatershed.org/browse/?organizations=Stroud%20Water%20Research%20Center) should display only Stroud Water Research Center's sites.
