### ISSUE TITLE
Update Deployment Guide on `develop` for Python 3 release; including how to set up private `settings.json` files

### ISSUE THREAD

**Issue by thuongtonphapluat1988** [ODM2/ODM2DataSharingPortal#503]
Can you help me clarify some details to complete the installation:
1. Can I create an environment from a .yml file, such as environment_py38_dj22.yml? How I can do it ?
2. If I use environment_py38_dj22.yml, do I need to install from requirements.txt anymore?
2. In step 6, what parameters do I need to edit in settings.json

Thanks and looking forward to everyone's responses.

**Comment by aufdenkampe** [comment]
Connecting to:
- #545
- #549

**Comment by kieutuandung-aptech-vn** [comment]
> Connecting to:
> 
> * [Missing Config repo #545](https://github.com/ODM2/ODM2DataSharingPortal/issues/545)
> * [Update Deployment Guide and related docs for releases >0.12 #549](https://github.com/ODM2/ODM2DataSharingPortal/issues/549)

Dear Sir!
Thanks for your feedback. I hope this ecosystem will be supported to grow continuously. There are many scientists in my country who are interested and look forward to receiving help and cooperation. I'm happy to see the upgraded version of ODM2DataSharingPortal.

**Comment by aufdenkampe** [comment]
With our release of v0.12.0 and v0.12.1, we now have a Python 3 deployment guide in place. It still needs some work, but we'll track that in:
- #549
