### ISSUE TITLE
TSA display different than downloaded CSV

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#504]
When displaying a tsa plot of fast changing Vbat from 4.109 to 3.563 to 4.109 the line plot doesn't seem to follow the recorded data.
The TSA graphs identifies UTC.  
I would expect the TSA graph (UTC) and the downloaded data (UTC) to match, data point for data point.
It seems like the TSA is being filtered.
If it is being filtered I would expect an option or the raw data to be viewed. This could be Visualization sub menu - "Time Series (Raw)"

Possibly I'm not seeing why these are different - I think I've done everything right

Using the site Ivy_link  for one day of UTC  2021-08-25  
selecting start 8/25/2021 and end 8/26/2021
The TSA plot is 
![20210825 Ivy_link_Vbat_TSA](https://user-images.githubusercontent.com/2766619/135004057-55a20774-814e-431a-ba92-1e1d9bad6b4f.jpg)

The plot from the downloaded data for the same day UTC is 

![20210825 Ivy_link_Vbat_csv](https://user-images.githubusercontent.com/2766619/135004062-235e8125-4754-4513-8517-98697cba2c1a.jpg)

If it is being filtered, I would expect the Visulation Histogram to be use the raw data. Using data for 8/24 to 8/25 the Historgram option doesn't appear to be accurate.

![20210824 Ivy_link_Vbat_csv](https://user-images.githubusercontent.com/2766619/135004375-9650e086-eadf-4e4c-a309-587dc8d3d6d3.jpg)

TSA Time Series

![20210824 Ivy_link_Vbat_TSA](https://user-images.githubusercontent.com/2766619/135004388-cba1f7e3-aec0-4fa1-ae65-c1987b2f6c2d.jpg)

TSA Histogram

![20210824 Ivy_link_Vbat_Histogram](https://user-images.githubusercontent.com/2766619/135004569-72065cf1-38ed-4a78-ba74-3f404940de5c.jpg)

The downloaded data is 
[Ivy_link_TimeSeriesResults_2108242days.xlsx](https://github.com/ODM2/ODM2DataSharingPortal/files/7240151/Ivy_link_TimeSeriesResults_2108242days.xlsx)

**Comment by aufdenkampe** [comment]
We have decided to replace TSA with a Time Series Visualization (TSV) page, starting with:
- #512

Check out the screenshots I just posted with https://github.com/ODM2/ODM2DataSharingPortal/issues/512#issuecomment-957935317. 

We think our new TSV addresses this issue. Specifically, TSV will be fetching data for display and download using the exact same code and database as for the main web app. The results will be identical.
