### ISSUE TITLE
Browse map: site goes to gray even though data are there

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#505]
When a new parameter is added to an existing site that has data, it changes the site's map color to grey because now the last parameter on the page hasn't ever been received.  Not a major issue but ideally if there are data associated with a site it would always register as red or another color but not grey.

**Comment by neilh10** [comment]
I'm seeing this with https://monitormywatershed.org/sites/TUCA-Na13/

Its a site that is receiving regular updates, every 15miuntes shows as grey. It has one UUID "Mayfly Temperature" not being used, 2nd from last on the list of UUIDs/
![image](https://user-images.githubusercontent.com/2766619/135527741-63f201ad-b45b-4e07-9759-f57acdc02042.png)

The other site on the list, also receiving regular updates is green, and has all its UUIDs in use.
https://monitormywatershed.org/sites/TUCA_PO03/

**Comment by aufdenkampe** [comment]
This appears fixed, and it probably happened with https://github.com/ODM2/ODM2DataSharingPortal/pull/617 and related work in the v0.14 release.
