### ISSUE TITLE
Upgrade Django from v2.2 to v3.2 LTS

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#507]
We should upgrade to Django 3.2 LTS by April 2022.

With PR #501 we upgraded Django to v2.2. See:
- #385

Unfortunately, Django 2.2 LTS end-of-life is April 2022. 
[Django 3.2 LTS](https://www.djangoproject.com/weblog/2021/apr/06/django-32-released/) was released in April 2021.

![Django Supported Versions](https://static.djangoproject.com/img/release-roadmap.png)

Here's [What's new in Django 3.2 LTS](https://theorangeone.net/posts/django-32/) compared to 2.2 LTS.

The main feature of Django 3 is support for ASGI (Asynchronous Server Gateway Interface), which is a successor to Python WSGI (Web Server Gateway Interface). Let's explore ASGI when we work on #431.

**Comment by ptomasula** [comment]
We've been testing the [Techdebt-refactoring](https://github.com/ODM2/ODM2DataSharingPortal/tree/Techdebt-refactoring) feature branch with Django LTS 3.2 and python 3.9. I've update the [environment.yml](https://github.com/ODM2/ODM2DataSharingPortal/blob/Techdebt-refactoring/environment.yml) file to reflect this. We'll be on this tech stack once we do our next scheduled release.
