### ISSUE TITLE
Server Error (500) on all sites

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#509]
When I try 
https://www.monitormywatershed.org/browse/

and access any of my sites - gives me Server Error (500)

at 07:45am (PST)  received not received any new data values in the last 4 hours
https://www.monitormywatershed.org/sites/LCC45_test02/
https://www.monitormywatershed.org/sites/TUCA-Na13/
https://www.monitormywatershed.org/sites/TUCA_PO03/

**Comment by aufdenkampe** [comment]
@neilh10, Thanks for pinging us. We noticed that issue this morning. It started last night and is connected to an issue that surfaced early this summer.
 
We implemented a short-term fix, but that's not sticking.

We know what the long-term fix is, but it's a bit more complicated to implement. We should have that done by this evening. It may fail on and off a few times until then.

**Comment by aufdenkampe** [comment]
We think we've got it resolved (thanks @ptomasula!). 

The main MMW site is back up and data looks to be flowing to the database server again.

We're rebuilding the tsa_catalog now, so there might be some short term glitches with interactions to TSA capabilities and sparkline plots.

Unfortunately, some data was lost last night, before were able to address any of this.

**Comment by neilh10** [comment]
Just an FYI - my sites which have a reliable data transfer algorithm -  I believe lost data transferring then to MMW today. 

That is, as shown by the incrementing sequence number, the Mayfly received a Response Code 201. for  a reading, 
However when downloaded there are missing records. 
LCC45_test02 - 63 records between UTC 2021-10-18  4:22:00 PM  & 2021-10-18  6:28:00 PM Seq# 655 to 717
turc_test06 lost 40 records between UTC 2021-10-18  4:10:00 PM  & 2021-10-18  5:32:00 PM Seq# 650 to 689
turc_test06 lost 4 records between  2021-10-18  6:22:00 PM  &  2021-10-18  6:30:00 PM  Seq# 714-717

So the failure on MMW was a good opportunity for me verify the ModularSensors--MMW reliable transfer algorithms to see how they coped with a total MMW failure - in this a case the tcp/ip request never completed.
Once MMW became available, and turc_test06  tcp/ip link was setup, then MMW responded with a '201'
021-10-18 11:28:42] POST /api/data-stream/ HTTP/1.1
[2021-10-18 11:28:42] Host: data.envirodiy.org
[2021-10-18 11:28:42] TOKEN: e89538ae-7ff0-4897-a396-9b10c0fadfc3
[2021-10-18 11:28:42] Content-Length: 460
[2021-10-18 11:28:42] Content-Type: application/json
[2021-10-18 11:28:42] 
[2021-10-18 11:28:42] {"sampling_feature":"31461753-cd5d-4ed0-99f7-17713c5e1e0e",
"timestamp":"2021-10-18T08:10:00-08:00",
"b404d204-f127-44d4-869c-50c058412999":**650**,
"d395b5f7-c9c4-4c99-a919-4c4869cbc288":4089.361,
"013225a5-b2ba-4f0d-ba99-3f38599e0672":0.893,
"32b6fb1f-4688-4fb0-ada7-323753536c08":3.9211,"be84dc61-86dd-4ff9-9c44-f1d25bd78f6b":5.397,"a4361b13-a4b4-4d53-b1c8-1398d73ceeec":0.03127,"b40cdca7-22c5-4d6e-91db-4eb77ebf2179":9.37,"83fb7c9a-9af5-4bff-874a-d780045c19f0":-69}
[2021-10-18 11:28:42] 
[2021-10-18 11:28:45] -- Response Code -- 201 waited  977 mS Timeout 5000

Since ModularSensors/Mayfly got a sucessful 201, it POSTED 20 records 650 to 669, that all had response code 201, but didn't make it into the downloadable .csv   If it had received anything other than a 201 it would have stopped attempting the POST.

I have seen this before.  So a heads up for you about the data loss, and whether you understand the new algorithms on AWS have better reliability for processing the records.  Possibly a sequence problem that POSTs are accepted before the rest of the modules are ready to accept the records??

If you wanted me to verify the other response code 201's that failed happy to work through them..

[tu_rc_test06_TimeSeriesResultsA.xlsx](https://github.com/ODM2/ODM2DataSharingPortal/files/7369310/tu_rc_test06_TimeSeriesResultsA.xlsx)
[LCC45_test02_TimeSeriesResultsA.xlsx](https://github.com/ODM2/ODM2DataSharingPortal/files/7369311/LCC45_test02_TimeSeriesResultsA.xlsx)

**Comment by ptomasula** [comment]
Thanks @neilh10 

This is good information to have. I agree that some work needs to be done on the algorithms. Presently that codes lacks proper exception handling, so it will continue and return a 201 response in instances where it should not. I've opened issue #510 to track this problem. 

Thanks again for the great feedback.
