### ISSUE TITLE
Develop basic time series visualization to replace TSA

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#512]
Although Time Series Analyst (TSA) has a lot of valuable functionality -- particularly with interactive visualization of time series data -- it  has a lot of redundancy of features with the main Monitor My Watershed web app ([ODM2DataSharingPortal](https://github.com/ODM2/ODM2DataSharingPortal)). See:
- #463

TSA also is built on fully separate codebase ([WEBTSA](https://github.com/LimnoTech/WEBTSA)) that itself works with a different database system (InfluxDB) and is build around the ODM1 data  schema. Integration required an entire ODM2 to ODM1 translation engine to be build, maintaining a separate TSAcatalog database instance to manage the crosswalk. This extra infrastructure has been the root cause of most of our challenging this data portal. See:
- #434

Last, a long requested feature is to have data QA/QC capabilities, which would naturally sit on top of the time series visualization interface.

The best solution to all this is to replace TSA with a new interactive visualization system that has potential for future feature growth.

This issue gets us started down this path, by building a basic interactive visualization that has the capability to:
- zoom, scroll and pan through a time series
- adjust Y axis scaling
- overlay multiple time series measured at the same site

**Comment by aufdenkampe** [comment]
@ptomasula has a Time Series Visualization (TVA) prototype working on our development server! We'll be deploying this to our staging servers by the end of next week!

Here are some screenshots for now:

### Standard View:

<img width="960" alt="TSV_StandardView" src="https://user-images.githubusercontent.com/5166036/139908450-88f0bdb0-4a96-45de-92d6-f1cd26ce06ef.png">


### Close up of Series Selector:

<img width="293" alt="TSV_SeriesSelector" src="https://user-images.githubusercontent.com/5166036/139908786-161e34fe-5e2d-453b-b249-a01c1a5ef2d6.png">


### Close up of Menu Options:

<img width="228" alt="TSV_MenuOptions" src="https://user-images.githubusercontent.com/5166036/139908805-9e51f8ca-a47e-439a-9563-fa59e4bf390d.png">


### Full Screen mode:

<img width="960" alt="TSV_FullScreen" src="https://user-images.githubusercontent.com/5166036/139908764-1f9b13ae-a629-4f0b-a558-35f48b2ba861.png">

**Comment by neilh10** [comment]
Wow looks like its coming along. 
Let me know when you feel its in good enough shape for some testing on it, and how you want the feedback. :)

**Comment by aufdenkampe** [comment]
We've completed our first round of work on TSV when we merged:
- #515

Its ready to test at https://staging.monitormywatershed.org/tsv/ or any of the usual places where you previously to launched TSA.
