### ISSUE TITLE
Customize WOFpy client pages?

### ISSUE THREAD

**Issue by emiliom** [ODM2/ODM2DataSharingPortal#516]
@aufdenkampe The WOFpy client pages (starting in https://monitormywatershed.org/wofpy/) can be customized. The static text in the pages can be easily changed. We can rework the banner title, remove the section that points to the old WOF/WaterML 1.0 services, and so on. There are also a couple of dynamic elements that can be easily customized, such as the site (`160065_Limno_Crossroads`) that's used for all the REST examples.

Simple changes to content would be easy. Bigger changes involving the HTML styles and structure are something I don't have the time (or interest) to get into.

We can discuss this if it sounds appealing.

**Comment by aufdenkampe** [comment]
@emiliom, thanks for creating an issue for this.
I had noticed the footer that you had created on these pages as a placeholder, and was thinking that its time for an update.

In the next week, I'll review the pages and suggest edits to the text.

**Comment by emiliom** [comment]
The HTML templates for those pages are in https://github.com/ODM2/WOFpy/tree/master/wof/flask/templates

The user-customizable settings that get populated in those templates are found mostly in this config file: https://github.com/LimnoTech/ODM2DataSharingPortalConfig/blob/master/wofpy/wofpyserver_prod/odm2/timeseries/odm2_config_timeseries.cfg

(obviously, that's not the one actually being used in the AWS instance)

**Comment by aufdenkampe** [comment]
@emiliom, I know this should be a task that I take on, but I'm being pulled in too many places. 

Could you take this on and make updates based on:
- My contact info in my email signature footer
- Delaware River Basin spatial context
- Links to https://wikiwatershed.org/monitor/
- Example site: https://monitormywatershed.org/sites/WCC019/
  - Which is the first EnviroDIY site ever deployed (we used 160065_Limno_Crossroads in 2017 because WCC019 was still streaming to the legacy site at that time).
  - Date Range: Aug 1, 2021 to Sep 30, 2021
  - Variables for examples:
    - Decagon_CTD-10_Depth
    - Decagon_CTD-10_Cond
    - Decagon_CTD-10_Temp

Thanks!

**Comment by aufdenkampe** [comment]
@emiliom, is this somethin

**Comment by emiliom** [comment]
@aufdenkampe while trying to work on this, I was unable to ssh into the AWS instance (18.117.19.92). The connection attempt times out. Has anything changed? The WOFpy server itself is online, though it seems to be very slow.

**Comment by aufdenkampe** [comment]
@emiliom, I just did a quick look and found that we did change our security group settings to only allow SSH from specific IP addresses. Let's continue that conversation via Teams.

**Comment by emiliom** [comment]
Updated `$HOME/wofpyserver_prod/odm2/timeseries/odm2_config_timeseries.cfg` with the following information:

```ini
[Contact]
# I've blocked some of the information here (XXXXX)
Name: Anthony Aufdenkampe
Phone: XXXXX
Email: XXXXX
Organization: MonitorMyWatershed
Address: XXXXX
City: Oakdale
State: MN
ZipCode: 55128
Link: https://wikiwatershed.org/monitor/

[Default_Params]
Site: WCC019
Variable: Decagon_CTD-10_Temp
StartDate: 2021-08-01T00:00:00
EndDate: 2021-09-30T23:59:00

[Default_Params_1_1]
West: -76.5
South: 38.5
East: -74
North: 42.5
```

**Comment by aufdenkampe** [comment]
@emiliom, that looks great! Thanks!!

**Comment by emiliom** [comment]
Great.

As for closing this issue now, it depends on whether you see value in the other, more involved (but not hard) customizations I mentioned:

> The WOFpy client pages (starting in https://monitormywatershed.org/wofpy/) can be customized. The static text in the pages can be easily changed. We can rework the banner title, remove the section that points to the old WOF/WaterML 1.0 services, and so on. There are also a couple of dynamic elements that can be easily customized, such as the site (160065_Limno_Crossroads) that's used for all the REST examples.
>
> Simple changes to content would be easy. Bigger changes involving the HTML styles and structure are something I don't have the time (or interest) to get into.

What I've changed at this time is this (changed parameter values in one configuration file):
> There are also a couple of dynamic elements that can be easily customized, such as the site (160065_Limno_Crossroads) that's used for all the REST examples.

**Comment by aufdenkampe** [comment]
@emiliom, thanks for pointing out that I missed some of the other potential customizations that you mentioned when opening this issue.

I'm OK with calling this issue as closed for now with these recent modest update, especially given our interest in migrating toward other web services.

**Comment by emiliom** [comment]
Sounds good. Thanks
