### ISSUE TITLE
smmw: Sampling feature UUID is null

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#518]
When looking at 
https://staging.monitormywatershed.org/sites/tu_rc_test07/
and bringing up the VIew Token UUID
it has a missing "samplingFeature"
const char *registrationToken = "0af40c10-cbd5-4a7d-b78c-79ca06553e54";   // Device registration token
const char *samplingFeature = "";     // Sampling feature UUID

I would expect this to be the same as on the the 
https://monitormywatershed.org/sites/tu_rc_test07/
const char *registrationToken = "0af40c10-cbd5-4a7d-b78c-79ca06553e54";   // Device registration token
const char *samplingFeature = "1e77a2de-11a7-4f4c-9237-668384eb3a18";     // Sampling feature UUID

When trying to do a post with this null or with the standard value it doesn't work, 

Client connected after 359 ms <--EnviroDIYPublisher
POST /api/data-stream/ HTTP/1.1
Host: staging.monitormywatershed.org
TOKEN: 0af40c10-cbd5-4a7d-b78c-79ca06553e54
Content-Length: 500
Content-Type: application/json

{"sampling_feature":"","timestamp":"2021-11-16T10:42:00-08:00","645d6ee6-c42a-4cee-9191-5a7e6a331a4c":2,"efe0e9a3-cd63-4e82-a025-7b3d2d4da18b":-0.670,"af45f842-68de-481b-9375-0788d5f13868":4.0162,"e9596fd4-35e9-4271-aab0-661aab3dd772":3.957,"e8011385-91ea-487e-a0a5-582ec4f0d906":17.66,"f762c642-33a0-4baa-a4e9-fff2d62411e5":-0.0019,"1be5346c-c59e-47b7-ade7-d71a5e841c54":71.9,"ae401cf2-8680-4a66-9bc9-5fe78bf10713":18.5,"c0222eb2-4c63-4050-a8cf-6ae2ce68bae7":-24}

 [[Client waited 3107 mS for 12 bytes. <--EnviroDIYPublisher
Client stopped after 735 ms <--EnviroDIYPublisher
Rsp:' HTTP/1.1 301 ' <--EnviroDIYPublisher

------------------------------------

Client connected after 467 ms <--EnviroDIYPublisher
POST /api/data-stream/ HTTP/1.1
Host: staging.monitormywatershed.org
TOKEN: 0af40c10-cbd5-4a7d-b78c-79ca06553e54
Content-Length: 499
Content-Type: application/json

{"sampling_feature":"1e77a2de-11a7-4f4c-9237-668384eb3a18","timestamp":"2021-11-16T10:50:47-08:00","645d6ee6-c42a-4cee-9191-5a7e6a331a4c":1,"efe0e9a3-cd63-4e82-a025-7b3d2d4da18b":0.000,"af45f842-68de-481b-9375-0788d5f13868":4.0114,"e9596fd4-35e9-4271-aab0-661aab3dd772":3.957,"e8011385-91ea-487e-a0a5-582ec4f0d906":17.68,"f762c642-33a0-4baa-a4e9-fff2d62411e5":-0.0019,"1be5346c-c59e-47b7-ade7-d71a5e841c54":71.8,"ae401cf2-8680-4a66-9bc9-5fe78bf10713":18.5,"c0222eb2-4c63-4050-a8cf-6ae2ce68bae7":-19}

 [[Client waited 471 mS for 12 bytes. <--EnviroDIYPublisher
Client stopped after 740 ms <--EnviroDIYPublisher
Rsp:' HTTP/1.1 301 ' <--EnviroDIYPublisher

-----------------------------------

https://en.wikipedia.org/wiki/HTTP_301  Says the server is redirecting
When enabling the STREAMDEBUGGER
it seems the server is responding with something like (and some chars may be lost managled)
HTTP/1.1 301 [[Client waited 205 mS for 12 bytes. <--EnviroDIYPublisher
 Moved Permanently
Server: nginx
Date: Tue, 16 Nov 2021 19:02ncin epaie
oain tp:/tgn.oiomwtrhdog/p/aa-tem

**Comment by aufdenkampe** [comment]
@neilh10, it seems like our data synchronization from production to staging isn't working perfectly.

@htaolimno, can you look into this?

**Comment by htaolimno** [comment]
@neilh10 I just updated both dataloader and odm2 data to the about an hour ago. Not sure this solves the problem.

**Comment by htaolimno** [comment]
The issue is that the samplingfeatures table is out of sync. I am working on updating those tables.

**Comment by htaolimno** [comment]
@neilh10 I've got all the tables in odm2 schema updated. I just checked the UUID using your link. Please verify. Thanks.

**Comment by aufdenkampe** [comment]
@neilh10, I think you should now be able to move forward with your testing of HTTP POST Requests from devices.

However, because of some nuances of the various PostgreSQL database replication approaches, we can't BOTH keep staging perfectly in sync with production (inducing primary keys) AND also receive new data into staging. The workaround that @htaolimno and I just settled on is to do a perfect sync every morning at 4 am ET / 1 am PT, which will over-write all your testing data. This will give you a full day to start and complete a test.

@SRGDamia1, we're hoping that you can also set up some tests of HTTP POST Requests to staging, so you will also need to be aware of this 1-day constraint.

We'll shift to hourly syncing after we're done testing and starting a day or two before the scheduled release (presently scheduled for the first days of December).

**Comment by neilh10** [comment]
@aufdenkampe that sounds perfectly reasonable. 
as a "staging" website I am using it as only testing, throw away in the end

My take its perfectly reasonable for testing that any data sent to  staging won't make it to the  production, and I understand your rationale on sinking staging with production, that will give everyone the chance to see how their data shows under the new graphing.

Just wondering though, from the point of view of a complete test including POSTings to display,  if  I create a completely newsite  on staging.monitormywatershed.org, that doesn't exist on the production,  will it be wiped out each night. ?

I haven't had the chance to test the posting to staging.monitormywatershed.org, but hope to in the next couple of hours.

**Comment by aufdenkampe** [comment]
@neilh10, yes, if you create a new site or variable on staging, it will be completely gone the next morning, unfortunately.

Thanks for offering to do this testing. It will be very helpful!

**Comment by neilh10** [comment]
I see the same UUIDs for https://staging.monitormywatershed.org/sites/tu_rc_test07/
thanks very much
