### ISSUE TITLE
smmw: using DateTimeUTC

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#519]
The display date in the graphs is DateTimeUTC 
I would expect it to be the local time "DateTime", which is the date that is posted, and visible in the downloaded .csv

Possibly as an option it could reference DateTimeUTC if that is needed in some applications, but the default should be the supplied local time.

From downloaded tu_rc_test06_TimeSeriesResults.
DateTime               DateTimeUTC                EnviroDIY_Mayfly_SampleNum
2021-11-14 15:08   2021-11-14 23:08          1648

From 
https://staging.monitormywatershed.org/tsv/tu_rc_test06/3816/
the last datapoint is SampleNum=1648 and time Nov14, 23:08

![image](https://user-images.githubusercontent.com/2766619/142051399-9afe1478-63ae-4e26-ac1a-216a3512aa61.png)

**Comment by aufdenkampe** [comment]
Thanks! We'll look into this!

**Comment by ptomasula** [comment]
Thanks @neilh10 

This has been corrected with commit [ba9fae0](https://github.com/ODM2/ODM2DataSharingPortal/commit/ba9fae0057d0f2e8fa9980eb70658ccab2565390). The time is now correctly converted from UTC to local sensor time and is live on the staging server. Let us know if you are still observing this issue.  
![image](https://user-images.githubusercontent.com/31142705/142079905-1aad410e-7dcf-43e2-950c-6a3f0467c954.png)
