### ISSUE TITLE
smmw: Date Range not set

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#520]
On Displaying a TSV graph 
https://staging.monitormywatershed.org/tsv/tu_rc_test06/3816/
the graph automatically incorporates a date range, but this range is not set in the "Date Range" area.

This is pretty minor, but it would be nice if it could be set per the auto scaling on the graph.
![image](https://user-images.githubusercontent.com/2766619/142051879-79281fa1-528d-4d58-a99c-252bdf690abd.png)

**Comment by aufdenkampe** [comment]
@neilh10. Great idea.

Since this isn't a bug and we're presently tight on time, we might bump this to the next release, which we'll start working on in early December.

**Comment by ptomasula** [comment]
@neilh10 

Great suggestion and fairly easy to implement. This was added in commit [647386b](647386b3e796cca8138e829a164e049224540d92) and is now live on the staging server.
