### ISSUE TITLE
smmw: posting response is 301

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#522]
When I attempt to post, to "staging.monitormywatershed.org"  I get response 301, which is unsuccessful

Looking at 
https://staging.monitormywatershed.org/tsv/tu_rc_test07/4903/ or
at download tu_rc_test07_TimeSeriesResults.csv 
its not been recorded.

With some debug the terminal response from the Mayfly is 
---------------------------
Client connected after 361 ms <--EnviroDIYPublisher
POST /api/data-stream/ HTTP/1.1
Host: staging.monitormywatershed.org
TOKEN: 0af40c10-cbd5-4a7d-b78c-79ca06553e54
Content-Length: 500
Content-Type: application/json

{"sampling_feature":"1e77a2de-11a7-4f4c-9237-668384eb3a18","timestamp":"2021-11-17T14:34:00-08:00","645d6ee6-c42a-4cee-9191-5a7e6a331a4c":3,"efe0e9a3-cd63-4e82-a025-7b3d2d4da18b":-0.670,"af45f842-68de-481b-9375-0788d5f13868":4.1334,"e9596fd4-35e9-4271-aab0-661aab3dd772":4.078,"e8011385-91ea-487e-a0a5-582ec4f0d906":16.47,"f762c642-33a0-4baa-a4e9-fff2d62411e5":-0.0019,"1be5346c-c59e-47b7-ade7-d71a5e841c54":62.5,"ae401cf2-8680-4a66-9bc9-5fe78bf10713":17.6,"c0222eb2-4c63-4050-a8cf-6ae2ce68bae7":-22}

 [[Client waited 3193 mS for 12 bytes. <--EnviroDIYPublisher
Client stopped after 737 ms <--EnviroDIYPublisher
Rsp:' HTTP/1.1 301 ' <--EnviroDIYPublisher
-- Response Code -- 301 waited  3193 mS Timeout 5000

-----------------
I checked the JSON payload size, and its 500bytes long.

Since it failed, and as part of reliable delivery the message is stored on the uSD.
I changed the destination back to "data.enviroDIY.org" and it completes with successful response 201, and shows on 
https://monitormywatershed.org/sites/tu_rc_test07/
------------------------------
Client connected after 250 ms <--EnviroDIYPublisher
Filled from SD QUE in  22 ms <--EnviroDIYPublisher
POST /api/data-stream/ HTTP/1.1
Host: data.enviroDIY.org
TOKEN: 0af40c10-cbd5-4a7d-b78c-79ca06553e54
Content-Length: 500
Content-Type: application/json

{"sampling_feature":"1e77a2de-11a7-4f4c-9237-668384eb3a18","timestamp":"2021-11-17T14:34:00-08:00","645d6ee6-c42a-4cee-9191-5a7e6a331a4c":3,"efe0e9a3-cd63-4e82-a025-7b3d2d4da18b":-0.670,"af45f842-68de-481b-9375-0788d5f13868":4.1334,"e9596fd4-35e9-4271-aab0-661aab3dd772":4.078,"e8011385-91ea-487e-a0a5-582ec4f0d906":16.47,"f762c642-33a0-4baa-a4e9-fff2d62411e5":-0.0019,"1be5346c-c59e-47b7-ade7-d71a5e841c54":62.5,"ae401cf2-8680-4a66-9bc9-5fe78bf10713":17.6,"c0222eb2-4c63-4050-a8cf-6ae2ce68bae7":-22}

 [[Client waited 471 mS for 12 bytes. <--EnviroDIYPublisher
Client stopped after 577 ms <--EnviroDIYPublisher
Rsp:' HTTP/1.1 201 ' <--EnviroDIYPublisher
-- Response Code -- 201 waited  471 mS Timeout 5000

**Comment by neilh10** [comment]
I just tried 
Pinging staging.monitormywatershed.org [3.130.242.34] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 3.130.242.34:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),


Pinging data.enviroDIY.org [50.236.137.123] with 32 bytes of data:
Reply from 50.236.137.123: bytes=32 time=70ms TTL=44
Reply from 50.236.137.123: bytes=32 time=69ms TTL=44
Reply from 50.236.137.123: bytes=32 time=73ms TTL=44
Reply from 50.236.137.123: bytes=32 time=69ms TTL=44

Ping statistics for 50.236.137.123:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 69ms, Maximum = 73ms, Average = 70ms


Pinging monitormywatershed.org [50.236.137.123] with 32 bytes of data:
Reply from 50.236.137.123: bytes=32 time=68ms TTL=44
Reply from 50.236.137.123: bytes=32 time=78ms TTL=44
Reply from 50.236.137.123: bytes=32 time=69ms TTL=44
Reply from 50.236.137.123: bytes=32 time=68ms TTL=44

Ping statistics for 50.236.137.123:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 68ms, Maximum = 78ms, Average = 70ms

**Comment by aufdenkampe** [comment]
@neilh10, wow, that's weird. I get the same thing. 

I'm thinking that we need to open a port for HTTP and forward to HTTPS or something like that. I'll look into it.

**Comment by neilh10** [comment]
Ahh seems some strange new spaces in the interstatial-net  ....

C:\Users\neilh77a>ping staging.monitormywatershed.org

Pinging staging.monitormywatershed.org [3.130.242.34] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

C:\Users\neilh77a>tracert staging.monitormywatershed.org

Tracing route to staging.monitormywatershed.org [3.130.242.34]
over a maximum of 30 hops:

  1     2 ms     1 ms     1 ms  SYNLAGUNAROUTER [10.66.66.66]
  2    12 ms    12 ms    13 ms  96.120.91.129
  3    11 ms    14 ms    18 ms  96.110.103.121
  4     9 ms    10 ms     9 ms  162.151.86.17
  5    21 ms    37 ms    55 ms  68.87.194.113
  6    13 ms    12 ms    13 ms  be-397-ar01.hayward.ca.sfba.comcast.net [96.108.99.9]
  7    14 ms    14 ms    14 ms  be-36341-cs04.9greatoaks.ca.ibone.comcast.net [68.86.93.141]
  8    35 ms    14 ms    15 ms  be-1411-cr11.9greatoaks.ca.ibone.comcast.net [68.86.166.166]
  9    22 ms    21 ms    21 ms  be-302-cr11.losangeles.ca.ibone.comcast.net [96.110.38.93]
 10    27 ms    21 ms    26 ms  be-1211-cs02.losangeles.ca.ibone.comcast.net [96.110.45.169]
 11    21 ms    21 ms    21 ms  be-1212-cr12.losangeles.ca.ibone.comcast.net [96.110.45.174]
 12    50 ms    50 ms    50 ms  be-301-cr13.houston.tx.ibone.comcast.net [96.110.37.185]
 13    59 ms    59 ms    59 ms  be-1313-cs03.houston.tx.ibone.comcast.net [96.110.46.137]
 14    52 ms    52 ms    52 ms  be-3311-pe11.westwaypark.tx.ibone.comcast.net [96.110.34.74]
 15    51 ms    50 ms    50 ms  50.248.119.14
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18    97 ms    97 ms    82 ms  54.239.41.148
 19    86 ms    83 ms    84 ms  150.222.249.254
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25    84 ms    84 ms    84 ms  52.95.1.150
 26    83 ms    84 ms    85 ms  52.95.1.161
 27    84 ms    89 ms    84 ms  52.95.1.104
 28    84 ms    84 ms    83 ms  52.95.1.87
 29   100 ms    99 ms    99 ms  ^C

and then
C:\Users\neilh77a>tracert monitormywatershed.org

Tracing route to monitormywatershed.org [50.236.137.123]
over a maximum of 30 hops:

  1     1 ms     1 ms     1 ms  SYNLAGUNAROUTER [10.66.66.66]
  2     9 ms     9 ms     9 ms  96.120.91.129
  3    11 ms     9 ms     9 ms  96.110.103.121
  4     9 ms    10 ms    10 ms  162.151.86.17
  5    10 ms     9 ms     9 ms  162.151.79.105
  6    12 ms    10 ms     9 ms  69.139.198.85
  7    12 ms    12 ms    12 ms  be-297-ar01.santaclara.ca.sfba.comcast.net [96.108.99.13]
  8    25 ms    15 ms    13 ms  be-36341-cs04.sunnyvale.ca.ibone.comcast.net [96.110.41.77]
  9    13 ms    12 ms    12 ms  be-1411-cr11.sunnyvale.ca.ibone.comcast.net [96.110.46.38]
 10     *        *        *     Request timed out.
 11    38 ms    38 ms    38 ms  be-1412-cs04.champa.co.ibone.comcast.net [96.110.37.221]
 12    37 ms    40 ms    37 ms  be-1414-cr14.champa.co.ibone.comcast.net [96.110.37.254]
 13    38 ms    39 ms    38 ms  be-302-cr14.1601milehigh.co.ibone.comcast.net [96.110.39.6]
 14    38 ms    37 ms    37 ms  be-1114-cs01.1601milehigh.co.ibone.comcast.net [96.110.39.113]
 15    37 ms    36 ms    36 ms  be-1111-cr11.1601milehigh.co.ibone.comcast.net [96.110.39.66]
 16    77 ms    59 ms    60 ms  be-301-cr11.350ecermak.il.ibone.comcast.net [96.110.37.145]
 17    61 ms    60 ms    60 ms  be-1111-cs01.350ecermak.il.ibone.comcast.net [96.110.35.1]
 18    66 ms    65 ms    65 ms  96.110.42.178
 19    67 ms    69 ms    68 ms  68.87.191.86
 20    71 ms    67 ms    69 ms  96.110.94.6
 21    68 ms    68 ms    68 ms  50-236-137-123-static.hfc.comcastbusiness.net [50.236.137.123]
 22    71 ms    69 ms    68 ms  50-236-137-123-static.hfc.comcastbusiness.net [50.236.137.123]

Trace complete.

**Comment by ptomasula** [comment]
The 301 response from the staging server was due to our nginx configuration. The server was configured to automatically root HTTP (non-secure) traffic to HTTPS (secure).

I have reconfigured nginx so that any HTTP traffic with ‘/api’ in the uri will bypass the HTTPS reroute and should now be handled by the application.

**Comment by ptomasula** [comment]
As for ping and tracert failing to resolve, that is probably AWS security related. I'm not certain but my guess is that AWS blocks ping and traceroute by default and that @aufdenkampe and I need to take a look at our security groups to enable that. We can leave the issue open for now until we resolve ping and traceroute.

**Comment by ptomasula** [comment]
Confirmed that ping (and likely traceroute) issues are related to AWS security settings. Ping should resolve correctly because I've enabled the EchoRequest protocol. I'm not exactly sure what protocol I need to enable for traceroute. I enabled the 'traceroute' protocol but still doesn't resolve for me. 

@aufdenkampe, might be worth following-up with AWS support if we need to get traceroute to work.

**Comment by ptomasula** [comment]
With the AWS configuration and the recent refactoring the /api/data-stream/ feature should now return either a 201 or a 500 response. I've tested this by spoofing a sensor with postman but it would be good to confirm this behavior using a real sensor before closing the issue. 

@neilh10 would you be able to resume posting some data to the staging server and verify if you get the appropriate response?

**Comment by neilh10** [comment]
Yeah with #526 complete, on POSTIing its going through and I'm getting a '201' response, and occasionally a '504'
https://staging.monitormywatershed.org/sites/tu_rc_test07/

**Comment by aufdenkampe** [comment]
@neilh10, that's great to see. Thanks for your testing!
