### ISSUE TITLE
smmw: Date Range actions switched

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#523]
When making a selection with the "Date Range" Begin selector,  after pressing Update Plot, the action is switched to the End date, and the result is not the expected start plotting from the Begin Date.
Stepping to https://staging.monitormywatershed.org/tsv/tu_rc_test06
and then selecting the Decagon_CTD Temperature 
The screen on entry
![Screenshot 2021-11-17 173717](https://user-images.githubusercontent.com/2766619/142335890-5be34156-05a4-4630-b7f3-49bb96ce64f7.jpg)

Selecting a value in the "Begin Date"
![Screenshot 2021-11-17 173828](https://user-images.githubusercontent.com/2766619/142336055-b485999a-1dde-412a-bea7-473599970233.jpg)

After pressing Update Plot, the result is un-expected.

![Screenshot 2021-11-17 173932](https://user-images.githubusercontent.com/2766619/142336139-607c061f-6b8f-4481-a8c8-c4ade67fb557.jpg)

**Comment by aufdenkampe** [comment]
@ptomasula, this might be something to work on in December. Adding it to the next milestone.

**Comment by ptomasula** [comment]
Nice find. This was related to a UTC conversion. It should now be addressed with PR [#528](https://github.com/ODM2/ODM2DataSharingPortal/pull/528). Changes are live on the staging server.
