### ISSUE TITLE
Production: Server Error (500)

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#525]
No response on all access, both front door, and data POSTS

From my test07 log reported Intermittent from  UTC
2021-11-27T07:32:22-08:00,POST,500,
2021-11-27T07:34:18-08:00,POST,500,
2021-11-27T07:36:23-08:00,POST,500,
2021-11-27T07:54:18-08:00,POST,201,

Then shortly after that 
2021-11-27T08:32:23-08:00,POST,500,5000,0,1637973120,133,2.903,3.9967,4.275,16.17,-0.0014,-9999.0,-9999.0,-33

https://monitormywatershed.org/sites/tu_rc_test07/
and 
... WiFi connected after 2099 milliseconds! <--DigiXBeeWifi
Connected Internet

pubDQTR Sending data to [ 0 ] data.enviroDIY.org
EnvrDIYPub gQS  1 <--EnviroDIYPublisher
getTPP(mS) 100 <--EnviroDIYPublisher
Connecting client. Timer (mS) <--EnviroDIYPublisher
Client connected after 362 ms <--EnviroDIYPublisher

POST /api/data-stream/ HTTP/1.1
Host: data.enviroDIY.org
TOKEN: 0af40c10-cbd5-4a7d-b78c-79ca06553e54
Content-Length: 507
Content-Type: application/json

{"sampling_feature":"1e77a2de-11a7-4f4c-9237-668384eb3a18","timestamp":"2021-11-27T09:22:00-08:00","....}

 [[Client waited 3228 mS for 12 bytes. <--EnviroDIYPublisher
Client stopped after 584 ms <--EnviroDIYPublisher
Rsp:' HTTP/1.1 500 ' <--EnviroDIYPublisher

**Comment by aufdenkampe** [comment]
@neilh10, thanks for sharing this error. We're looking into it right now.
cc. @ptomasula

**Comment by neilh10** [comment]
Many thanks. All fixed that I can see off

**Comment by aufdenkampe** [comment]
@neilh10, yes! Thanks for posting this error.
