### ISSUE TITLE
Cache Busting for JS/CS

### ISSUE THREAD

**Issue by ptomasula** [ODM2/ODM2DataSharingPortal#529]
It's common practice to add methods to force an update of new JS and CSS files when a new version is deployed to the server. This prevents the third party cached version of the files from being used and ensures that users see updates to these files as soon as they are deployed. In Django this is done by having the application append a version number to the various JS/CSS files. See [manifeststaticfilesstorage](https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#manifeststaticfilesstorage) for additional details.

**Comment by ptomasula** [comment]
@aufdenkampe, commit [b78a8f9](https://github.com/ODM2/ODM2DataSharingPortal/commit/b78a8f9563836483911015c9f74e5ab0d8c13821) implements cache busting. This adds an extra step for deployment, where we need to run `python manage.py collectstatic --noinput` prior to restarting gunicorn. I'll update the deployment scripts and documentation.

I have it up and running on the staging server. Essentially Django appends a hash to the end of static files. When the `collectstatic` command is run, it will check which files have been modified and replace them in the folder that serves the static files with a different hash. This forces user's browser to grab the new version of the static file whenever we update. 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/31142705/154137246-b4d545e2-0cb9-40d9-899d-e821f1522eb4.png">

**Comment by aufdenkampe** [comment]
Nice work implementing this fix, which users will greatly appreciate down the road.
