### ISSUE TITLE
Missing Config repo

### ISSUE THREAD

**Issue by TRSWNCA** [ODM2/ODM2DataSharingPortal#545]
Hi guys! The tutorial says it have a config repo at https://github.com/LimnoTech/ODM2DataSharingPortalConfig.
But depressedly it was deleted.
What can I do?

**Comment by SRGDamia1** [comment]
If you're trying to set up and deploy your own instance of this, you'd need your own configurations based on your actual server and passwords and the like.

What are you trying to do?

**Comment by kieutuandung-aptech-vn** [comment]
I have same question as TRSWNCA. How can I have a config repo or install exactly as guide?

**Comment by aufdenkampe** [comment]
Thank you for creating this issue. It is clear that we need up update our deployment guide, as there is a mixture of old and new information, along with links that are not really relevant to others that would like to deploy something similar.

As @SRGDamia1 described above, https://github.com/LimnoTech/ODM2DataSharingPortalConfig is a private repository that holds all of our settings files that are specific to our deployment.

You will need to create your own settings files as described in step 6 of the old Python 2.7 deployment guide, here: https://github.com/ODM2/ODM2DataSharingPortal/blob/main/doc/deployment_guide.md#python-27

Although we've recently upgraded the stack significantly with release 0.12.0, that general instruction for creating your own settings file still applies.

We'll update the documentation with our next release, scheduled for February. You can follow that progress under:
- #549
