### ISSUE TITLE
Enhance the new Time Series Visualization (TSV)

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#551]
Potentially adding features such as:

- [ ] Adjustable vertical scrolling for plotted time series
  - #540
- [x] Filter option for 'Load Site' panel which narrows down selection options 
- [x] Plot to auto-scale (vertically) with screen.
- [x] Overflow-y scrolling for the control panel. Make the controls more similar to a single page application, so that controls stay within the same vertical boundary as the plot. 
- [x] Loading indicator for after they are checked timeseries
- [ ] Plotting threshold function (option to exclude data over/under a user-defined value(s) so that spikes and other out-of-water artifacts don’t crowd visualization)
  - #572

**Comment by dbressler75** [comment]
@aufdenkampe, here are some other items:

- [ ] currently when you plot a single parameter for two different sites it displays two different y-axes (see 
![two_y-axes_for_same_parameter](https://user-images.githubusercontent.com/39309124/149558972-f9d1f1ff-ff32-47fa-ad39-65496be18b26.JPG) - need to display one axis per parameter
- [ ] summary stats for parameters selected in TSV for date range selected (current TSV does not have summary stats)
- [ ] cursor hover over TSV graphs should include year, as well as time, day, month which it currently shows (does not currently show year of data points)

**Comment by aufdenkampe** [comment]
@SRGDamia1 and @dbressler75, it would be helpful if you could help us prioritize these requested TSV feature enhancements for us to tackle in the next couple of weeks for our [v0.13.0 release - Address Tech Debt, Improve TSV](https://github.com/ODM2/ODM2DataSharingPortal/milestone/19) Milestone, scheduled for release in early April.

For example, for the priority items on the lists above, perhaps you could create individual issues, assign them to the Milestone, then tag them as `high-priority` (or tag existing issues).

**Comment by dbressler75** [comment]
@aufdenkampe, yes the ones that I had as top priority were #540, #570, #571, #572, and #573, however the other ones that you laid out are important too.  I have not used MonitorMW a lot lately so I'm hoping there aren't others that I/we are missing.  The upload size issue was/is a big one too #364 - that is not TSV related but is a big one and hopefully is being addressed(?).  Thank you!!

**Comment by mbarneytu** [comment]
> We think that the need for https://github.com/ODM2/ODM2DataSharingPortal/issues/570 will largely be resolved by addressing https://github.com/ODM2/ODM2DataSharingPortal/issues/540.

@aufdenkampe I really appreciate your and your team's hard work on all of these issues! 
Would you anticipate that the resolution of #540 (make the axes adjustable) will enable zooming the axis by _individual_ series? If not, I wouldn't think that it will address the usability issue described in #570 (separate axes are plotted for each instance of the same variable). Considering @dbressler75 's example, where the two conductivity axes displayed differ by an order of magnitude, it's impossible to effectively compare the two conductivity values at a given datetime.

**Comment by ptomasula** [comment]
A subset of the functionality listed in @aufdenkampe's [original comment](https://github.com/ODM2/ODM2DataSharingPortal/issues/551#issue-1095556480) has been implemented and is presently on the staging server for testing. 

The remaining two items are captured in issues #540 and #572. Additionally some of the features in @dbressler75's (reply)[https://github.com/ODM2/ODM2DataSharingPortal/issues/551#issuecomment-1013319207] have not yet been implemented and were moved to a new issue for tracking. Resolving those will require additional effort and will be addressed as part of a future release.
