### ISSUE TITLE
Tests over weekend 2022Jan7 WiFi response adequate 3.2secs

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#552]
A test was started 2022-01-07 19:23:46.790 PST
Its using the Mayfly 1.0A3 (first time for testing) taking a sample every 2minutes and POSTING it over WiFi. Locally the 
 internet connections is comcast cable with an of upload speed of 6MB download 60MB.

This issue can be closed when any observations from the server loading are noted.

Good news,  the responses noted where all 201's, and with an adequate response time, mostly about 3.2Seconds but an interesting occasional  fast ~360-440mS
There is a period of lot of short response times, but this was happening with a series of processors resets that occurred dues a long switched battery power line, and low battery voltage. Once the longer switched battery power line was removed, and battery charged, the processor stopped resetting and response times crept up to 3.2Seconds.

Its possibly that something in the measurement method in the Mayfly software is contributing to an apparent longer access time, so I've altered the method of measuring to check this.
See attached. [tty220108-0832contB_response220110_0828.txt](https://github.com/ODM2/ODM2DataSharingPortal/files/7840378/tty220108-0832contB_response220110_0828.txt)

For a comparison,  response times for 201's captured in short informal tests on on the earlier server release, that was not correctly handshaking with the database,   where
2021Sept30 response in the range 240-540mS 
2021Feb1    response in the range 276-746mS
[tty210930-1437_code201.txt](https://github.com/ODM2/ODM2DataSharingPortal/files/7840760/tty210930-1437_code201.txt)

[tty210201-1914_code201.txt](https://github.com/ODM2/ODM2DataSharingPortal/files/7840710/tty210201-1914_code201.txt)

The is a development build, primarily checking a new type of runtime instantiation of the Modem (class loggerModem) - regression testing on the Mayfly 1.0, as well as the server response.

**Comment by aufdenkampe** [comment]
@neilh10, thanks for letting us know that response codes and times are looking much better on your end! Yay!

My quick scan is that your test does not show any impact on DB server CPU usage, suggesting that your high frequency tests are easily handled amidst other traffic.

This suggests that our hot fix worked very well!

BTW, this hotfix represents some quick refactoring of a portion of the code, from which we learned that there is quite a bit of room for additional improvements. So getting response in <1 second might be within our reach over the next year or two, even as overall traffic increases. We'll see. There are other portions of the code that also need our refactoring attention, which we need to do before implementing feature enhancements.
