### ISSUE TITLE
Fix "EnviroDIY Site Alert" system

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#555]
A user mentioned to me that they didn't get a site alert when their batteries went down in December, and they lost a month of data as a result.

Yesterday I turned on notifications to one of my sites that hasn't been on, and I have not gotten any alerts. It appears to no longer be working, perhaps since our release 0.12.0 in December, although we did not touch that code directly.

@neilh10 & @mbarneytu, have either of you noticed a change in our notification system?

**Comment by mbarneytu** [comment]
I checked with my colleague, and he has not been getting site alerts since the update. The last alert he received was on 12/8/2021. 
Thanks @aufdenkampe!

**Comment by neilh10** [comment]
I would agree, I've not seen any site alert notifications, and I would have expected some for 
https://monitormywatershed.org/sites/tu_rc_test08/   which was set to 24hours notification
I've changed it to 4hrs to monitor it.
tu_rc_test08/Mayfly1.0 testing recently went through a period of low battery, when it doesn't transmit, but I would have to check the logs to see if that exceeded 24hours.

https://monitormywatershed.org/sites/tu_rc_test06/ which is set for 4hours, should probably have alerted about Jan 14th, but I don't have any record of it.

All my field systems have been operating well, The last site alert for the field system I have- which was probably transitioning to the new system - is
Monitor My Watershed Notification: No data received for site TU CA Porter Creek 03 in the last 4 hours
Fri, 10 Dec 2021 21:30:03 -0000

**Comment by aufdenkampe** [comment]
@mbarneytu & @neilh10, thanks for that feedback.

We found the issue. Notifications were triggered by an undocumented cron job that @ptomasula found on the old production server. 

He's working on applying a hotfix to the AWS production server and will keep us posted.

**Comment by ptomasula** [comment]
Even after adding back in a previously undocumented cron job, the email notification were still not being sent out. We determined that the default SMTP port (port 25) is [blocked for outgoing traffic on AWS](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/). We switched to using port 587, which is a TLS encrypted SMTP port, but that introduced authentication issues with the gmail account previously used for alerts. Authentication required the EC2 instance to pass a security verification step, which we cannot complete from the linux server.

Our solution in the end was to replace the old alerts email service with one from the Stroud Center. The new email address for the alerts system is `monitormywatershedalerts@stroudcenter.org`

**Comment by neilh10** [comment]
Great.
I got 2 emails this morning @06:48 (PST) from monitormywatershedalerts@stroudcenter.org about systems, out of 5 active systems.
One below.
I include with full headers and it has the DKIM signature which helps with spam scoring. 
From what I understand for DKIM signatures, (i've been researching it in the last two weeks for another project),  and looking at all a range of emails I receive,   DKIM signatures are painful to add, and may not be truly meaningful in signing an email, are used by big providers google/Microsoft,   but do help with spam scoring.

-------- Forwarded Message --------
From: 	51 2022 <>
X-Account-Key: 	account5
X-UIDL: 	1643294872.18770_0.b.local-delivery,S=4403
X-Mozilla-Status: 	0001
X-Mozilla-Status2: 	00000000
X-Mozilla-Keys: 	
Return-Path: 	<monitormywatershedalerts@stroudcenter.org>
X-Spam-Checker-Version: 	SpamAssassin 3.4.6 (2021-04-09) on h.spam.sonic.net
X-Spam-Level: 	
X-Spam-Status: 	No, score=-2.1 required=4.5 tests=DKIM_SIGNED,DKIM_VALID, DKIM_VALID_AU,DKIM_VALID_EF,SNF4SA,SONIC_BX_A2,SPF_HELO_NONE shortcircuit=no autolearn=disabled version=3.4.6
X-Spam-SNF-Result: 	0 (Standard White Rules)
X-Spam-MessageSniffer-Scan-Result: 	
X-Spam-MessageSniffer-Rules: 	0-0-0-4443-c


Received: 	by mail-io1-f67.google.com with SMTP id y84so3899106iof.0 for <neilh20+ww1809@wllw.net>; Thu, 27 Jan 2022 06:47:50 -0800 (PST)
DKIM-Signature: 	v=1; a=rsa-sha256; c=relaxed/relaxed; d=stroudcenter.org; s=google; h=from:mime-version:content-transfer-encoding:subject:to:date :message-id; bh=IBLWViZMx5fbwAEZqRvDS+2qGjJdIaClTtMGiZmIMek=; b=LtiJnsFZ8De/uPmndLrQjM9cMA+BqXNJnxu3cnwBV9ORYUUE+uEXbz0yuVqIKl2no+ D+K2FdN66WWIGrU4iaOjqur6EBEU6AGPDEq5gkJRGEX0DhJosq93tiCoBx66kESfowQ0 nj9wBQU34qanBo8tQKltkUMbzcDn/T07k7zeSBt1/Wce8CuEPBak/KoeWQl95v4a6vGj fvokhcVbOuBGyVYoW9f8uCR4bc0DECHwHyEfh1S9Lpt5xZKmjPmUjfSn9t1R1+w239TW hiCAk820PGx8Qv7ebSbc7g0qGBiav7/XE3j08rI39bS5/T/XyNzded6bojapbo3lTvp8 CxXQ==
X-Google-DKIM-Signature: 	v=1; a=rsa-sha256; c=relaxed/relaxed; d=1e100.net; s=20210112; h=x-gm-message-state:from:mime-version:content-transfer-encoding :subject:to:date:message-id; bh=IBLWViZMx5fbwAEZqRvDS+2qGjJdIaClTtMGiZmIMek=; b=IUX5zhsnxEpMfk8AiIV8TyBMA124rKPTVBffvmz1JGaQqiIdeWbxXVF7NmvafDwQp+ it5O+YnHSCFTIRmoHOS4A2pXH2ry857gFJmpEXXkGN2nMrkGkqB7TPu3XtEliR4Pd/sx RWtcfip2yHrblrwiRXRecvgcNzO9bKL/bgO68WGGMxVE/phsc6Kqrx/pmKpXZB4Jb1ay ejvVR1v9EPgDYQZmuPuuMhc97aNLqP1i6Afeb0hef1GGE8nuBAr1MpvWaNJznJiCLlEz MzDadHT5hL4KX36jWCq2xchjUzmF5/gUKgn+pTlnbSJt686sXPHi7CX2eABUFx/mAtn7 qPPw==
X-Gm-Message-State: 	AOAM5307OopyWHTOf7jiFZr4u633WjoQnpQpcxFvVsisjGUVb4yyJ06n 5DAobm8QwxT1cHN6Ab6g5qLMT+xHX5SDVMdwnUvQJoHd
X-Google-Smtp-Source: 	ABdhPJz11IPSOZhRDkC0PH+XLHZsFWMLf/HYrLgvJaqgUYAbbnqe44REogt8Xf9jflb6BpR5hCutpA==
X-Received: 	by 2002:a02:77d3:: with SMTP id g202mr2044019jac.268.1643294869531; Thu, 27 Jan 2022 06:47:49 -0800 (PST)
Received: 	from ip-172-31-42-67.us-east-2.compute.internal (ec2-3-14-188-180.us-east-2.compute.amazonaws.com. [3.14.188.180]) by smtp.gmail.com with ESMTPSA id m12sm10068511iow.54.2022.01.27.06.47.49 for <neilh20+ww1809@wllw.net> (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256); Thu, 27 Jan 2022 06:47:49 -0800 (PST)

From: 	EnviroDIY Site Alert <monitormywatershedalerts@stroudcenter.org>
X-Google-Original-From: 	"EnviroDIY Site Alert" <data-alert@monitormywatershed.org>
Content-Type: 	text/plain; charset="utf-8"
MIME-Version: 	1.0
Content-Transfer-Encoding: 	7bit
Subject: 	Monitor My Watershed Notification: No data received for site Laguna da Santa Rosa @ E Cotati Ave in the last 2295 hours
To: 	neilh20+ww1809@wllw.net
Date: 	Thu, 27 Jan 2022 14:47:49 -0000
Message-ID: 	<164329486909.1582735.18381624598944948563@ip-172-31-42-67.us-east-2.compute.internal>
X-Orthrus: 	tar=0 grey=no co=US os=Linux/3.x/3 spf=softfail dkim=pass


Neil,

This email is to notify you that your Monitor My Watershed site "Laguna da Santa Rosa @ E Cotati Ave" has not received any new data values in the last 2295 hours. The last update was on 2021-10-23 23:20:00. You may want to check your equipment to ensure it's working as intended.
https://www.monitormywatershed.org/sites/LCC45_test02/

Best regards,
The Monitor My Watershed Team

**Comment by mbarneytu** [comment]
The alerts are apparently still not working or my colleague, Jake:

> I have not received any MMW notifications since the December update.  For our [Lee Creek](https://monitormywatershed.org/sites/Lee_Creek_Vergennes/) site I have notifications set to be sent if the site does not send data for 2 hours. There have been multiple data gaps within the last week that have exceeded 2 hours and I have not received an email.

**Comment by mbarneytu** [comment]
As of 13:36 ET, Jake reports that he got 2 email notifications from MMW.

**Comment by ptomasula** [comment]
@mbarneytu Thanks for the additional report. I discovered a typo in the cronjob, which prevented the alerts generation code from running on an automated schedule. I've corrected the error and the alerts should now be functioning correctly.

I manually executed the alerts function, so emails will have just gone out. I'll keep this open for a few days until I verify that the cronjob is executing correctly and doesn't need any more adjustments.

**Comment by ptomasula** [comment]
We've tested a few different approaches to get our site alerts to trigger automatically, but we currently have not found a workable solution. We believe this might be in part due to our use of gmail smtp. We have recently started the process of transitioning to an alternative email provider like [SES](https://aws.amazon.com/ses/) to see if that resolves our issues. 

We are hoping to resolve this quickly and this remains a high priority issue for us. However, we'd like to release the rest of the techdept updates and TSV enhancements sooner than it my take to resolve this. I'm going to move this over to our next milestone, though we are open to issuing a hotfix as soon as a resolution is in place.

**Comment by ptomasula** [comment]
Now that we have [AWS SES](https://aws.amazon.com/ses/) working, I have wired up the alerts system to use that service. My manually test run on the command, successfully set out alert emails. I'll keep an eye on this to make sure this code is executing automatically as intended before we call this closed, but we're making progress.

**Comment by ptomasula** [comment]
Our database and SES metrics are showing that site alerts were sent out automatically over the weekend and this morning. I'm going to close out this issue, but please let us know if anyone is still not receiving site alerts.

**Comment by aufdenkampe** [comment]
@ptomasula, thanks for this hotfix! That great news!

Given that it's all working on production, I'm going to move this to the 0.13 milestone and into our Release Notes.
