### ISSUE TITLE
Empty UUIDs prevent data upload

### ISSUE THREAD

**Issue by mbarneytu** [ODM2/ODM2DataSharingPortal#556]
ModularSensors allows you to build Variable objects that contain empty UUIDs, and in fact the UUID defaults to empty string in one version of the constructor. The use case for this was described in [this post](https://www.envirodiy.org/topic/plotting-calculated-values/#post-13743) on the Mayfly forum, as a way to deal with calculated values, such as when a sensor reports depth in mm, but you only want to upload the value in inches.

However, if you upload such a variable, the server responds with a 504 and rejects the entire datapoint, as in this example which contains several variables with valid UUIDs, but two with empty UUIDs at the end:

`{"sampling_feature":"989b7148-d939-487e-ac47-baf41e30370d","timestamp":"2022-01-24T09:30:00-07:00","8c885a18-46f5-48a7-b0c3-3e74bf1c1d66":67.8,"a97f78c9-2398-4953-a66f-bd7786a582e8":0.2,"b2dbf7a1-07af-4f87-bf85-b36768745436":0.0,"b7717d98-3c5b-4432-9ac3-4188c7de7a05":19.90,"b286a34a-0b48-4c35-a90e-a531a2594959":4.912,"6c79d6be-edd7-4bb3-836b-30b99d6b4f5d":68.9,"621555d7-ebb1-4f8c-b8af-33fb35e78c3a":-59,"2e6faaa5-e7ea-40c1-90be-c1092d326b0e":87,"ca519f85-1d11-4c3a-bc17-6eaa7afd0229":-3.79005,"9b5e00bd-8712-4d51-bb20-01c31faee32f":0.0201,"":4.0,"":20.50}`

I _think_ that blank UUIDs were allowed prior to v0.12.0 of the server (it's been 2 years since I was first using this technique). The server used to just ignore values that were associated with blank UUIDs and store the other values as usual. I wonder whether the server could be modified so that it handles lists of ModularSensors Variables more transparently.

I am able to work around this issue by supplying a dummy UUID (e.g. "12345678-abcd-1234-ef00-1234567890ab").

**Comment by aufdenkampe** [comment]
@mbarneytu, thank you for posting this issue!  It has also been a peeve of mine for quite a long time. See:
- #303 

We'll definitely address this sometime in the next couple of months, for the next release or the one after that. We still have quite a bit of tech-debt to work through before we can easily address these kinds of issues, unfortunately. The good news is that we now have funding to move forward on doing just that.

**Comment by aufdenkampe** [comment]
@mbarneytu, @ptomasula, @xaviernogueira, I'm closing this issue, which is a replicate of #303, to simplify tracking and conversations.

@mbarneytu, we are targeting a fix in the next month with release of v0.13.
