### ISSUE TITLE
User taken to Django administration page upon log out

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#558]
![monitormw-logout](https://user-images.githubusercontent.com/9368629/152422279-47b64977-ae77-4807-a671-58954736ebc1.jpg)

**Comment by HeatherBrooks** [comment]
Thanks for taking a look at this. If I'm rememberin correctly, the previous behavior when a user logged out was to be returned to the homepage.

**Comment by aufdenkampe** [comment]
@ptomasula, let us know when this fix is on staging, so that we can close this issue.

**Comment by ptomasula** [comment]
> @ptomasula, let us know when this fix is on staging, so that we can close this issue.

Yes that's correct. @xaviernogueira update is now on staging and logout traffic is being routed to the new page.
