### ISSUE TITLE
Problem with organizational affiliation on site page

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#562]
> I created an account on Monitor My Watershed and selected my organization “Mississippi Watershed Management Organization”. I have deployed a rain gauge and set up the site “[SAVPW-RG](https://monitormywatershed.org/sites/SAVPW-RG/)” but on the second line of the site page after Organization it says “I am currently unaffiliated with and organization.” How do I get my organization to populate that line? I’ve selected my organization in ‘Edit Profile Information’ but it’s still not showing up on the “[SAVPW-RG](https://monitormywatershed.org/sites/SAVPW-RG/)” site page.
 I also set up an account for my organization and the sites registered under that account do have “Mississippi Watershed Management Organization” listed under the Organization line of the site page as you can see for this site, “[Mensing](https://monitormywatershed.org/sites/Mensing/)“.

Both accounts and the site that is showing as unaffiliated were created in 2019. The site that is showing correct affiliation was created in 2020. See the [Monitor My Watershed forum topic](https://www.envirodiy.org/topic/i-am-currently-unaffiliated-with-and-organization/) for the complete thread.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, thanks for this. I think it might be due to caching. Hopefully this will be addressed when we deploy:
- #529
