### ISSUE TITLE
Add date range query parameter to TSV data fetch and use to pull no more than last ~6 months by default

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#565]
There is a box to select the date range, but the date range is applied to the axis after the full data set is fetched.  Fetching the entire date set is slow and as the size increases it will slow further and probably overload the browser.

**Comment by aufdenkampe** [comment]
@ptomasula, I think that it might make sense to have a default behavior of loading the last month of data by default, then fetching additional data as requested by the user. 

This should substantially improve the user experience.

**Comment by aufdenkampe** [comment]
Connecting to this parent issue:
- #551

**Comment by neilh10** [comment]
You guys probably know more than me on this, but I had this Highstock prototype some years ago
https://github.com/neilh10/thingspeakmultichannel-highcharts
with an interface to my raingauge (totalizer)  
http://azonde.org/pm2/LiveRainGauge3.htm
Extra date range is pulled by pressing bottom left button "Load More Historical Data".
Though I haven't dug into all the JS code and how it does it.

**Comment by ptomasula** [comment]
Commit [ed27053](https://github.com/ODM2/ODM2DataSharingPortal/commit/ed27053101536ec5a2238232de4a8d58ac185b92) is now live on the staging server. This commit encapsulates timeseries management into a class. This class includes a method which checks the requested dates versus the data that has already been loaded and requests only the additional data required.

**Comment by SRGDamia1** [comment]
I didn't think this one was going to make it, so I'm excited and testing this more now.

I've been using the TSV endpoint to scrape data so I can adjust my scripts to have ranges and see how it goes.
