### ISSUE TITLE
TSV: Date range should be populated after clicking "last year" or "last month" button

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#566]
After clicking either button, the date values should fill:
![image](https://user-images.githubusercontent.com/5374350/159027372-665a12db-23a9-4c0a-9298-148a1a7c12e3.png)

**Comment by aufdenkampe** [comment]
Connecting to this parent issue:
- #551

**Comment by ptomasula** [comment]
This was resolved in commit (33a5899)[33a5899146656ef40c2788d4b4ddd2b1c6c3fdef]. These changes are now live on the staging server.
