### ISSUE TITLE
cursor hover needs to include year

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#571]
Cursor hover over TSV graphs should include year - it currently only shows date and month.  
![hover_noyear](https://user-images.githubusercontent.com/39309124/159493319-49f9cece-5b61-4984-93ac-d38178a323dd.JPG)

**Comment by neilh10** [comment]
For the cursor hovering over a point, I'm wondering can it show a meaningful resolution, possibly the max shown on the axis.

Eg for the snapshot below, hovering on the plotted lines is shown as 0.1, yet the scale range is  0.11 to 0.145.  
If it was shown at the  max resolution of the auto derived axis scale - in this case would be three decimal points - so the data would be shown as 0.141

![image](https://user-images.githubusercontent.com/2766619/159587727-55a4a521-61af-4f31-b800-deaad095d55a.png)

https://monitormywatershed.org/tsv/tu_rc_test06/3811/
Many thanks
