### ISSUE TITLE
Unable to delete sensors 

### ISSUE THREAD

**Issue by mbarneytu** [ODM2/ODM2DataSharingPortal#575]
No errors, but nothing gets deleted.
Note that this was also reported here: https://www.envirodiy.org/topic/data-uploading-but-not-publishing/#post-16809

**Comment by aufdenkampe** [comment]
This looks connected to:
- #577

**Comment by ptomasula** [comment]
This issue should be resolved on [staging](https://staging.monitormywatershed.org/).
