### ISSUE TITLE
Admin backed returns 500 error for all operations

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#577]
I can't add or modify anything right now.

**Comment by ptomasula** [comment]
This should be addressed on [staging](https://staging.monitormywatershed.org/). It's hard for me to pin point the exact cause of this one, which is not usually how I like to resolve these types of issues. But our staging environment updated to a different major release of Django, further consolidated our databases, and removed some old admin dependencies. Between those three things the functionality looks to be restored and should be on production following our release of [V0.13.0](https://github.com/ODM2/ODM2DataSharingPortal/milestone/19)
