### ISSUE TITLE
High Priority Upgrade TimescaleDB 2.5.1 => 2.5.2 (or 2.6.1)

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#581]
Since we upgraded to TimescaleDB 2.5.1 on January 13 with:
- #580 
TimescaleDB issue a high priority bugfix release 2.5.2:
- https://github.com/timescale/timescaledb/releases/tag/2.5.2

It seems important that upgrade to at least 2.5.2.

We could upgrade to [2.6.1 (2022-04-11)](https://github.com/timescale/timescaledb/releases), which includes additional bug fixes since 2.5.2 and also builds stability into new features that we might want to leverage (i.e. Compression on [Continuous aggregates in TimescaleDB](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/) are a more powerful version of [PostgreSQL materialized views](https://www.postgresql.org/docs/9.3/rules-materializedviews.html).

Read Timescale's blog post on these features at: https://www.timescale.com/blog/increase-your-storage-savings-with-timescaledb-2-6-introducing-compression-for-continuous-aggregates

I'm open to upgrading to either 2.5.2 or 2.6.1.

@htaolimno, can you do this upgrade in the next week for this coming release?
cc: @ptomasula

**Comment by htaolimno** [comment]
@aufdenkampe @ptomasula Sorry for late response. I'll do the upgrade today, possibly directly to 2.6.1

**Comment by aufdenkampe** [comment]
@htaolimno, thanks! It looks like there are no breaking changes between our current version 2.5.1 and 2.6.1, so it might make sense to go all the way to 2.6.1.

Also, before you do that, please create an AMI backup, and also migrate the AWS instance type from `M5` to `M6i`.

**Comment by htaolimno** [comment]
@aufdenkampe the DB instance type is c5.xlarge. Just confirm that change it to M6i.xlarge ?

**Comment by aufdenkampe** [comment]
@htaolimno, whoops. I had meant to change it to `C5i.xlarge`.

**Comment by aufdenkampe** [comment]
@htaolimno, I just created this separate issue:
- #587

**Comment by htaolimno** [comment]
I spun up a new staging DB server with timescaledb upgraded to 2.6.1 and associated with the elastic IP. The old staging DB server has been stopped.
