### ISSUE TITLE
Need ability to recover username and/or password

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2DataSharingPortal#6]
Because people forget it. Like me. Today.

**Comment by SRGDamia1** [comment]
Reopening this because people still need to be able to recover their username.

**Comment by ptomasula** [comment]
I believe we fixed this on the current production when we swapped to a different email provider. However when we release 0.15.0 we are switching to AWS Cognito for managing user credential. They provide a robust methodology for resetting passwords.
