### ISSUE TITLE
reopen #561, forgot password function

### ISSUE THREAD

**Issue by dbressler75** [ODM2/ODM2DataSharingPortal#618]
@ptomasula and @aufdenkampe, I tested the Forgot Password function and never received an email (account: davidwbressler@gmail.com) with any instructions for resetting the password.  I don't need to reset the password but wanted to test it and it does not appear to be working.

_Originally posted by @dbressler75 in https://github.com/ODM2/ODM2DataSharingPortal/issues/561#issuecomment-1222643110_

> As a follow up, another user said they were able to get all the way to the point where they changed the password but then when they entered the new password it wouldn't work: "I actually got the whole way through to change my PW, but when I tried entering the new PW it wouldn't let me access the account. I tried it a few times and it didn't work."

> Also, I think there may be different issues with older accounts (such as the one I just mentioned with the other user) and newer accounts (such as my personal one that I described in the first post today). Different issues but neither one resulted in successful password change.

**Comment by aufdenkampe** [comment]
@dbressler75, I'm moving this back to the original issue #561 that you reopened, to consolidate.
