### ISSUE TITLE
Excessive blank space (indentation) on generated UUID list 

### ISSUE THREAD

**Issue by s-hicks2** [ODM2/ODM2DataSharingPortal#627]
This issue appeared 2 weeks ago after the latest update, but there's now excessive blank space (32 spaces to be exact) indentation on the list is generated when you press the "View Token UUID List" button.  This makes the list extremely cumbersome to work with when a user needs to copy/paste it into an Arduino sketch.

**Comment by ptomasula** [comment]
@s-hicks2 @aufdenkampe 
That block of HTML is using a `pre` tag. That meant that indentations in the template (likely put in for readability) were being rendered. I removed those in my last commit. Changes are live on staging.
