### ISSUE TITLE
Add Cognito new password requirements

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#634]
My first New password failed, because I didn't have a lowercase character in it. 

We might want to add a little text that describes those password criteria.

**Comment by ptomasula** [comment]
@aufdenkampe 

The password requirements appear as the user enters their desired password. Do you think that is sufficient to address this issue? 

<img width="128" alt="image" src="https://user-images.githubusercontent.com/31142705/211336462-fb22454e-56b7-4a09-9c28-81b18020f027.png">

I don't see an option to have those requirements appear statically on the sign-up or sign-on pages within Cognito's setting. We could eventually implement our own sign-up and sign-on pages to replace the built in Cognito ones but probably not in the timeline and remaining funding for initial Cognito integration.
