### ISSUE TITLE
Improve Cognito verification email

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#636]
Presently, the email I got was this:

> From: no-reply@verificationemail.com <no-reply@verificationemail.com>
> Date: Monday, December 5, 2022 at 1:44 PM
> To: Anthony Aufdenkampe <aaufdenkampe@limno.com>
> Subject: Your verification code
> Your password reset code is 039126

We want to add some identifying info here for "Monitor My Watershed".

**Comment by ptomasula** [comment]
@aufdenkampe 

I modified the message settings from Cognito's default. 

**Subject:** Monitor My Watershed - Password Reset
 **Body**  The verification code to reset the password on your Monitor My Watershed account is: ######

Let me know if you want any tweaks to the language.

**Comment by aufdenkampe** [comment]
@ptomasula, looks good to me!
