### ISSUE TITLE
Extremely long pageload times

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#642]
Navigating from the homepage to Browse Sites or the login page, pages are taking 30-45 seconds to load each time. Also when trying to reach an individual site page from the Browse Sites page. Issue was first reported at 14:30 today by Tara Muenz who is in Delaware trying to demonstrate how to use the site. She tried multiple devices and browsers and encountered the slow pageloads across all. I've been able to replicate the issue at the Stroud Center in Firefox and Chrome.

**Comment by HeatherBrooks** [comment]
Still seeing these extremely slow page loads today. @aufdenkampe, any ideas?

**Comment by ptomasula** [comment]
After reviewing monitoring metrics we noticed an uptick in CPU utilization over the course of several months. It looks like it crossed a critical threshold about 3 weeks ago. In response to this issue we rebooted the production data server on 02/24/2023 and both CPU utilization and site performance seem to have increased. 

We've not yet identified a source for the gradual CPU utilization uptick, though are still looking into it. We are also looking into automated performance monitoring. We have uptime monitoring but currently do not receive automated alerts for slow performance. Such alerts would allow us to take quicker action when site performance is degraded.

**Comment by ptomasula** [comment]
@HeatherBrooks, just providing an update on this issue. 

LimnoTech swapped over a monitoring service so we now have page response time as an optional component on our monitoring. I set up a response time monitor so we are now collecting that data. It might take a little experimentation to determine appropriate alert thresholds, but I've presently set alert notification for a 50% increase in response time from the baseline.

**Comment by HeatherBrooks** [comment]
This is great, thank you!

**Comment by neilh10** [comment]
@HeatherBrooks I see the page load times have greatly improved. Seems to me this could be closed. Usually its the originator that closes if they think its working :)

**Comment by HeatherBrooks** [comment]
Thanks!
