### ISSUE TITLE
Creation of a StreamWatch Schools checkbox on 'Browse Sites' page

### ISSUE THREAD

**Issue by ptomasula** [ODM2/ODM2DataSharingPortal#645]
@aufdenkampe 
Requested as Task2 of the StreamWatch enhancements amendment.

Creation of a StreamWatch Schools “Data Type” category checkbox on the “Browse Sites” page of MonMW, similar to those that exist for the EnviroDIY and Leaf Pack Network program

**Comment by ptomasula** [comment]
Implementation was completed with commit [97fcad4](https://github.com/ODM2/ODM2DataSharingPortal/commit/97fcad466e3c5ca5174450dda5ec97c916344da7).

Our approach was to add an additional data field to the SiteRegistration model which keeps count of the number of StreamWatch assessments completed for the site. We separately implemented syncing logic in the form of SQL functions in the database to auto increment/decrement the number when StreamWatch action records are inserted/deleted.

**Comment by ptomasula** [comment]
The changes are live on the staging server.
[https://staging.monitormywatershed.org](https://staging.monitormywatershed.org)

**Comment by aufdenkampe** [comment]
@ptomasula, Can we change the title of the filter from "Data Types" to "Programs".

![image](https://user-images.githubusercontent.com/5166036/227003021-1bb89f00-44a1-4f69-af0c-35f69adb498d.png)

**Comment by ptomasula** [comment]
@aufdenkampe. I changed this in commit [d1447cc](https://github.com/ODM2/ODM2DataSharingPortal/commit/d1447ccdb6f2bf4aeb54df7e062c6f28aec75d99).
