### ISSUE TITLE
Anchor Link for StreamWatch program location

### ISSUE THREAD

**Issue by ptomasula** [ODM2/ODM2DataSharingPortal#647]
@aufdenkampe 

The creation of an “Anchor Link” at the StreamWatch program location on the MonMW homepage

**Comment by ptomasula** [comment]
This has been added in commit [4d8dba7](https://github.com/ODM2/ODM2DataSharingPortal/commit/4d8dba7509c79640eb20aea40ba3505a4ba4f064). Once live users will be able to navigate to the StreamWatch panel on the home page through the link [https://monitormywatershed.org/#StreamWatch](https://monitormywatershed.org/#StreamWatch)

**Comment by aufdenkampe** [comment]
@ptomasula, when I test on https://staging.monitormywatershed.org/#streamwatch, it's not autoscrolling down the page to this view, as intended:

![image](https://user-images.githubusercontent.com/5166036/227002200-ec907253-8c04-4630-97a8-23177aca33f7.png)

**Comment by aufdenkampe** [comment]
@ptomasula, https://staging.monitormywatershed.org/#StreamWatch works! Thanks.
