### ISSUE TITLE
Unable to delete leaf pack experiment from details page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#655]
![image](https://user-images.githubusercontent.com/5374350/235470225-51432698-af2e-4b18-aefb-2225d888b5c1.png)

Hitting the delete menu brings up a delete confirmation menu, but after confirming you're forwarded to an empty page (https://monitormywatershed.org/sites/xx/leafpack/delete/). If you go back and look at the experiments for the site, the "deleted" experiment still exists.

**Comment by ptomasula** [comment]
Thanks @SRGDamia1, I addressed this with PR #656 yesterday, and then redeployed it to the production server this afternoon with PR #657. Let me know if the delete button is still not working for you.
