### ISSUE TITLE
Create path for users to transfer station ownership

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#660]
One of the most frequent requests is to transfer station ownership from one user to another. Since it's such a common problem, there should be a way for users to do it without our direct interaction.

**Comment by ptomasula** [comment]
This has been addressed with issue #687. The `Deploy Site For` drop down on the edit site page will now allow users to transfer sites between their individual organizations (`myself` in the drop down) or any of the organizations with which they are affiliated.
