### ISSUE TITLE
MMW Notification not operating

### ISSUE THREAD

**Issue by neilh10** [ODM2/ODM2DataSharingPortal#675]
I'm not getting a notification on my sites not receiving data.
There is a checkbox on managing site eg https://monitormywatershed.org/sites/tu_rc_test08/ says
 "You will be notified if this site stops receiving sensor data after: 4.0 hours."

And I haven't received any in its testing. 

The last record I have, from any site is  8 Aug 2022,  I don't see any bug reports on this since then, so originating a new bug.

-------- Forwarded Message --------
Subject: 	Monitor My Watershed Notification: No data received for site Laguna da Santa Rosa @ E Cotati Ave in the last 12 hours
Date: 	Mon, 8 Aug 2022 13:00:04 +0000
From: 	EnviroDIY Site Alert <monitormywatershedalerts@stroudcenter.org>
To: 	

Neil,

This email is to notify you that your Monitor My Watershed site "Laguna da Santa Rosa @ E Cotati Ave" has not received any new data values in the last 12 hours. The last update was on 2022-08-08 00:15:00. You may want to check your equipment to ensure it's working as intended.
https://www.monitormywatershed.org/sites/nh_LCC45/

Best regards,
The Monitor My Watershed Team

**Comment by ptomasula** [comment]
Thanks @neilh10, I will look into the issue. I've confirmed that the system is running the check on an hourly basis, so it must be something wrong with the check itself.

**Comment by ptomasula** [comment]
@neilh10 I believe I have resolved this issue with my hotfix #676. This was due to the alerts code referencing stale account models. Our email system indicates that 76 alert emails went out. Let us know if you are still seeing issues. Thanks again!

**Comment by neilh10** [comment]
@ptomasula many thanks. I had useful notifications of some sites not getting data already!! Now why have those sites stopped.
