### ISSUE TITLE
Restructure "backend" site ownership from individuals to organizations

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#687]
This high-level and relatively restructuring of the "backend" is required to eventually allow organizations to oversee the management of (and payment for) a number of sites while allowing organization members the ability to add data to those same sites.

This work will not yet include new user features.

**Comment by ptomasula** [comment]
This has been implemented on staging. Site ownership has be changed from individual accounts to organizations, with every user being assigned a personal 'organization' that consists on only their account. This provides a foundation for us to start developing multi-user organization feature like multiuser administration/editing of sites.
