### ISSUE TITLE
Staging: Map location is off on the browse window

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#690]
![image](https://github.com/ODM2/ODM2DataSharingPortal/assets/5374350/56003ac6-7a85-48f7-a75e-e2a5a550ff4a)

**Comment by ptomasula** [comment]
@SRGDamia1 can you confirm how you produced this issue. I suspect that it was related to zooming on the page. In which case this is a known bug related to #633.

**Comment by SRGDamia1** [comment]
@ptomasula yes, this is probably a dup of #633.
