### ISSUE TITLE
Staging: All sites belonging to my organization show up as my sites on the my sites page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#691]
I now see all 68 Stroud sites as my own on the my sites page, rather than the few that I'm the primary contact for.

On staging:
![image](https://github.com/ODM2/ODM2DataSharingPortal/assets/5374350/9deeda71-15c4-4d8b-ba1d-ab25c5f8d45d)

On production:
![image](https://github.com/ODM2/ODM2DataSharingPortal/assets/5374350/09bc57be-e28d-4297-9288-ee2f6da2bfd4)

**Comment by ptomasula** [comment]
This has to do with the changed definition of ownership and would be the behavior I expect. You are affiliated with the Stroud Center's organization and thereby have access to their sites. I think one thing that could help is if we binned the sites by organization affiliation or something so they were a little easier to navigate around, or tell which of the sites are your personal ones and which are by affiliation.

**Comment by SRGDamia1** [comment]
In the my sites page, I'd like to see categories like "my sites within org x", "sites within org x", "my sites in org y", etc.

**Comment by ptomasula** [comment]
I have changed the page to group sites by organizations. The sites owned by your personal organization will always be on top, followed by affiliated organization in alphabetical order, with followed sites on the bottom.
![image](https://github.com/ODM2/ODM2DataSharingPortal/assets/31142705/55db5961-9b59-4282-9473-dcfd3b2c7a0a)

**Comment by aufdenkampe** [comment]
@ptomasula, this looks great!
