### ISSUE TITLE
Staging: My "personal" organization isn't visible in the my accounts page and I cannot transfer my site to it

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#694]
Should I be able to see this or transfer sites to it?

**Comment by ptomasula** [comment]
I think this was a bug at the time you tested the staging sites, and is now resolved. There should be a `myself` option in the dropdown to allow you to transfer a site to your individual organization. 
![image](https://github.com/ODM2/ODM2DataSharingPortal/assets/31142705/ce948b46-84fd-431d-8975-e38440f9a535)
