### ISSUE TITLE
Remove outdated Google Analytics tracking code

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#700]
The UA tracking code stopped collecting data in July 2023 and should be removed. I have verified that the GA4 tracking code is working properly. Thank you!
![monitormw-old-gtag](https://github.com/ODM2/ODM2DataSharingPortal/assets/9368629/3623787d-46e0-42aa-ace5-7521662b397e)
[ga4-report.pdf](https://github.com/ODM2/ODM2DataSharingPortal/files/14284073/ga4-report.pdf)

**Comment by ptomasula** [comment]
Looks like PR #674 includes removal of this analytics code.
