### ISSUE TITLE
New Users do not have individual organization seeded when the log in the first time

### ISSUE THREAD

**Issue by ptomasula** [ODM2/ODM2DataSharingPortal#708]
This was likely over looked in [release 0.17](https://github.com/ODM2/ODM2DataSharingPortal/releases/tag/v0.17.0), but with a change to organizational ownership, each individual account also has an organization record associated with them. These were auto generated for users upon release, but they do not appear to be generated automatically for new users.

**Comment by SRGDamia1** [comment]
There's also no way for a new user to select an organization for themselves. With the Cognito registration flow, the user doesn't select an organization at registration. The edit user page also does not allow the user to modify their organization.

This may be related to the inability to view the sites page or create a new site in https://github.com/ODM2/ODM2DataSharingPortal/issues/709
