### ISSUE TITLE
New user unable to access the "My Sites" page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#710]
Split from #709 

![image](https://github.com/ODM2/ODM2DataSharingPortal/assets/5374350/b8166476-5dd8-4bd4-a714-2882081fe26a)

Could this be the guilty line: https://github.com/ODM2/ODM2DataSharingPortal/blob/66999c359f94a42d96e12cdd82a733efe83d1863/src/dataloaderinterface/views.py#L99

**Comment by ptomasula** [comment]
I think one is just a side effect of #708. Like one among a number of side effects, so I'll work on resolving #708 ASAP.

The followed_by logic has not changed and that is still controlled on an account basis. I think line 89 is a more likely candidate, but I'll dig into this. 

https://github.com/ODM2/ODM2DataSharingPortal/blob/66999c359f94a42d96e12cdd82a733efe83d1863/src/dataloaderinterface/views.py#L89

**Comment by ptomasula** [comment]
@SRGDamia1 I resolved #708, so this issue should now also be resolved. Let me know if you are still seeing issues.

**Comment by SRGDamia1** [comment]
Great, works for me now!
