### ISSUE TITLE
Data download button attempts to download HTM rather than CSV file

### ISSUE THREAD

**Issue by HeatherBrooks** [ODM2/ODM2DataSharingPortal#713]
Issue reported this morning through the WikiWatershed.org contact form. I tried downloading the data for a different site (OCTPA010) when logged in to my StroudCenter account and got the same results.

> The data download for my site (jrm001) does not seem to be working. When I click the button, it immediately starts to download an HTML file rather than compiling the .CSV that would hold the data.

![download-htm](https://github.com/ODM2/ODM2DataSharingPortal/assets/9368629/f67875e1-d472-440a-afee-c56cf89fe11a)

**Comment by HeatherBrooks** [comment]
Jake Lemon from TU also reported this on the EnviroDIY Monitor My Watershed forum: [https://www.envirodiy.org/topic/mmw-site-download-sensor-data/](https://www.envirodiy.org/topic/mmw-site-download-sensor-data/)

**Comment by ptomasula** [comment]
This is resolved and deployed to production.
