### ISSUE TITLE
Is there any updated deployment guide?

### ISSUE THREAD

**Issue by KenTSUI-dev** [ODM2/ODM2DataSharingPortal#723]
I am reading the [deployment guide](https://github.com/ODM2/ODM2DataSharingPortal/blob/main/doc/deployment_guide.md) but find that something may be outdated.  For example, I can't find `https://github.com/LimnoTech/ODM2DataSharingPortalConfig.git`.  Is there any updated deployment guide?  Thank you.

**Comment by aufdenkampe** [comment]
Our deployment guide is indeed outdated, and our current plan is to update our docs for our next release. Closing this issue, as we're tracking this task here:
- #697
