### ISSUE TITLE
Include a button linking users to a submission form to request new sensors/variables

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#73]
Have users fill in a simple for that sends a notification to the system admins who would then vett the submissions and add the new submission via the admin interface. No need for a full moderation system built in Django.

**Comment by horsburgh** [comment]
The form will need to collect enough information from the user that an admin of the system could identify the sensor and its output variables. Then one of us admin users can add the sensor and its variable(s) to the application. When a user submits a request via this form, it should email the submitted information to the admin users. We will not build a moderation system or automated approval system for this. The simple workflow is: 
1. User submits request via the form 
2. The application emails the request information to the admin users of the system
3. An admin looks up the requested sensor and gets required variable information
4. Admin adds the sensor and its output variable(s) using the admin functionality for adding new sensors/variables describe in #71 .

**Comment by aufdenkampe** [comment]
The ability for users to add new sensors is fundamental for this portal to grow in use.
Can we manage the sensor list using the http://vocabulary.odm2.org system?

**Comment by horsburgh** [comment]
@aufdenkampe and @SRGDamia1 - it is beyond the scope of the current project to build a user submission and moderation system for sensors. And, given that users are citizen scientists, I think anything we do to resolve this needs to be encapulated into the page. So, to address this issue, we are going to add text to the "Add Sensor" modal window that says:

> Don't see your sensor in the list of equipment models? Click here to send an email to a system administrator with a request to add new sensors. Please provide us with the manufacturer and make/model information for the sensor, as well as a link to a website description if you can.

We need to know from you who should receive those email requests. My developers can add additional sensors to the database for now, and we may consider a Django admin interface for this if we have time later on. To add new sensors to the database we will continue to need your team to provide all of the information that goes into the Google spreadsheet that describes sensors.

**Comment by aufdenkampe** [comment]
@horsburgh, your proposed "Add Sensor" modal window sounds like a very good approach for now.

@SRGDamia1, can we set up a Google Group for this kind of support, similar https://groups.google.com/a/stroudcenter.org/forum/#!forum/wikiwatershed-help, which we setup as a collaborative inbox with multiple (and potentially revolving) recipients?

**Comment by SRGDamia1** [comment]
clicking "here" goes to "mailto:someone@example.com?Subject=Hello again".  I think the link should be "mailto:iutah.ci@gmail.com?Subject=Request for new sensor".

**Comment by horsburgh** [comment]
@SRGDamia1 - this email needs to go to someone that will respond by adding the sensor to the database through the admin interface. Whose email should be use?

**Comment by SRGDamia1** [comment]
Um.  Mine, then, I guess.

**Comment by aufdenkampe** [comment]
We should create a Google Group & email, similar to <wikiwatershed-help@stroudcenter.org>, which @HeatherBrooks created for us. Emails sent from the Questions webform (https://wikiwatershed.org/help/#contact) get forwarded to all the members of the group, which can change over time.

@HeatherBrooks or @SRGDamia1, can you create a similar "wikiwatershed-data-portal-help" or "data-portal-help"Google Group that we could use?

**Comment by aufdenkampe** [comment]
@HeatherBrooks just created this for us to use: ww-data-portal-help@googlegroups.com

**Comment by Maurier** [comment]
Thanks, I made the change and will be reflected on the next update to the sandbox.

**Comment by aufdenkampe** [comment]
@Maurier, I don't see this change in email address on sandbox yet. Instead, the copy to clipboard address is iutah.ci@gmail.com. The click here link, opens up an empty email to someone@example.com. 

So does that mean that we're not testing your latest code? 
I refreshed my browser 3x times, to clear caches. 

Please let me know when we can test that.

**Comment by Maurier** [comment]
That's correct. @jcaraballo17 can we get the latest update in the sandbox?

**Comment by aufdenkampe** [comment]
Thanks for looking into and putting the latest code into the sandbox for @SRGDamia1 and I to test.

**Comment by Maurier** [comment]
The sandbox has been updated now.
