### ISSUE TITLE
Include a depth (z) offset for profile-type data within a site

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#75]
- For sensors in lakes
- Using ODM2 offset field? No - store using X, Y, Z location of TimeSeriesResult
    - Depth = Z, in meters
- This can be stored easily in the ODM2 database, but need to implement input from user via the web forms.
- Users need to input this information when registering a Site/Variable
    - All sensors may have the same offset
    - All sensors may have no offset
    - Each sensor may have a different offset
- Need to make clear to users the difference between a sensor with a true vertical offset and a sensor that is measuring depth and may have an offset that changes small amounts as it’s cleaned

**Comment by aufdenkampe** [comment]
We discussed prioritizing this in our 2017-08-10 EnviroDIY Data Portal call.
Sara captured that discussion above, for use cases where sensors are placed at multiple depths at the same station, such as:
* water sensors on buoys
* soil moisture sensors in soil pits
It can also be useful to know the nominal/approximate depth even when there is only one sensor.

Also, consider allowing user to use this to record the height of an ultrasonic water level reader? This could be helpful, but would require some clear language to distinguish this use case. 

For now, just stick to "nominal depth below surface" .

**Comment by horsburgh** [comment]
@SRGDamia1 and @aufdenkampe - ODM2 doesn't have an "offset type". So, there is no way for a user to express "nominal depth below surface". We simply record X, Y, and Z location coordinates in the "TimeSeriesResults" table. For display purposes, we can infer any negative Z values to be a depth below the surface and any positive Z values to be hight above the ground or water surface. On the user interface when they register a sensor, we can give them the option of an offset that is above the ground or water surface (recorded as a positive Z value in the database) or below the ground or water surface (recorded as a negative value in the database).

**Comment by SRGDamia1** [comment]
That seems fine to me.

**Comment by aufdenkampe** [comment]
@horsburgh, good point. That UI approach sounds like a great solution.
We want to make sure that the single header makes sense in the Sensor table list (in Edit Site view) and the Result Sparkline "Card".  

Would this work: "Height above(+) or below(-) surface, in meters"

**Comment by jcaraballo17** [comment]
@kwuz are you still working on this one? :)

**Comment by horsburgh** [comment]
I see where I can add the vertical offset in edit mode, and the value that I enter is saved and persisted. However, it is not displayed in view mode. @jcaraballo17 - need to add the vertical offset to the view if a value has been entered. Also - has this information been added to the CSV download files?

**Comment by horsburgh** [comment]
@jcaraballo17 - the offset information is still not displayed on the page.

**Comment by horsburgh** [comment]
I can now see the vertical offset displayed on the page. I'm going to add the "tested" label to this one.

**Comment by aufdenkampe** [comment]
Looks awesome!

**Comment by horsburgh** [comment]
Live on production. Closing.
