### ISSUE TITLE
Change download CSV to be one multi-variable CSV per site

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#79]
The ability to download a CSV is awesome (as implemented in #18). However, I think most users will want one single CSV per site, with columns for all the variables measured at that site, all sharing the same datetime row index. All the download links associated with each Result/Variable would all point to the single CSV file for that site.

@horsburgh, @jcaraballo17 and @Maurier , would this be easy to modify the current system to do? Would it reduce the resource use, by only writing to a single CSV file each time the data is updated with a POST request?

I'm not sure that this is top priority, but want to get this recorded in case addressing this enhancement makes sense while working on other things.

**Comment by horsburgh** [comment]
Isn't there only one CSV per site already?

**Comment by jcaraballo17** [comment]
One csv per sensor.

**Comment by horsburgh** [comment]
Oh - right. It's one per variable. This may be an issue for down the road. First - most of the time in the page load right now is loading all of the data values into the tabular display of the data. So, we are considering limiting the modal window that displays the tabular data to say the first 72 hours of data or the first 1000 data values or something like that. If they want to see the whole record, then they would download the CSV file. For this reason, I like having the tabular view link and the CSV link side-by-side. 

I see the point in having a single CSV download, and I think we can do that via our link with HydroShare.

**Comment by aufdenkampe** [comment]
It makes sense to me to hold off on developing this feature for when we need it for HydroShare. Hopefully the good work toward improving performance (#30) will continue to allow us to share all the data in a single download. I can see having a "last 72" hours or something like that, however, just to populate the sparklines.

**Comment by horsburgh** [comment]
There's an issue with waiting for the HydroShare connection to resolve this issue. Sharing the data in HydroShare will be an optional thing that a user can choose to turn on. If we base the CSV download on whether the user has turned on this option, then it won't work all the time. 

I suggest that we leave the CSV download for individual variables the way they are now and just add a link to the page that says "Download all data for this site as a CSV file" or something like that. The format of the CSV file would be exactly the same except that the format of the header is going to have to change to accommodate descriptions for all of the variables contained in the file and not just one variable.

**Comment by aufdenkampe** [comment]
That sounds like a good solution.

**Comment by horsburgh** [comment]
I've tested the "Download Site Sensor Data" button on the sandbox. It produces a single CSV file with the data for all variables at the selected site. Adding the "tested" label.

**Comment by aufdenkampe** [comment]
Awesome!

Sent from my iPhone

On Jul 26, 2018, at 5:07 PM, Jeff Horsburgh <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tested the "Download Site Sensor Data" button on the sandbox. It produces a single CSV file with the data for all variables at the selected site. Adding the "tested" label.

-

**Comment by horsburgh** [comment]
Link to download all sensor time series in a single file is live on production. Closing.
