### ISSUE TITLE
Suggested "default" ordering for variables at initial site creation

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#90]
ProcessorMetadata_Batt,
ProcessorMetadata_FreeRam,
MaximDS3231_Temp,
ApogeeSQ212_PAR,
MaxBotixSonar_Range,
Decagon5TM_Ea,
Decagon5TM_Temp,
Decagon5TM_VWC,
DecagonES2_Cond,
DecagonES2_Temp,
DecagonCTD_Cond,
DecagonCTD_Temp,
DecagonCTD_Depth,
MaximDS18_Temp,
MaximDS18_Temp,
MaximDS18_Temp,
BoschBME280_Temp,
BoschBME280_Humidity,
BoschBME280_Pressure,
BoschBME280_Altitude,
AOSongDHT_Humidity,
AOSongDHT_Temp,
AOSongDHT_HI,
AOSongAM2315_Humidity,
AOSongAM2315_Temp,
CampbellOBS3_Turbidity,
CampbellOBS3_Turbidity,
YosemitechY504_DOpct,
YosemitechY504_Temp,
YosemitechY504_DOmgL,
YosemitechY510_Turbidity,
YosemitechY510_Temp,
YosemitechY514_Chlorophyll,
YosemitechY514_Temp,
YosemitechY520_Cond,
YosemitechY520_Temp,
YosemitechY532_pH,
YosemitechY532_Temp,
YosemitechY532_Voltage,
Modem_RSSI,
Modem_SignalPercent,
Previous_send_successful

**Comment by SRGDamia1** [comment]
This is the ordering by how long it takes each sensor to spit out a value from the time power is applied.  Ideally, someone using the modular sensors library would order their variables this way to minimize the logger awake time.

**Comment by aufdenkampe** [comment]
This is a great idea. I've been doing this ordering manually and it is a pain.

**Comment by SRGDamia1** [comment]
This would definitely be helpful, though I think ensuring that the order never changes after initial creation (#89) is much more important.  The current libraries I've built to send data to from an Arduino are completely dependent on the ordering of variables matching exactly in the variable array and the GUID array.  This means being able to see the GUID for a particlar variable (#92) is really important for debugging.

**Comment by SRGDamia1** [comment]
The ModularSensors has been improved to the point that  this is no longer necessary.
